-- Fill out the Items table, batch 11 (final): Goods. Source: PTA3PlayersHandbook.pdf page 201.
-- Flat category, no detail table, no description text -- unlike every prior category, this page is a
-- bare name+price table with zero per-item flavor/mechanical text in the source at all (self-
-- explanatory goods like "Backpack" don't need it). 75 items, closing out this FR's 11-category scope.
insert into item_categories (name) values ('Goods');

insert into items (name, item_category_id, buyable, price)
select v.name, c.id, true, v.price
from item_categories c,
(values
  ('Backpack', 5),
  ('Ball bearings (25)', 10),
  ('Bedroll', 5),
  ('Binoculars (digital)', 45),
  ('Blanket', 2),
  ('Blanket (winter)', 10),
  ('Block and tackle', 5),
  ('Bolt cutter', 10),
  ('Briefcase', 5),
  ('Camera (digital high end)', 2850),
  ('Camera (digital)', 450),
  ('Camera (film high end)', 1050),
  ('Case (aluminum)', 20),
  ('Cell phone', 80),
  ('Chain (10 ft)', 5),
  ('Chalk (10 sticks)', 1),
  ('Clothes (brand names)', 100),
  ('Clothes (custom-fit high end)', 1250),
  ('Clothes (designer brands)', 350),
  ('Clothes (camo fatigue)', 65),
  ('Clothes (generic brands)', 35),
  ('Clothes (workout / outdoors)', 20),
  ('Computer (desktop)', 480),
  ('Computer (laptop)', 980),
  ('Computer (tablet)', 780),
  ('Cooler bag (foldable)', 10),
  ('Crowbar', 10),
  ('Duct Tape', 5),
  ('Flashlight', 2),
  ('Flask', 4),
  ('Gas mask', 25),
  ('Grappling hook', 10),
  ('Hammer', 10),
  ('Hammer (sledge)', 15),
  ('Handheld transceiver (pair)', 60),
  ('Jacket (rain)', 65),
  ('Jacket (snow)', 145),
  ('Jacket (windbreaker)', 50),
  ('Knife (folding)', 10),
  ('Ladder (folding, 10ft)', 15),
  ('Lighter', 2),
  ('Luggage bag (wheeled)', 5),
  ('Messenger bag', 5),
  ('Memory stick (100gb)', 45),
  ('Metal Detector', 30),
  ('Mobile Trailer Home (for 1)', 19800),
  ('Mobile Trailer Home (for 4)', 39800),
  ('Multi-purpose tool', 20),
  ('Night-vision goggles', 350),
  ('Padlock and key', 10),
  ('Pencils (10 coloring)', 2),
  ('Pencils (10 graphite)', 2),
  ('Pens (10 coloring)', 2),
  ('Pens (5 writing)', 2),
  ('Pick', 10),
  ('Pitons (5)', 5),
  ('Pole (steel, 10 ft)', 5),
  ('Rope (50 ft)', 5),
  ('Saddle (large)', 35),
  ('Saddle (massive)', 55),
  ('Saddle (small)', 15),
  ('Shovel (folding)', 10),
  ('Smartphone', 580),
  ('Soap / Shampoo / Toothpaste', 4),
  ('Tent (folding, two-person)', 35),
  ('Vehicle (bus)', 248800),
  ('Vehicle (car)', 49800),
  ('Vehicle (camper)', 124800),
  ('Vehicle (motorcycle)', 4980),
  ('Vehicle (truck)', 69800),
  ('Vehicle (van)', 49800),
  ('Vial', 5),
  ('Wallet', 5),
  ('Whistle', 2),
  ('Zip ties (30)', 10)
) as v(name, price)
where c.name = 'Goods';
