-- [[Bug - It looks like effectiveness is broken]]: `type_matchups` (should have 112 rows, seeded by
-- 20260810150000_type_matchups.sql) and `type_immunities` (should have 8 rows, seeded by
-- 20260815100000_type_immunities.sql) were found empty on the shared dev DB despite both migrations
-- showing as applied -- root cause unconfirmed (most likely an out-of-band reset/restore against the
-- shared DB, per [[supabase_migration_branch_discipline]]'s "shared hosted DB isn't branched" caveat),
-- but the fix is the same regardless: re-seed both tables (both original inserts already end in
-- `on conflict ... do nothing`, so simply re-running them is safe no matter their current state).
--
-- Also closes a separate, real gap found while investigating: neither original migration ever enabled
-- RLS on these two tables (confirmed via grep -- every other reference table gets `enable row level
-- security` + a "Public read access" policy in its own creating migration; these two never did).

alter table type_matchups enable row level security;
create policy "Public read access" on type_matchups for select using (true);

alter table type_immunities enable row level security;
create policy "Public read access" on type_immunities for select using (true);

insert into type_matchups (attacking_type_id, defending_type_id, modifier) values
  ((select id from types where name = 'Bug'), (select id from types where name = 'Dark'), 1),
  ((select id from types where name = 'Bug'), (select id from types where name = 'Fairy'), -1),
  ((select id from types where name = 'Bug'), (select id from types where name = 'Fighting'), -1),
  ((select id from types where name = 'Bug'), (select id from types where name = 'Fire'), -1),
  ((select id from types where name = 'Bug'), (select id from types where name = 'Flying'), -1),
  ((select id from types where name = 'Bug'), (select id from types where name = 'Ghost'), -1),
  ((select id from types where name = 'Bug'), (select id from types where name = 'Grass'), 1),
  ((select id from types where name = 'Bug'), (select id from types where name = 'Poison'), -1),
  ((select id from types where name = 'Bug'), (select id from types where name = 'Psychic'), 1),
  ((select id from types where name = 'Bug'), (select id from types where name = 'Steel'), -1),
  ((select id from types where name = 'Dark'), (select id from types where name = 'Dark'), -1),
  ((select id from types where name = 'Dark'), (select id from types where name = 'Fairy'), -1),
  ((select id from types where name = 'Dark'), (select id from types where name = 'Fighting'), -1),
  ((select id from types where name = 'Dark'), (select id from types where name = 'Ghost'), 1),
  ((select id from types where name = 'Dark'), (select id from types where name = 'Psychic'), 1),
  ((select id from types where name = 'Dragon'), (select id from types where name = 'Dragon'), 1),
  ((select id from types where name = 'Dragon'), (select id from types where name = 'Steel'), -1),
  ((select id from types where name = 'Electric'), (select id from types where name = 'Dragon'), -1),
  ((select id from types where name = 'Electric'), (select id from types where name = 'Electric'), -1),
  ((select id from types where name = 'Electric'), (select id from types where name = 'Flying'), 1),
  ((select id from types where name = 'Electric'), (select id from types where name = 'Grass'), -1),
  ((select id from types where name = 'Electric'), (select id from types where name = 'Water'), 1),
  ((select id from types where name = 'Fairy'), (select id from types where name = 'Dark'), 1),
  ((select id from types where name = 'Fairy'), (select id from types where name = 'Dragon'), 1),
  ((select id from types where name = 'Fairy'), (select id from types where name = 'Fighting'), 1),
  ((select id from types where name = 'Fairy'), (select id from types where name = 'Fire'), -1),
  ((select id from types where name = 'Fairy'), (select id from types where name = 'Poison'), -1),
  ((select id from types where name = 'Fairy'), (select id from types where name = 'Steel'), -1),
  ((select id from types where name = 'Fighting'), (select id from types where name = 'Bug'), -1),
  ((select id from types where name = 'Fighting'), (select id from types where name = 'Dark'), 1),
  ((select id from types where name = 'Fighting'), (select id from types where name = 'Fairy'), -1),
  ((select id from types where name = 'Fighting'), (select id from types where name = 'Flying'), -1),
  ((select id from types where name = 'Fighting'), (select id from types where name = 'Ice'), 1),
  ((select id from types where name = 'Fighting'), (select id from types where name = 'Normal'), 1),
  ((select id from types where name = 'Fighting'), (select id from types where name = 'Poison'), -1),
  ((select id from types where name = 'Fighting'), (select id from types where name = 'Psychic'), -1),
  ((select id from types where name = 'Fighting'), (select id from types where name = 'Rock'), 1),
  ((select id from types where name = 'Fighting'), (select id from types where name = 'Steel'), 1),
  ((select id from types where name = 'Fire'), (select id from types where name = 'Bug'), 1),
  ((select id from types where name = 'Fire'), (select id from types where name = 'Dragon'), -1),
  ((select id from types where name = 'Fire'), (select id from types where name = 'Fire'), -1),
  ((select id from types where name = 'Fire'), (select id from types where name = 'Grass'), 1),
  ((select id from types where name = 'Fire'), (select id from types where name = 'Ice'), 1),
  ((select id from types where name = 'Fire'), (select id from types where name = 'Rock'), -1),
  ((select id from types where name = 'Fire'), (select id from types where name = 'Steel'), 1),
  ((select id from types where name = 'Fire'), (select id from types where name = 'Water'), -1),
  ((select id from types where name = 'Flying'), (select id from types where name = 'Bug'), 1),
  ((select id from types where name = 'Flying'), (select id from types where name = 'Electric'), -1),
  ((select id from types where name = 'Flying'), (select id from types where name = 'Fighting'), 1),
  ((select id from types where name = 'Flying'), (select id from types where name = 'Grass'), 1),
  ((select id from types where name = 'Flying'), (select id from types where name = 'Rock'), -1),
  ((select id from types where name = 'Flying'), (select id from types where name = 'Steel'), -1),
  ((select id from types where name = 'Ghost'), (select id from types where name = 'Dark'), -1),
  ((select id from types where name = 'Ghost'), (select id from types where name = 'Ghost'), 1),
  ((select id from types where name = 'Ghost'), (select id from types where name = 'Psychic'), 1),
  ((select id from types where name = 'Grass'), (select id from types where name = 'Bug'), -1),
  ((select id from types where name = 'Grass'), (select id from types where name = 'Dragon'), -1),
  ((select id from types where name = 'Grass'), (select id from types where name = 'Fire'), -1),
  ((select id from types where name = 'Grass'), (select id from types where name = 'Flying'), -1),
  ((select id from types where name = 'Grass'), (select id from types where name = 'Grass'), -1),
  ((select id from types where name = 'Grass'), (select id from types where name = 'Ground'), 1),
  ((select id from types where name = 'Grass'), (select id from types where name = 'Poison'), -1),
  ((select id from types where name = 'Grass'), (select id from types where name = 'Rock'), 1),
  ((select id from types where name = 'Grass'), (select id from types where name = 'Steel'), -1),
  ((select id from types where name = 'Grass'), (select id from types where name = 'Water'), 1),
  ((select id from types where name = 'Ground'), (select id from types where name = 'Bug'), -1),
  ((select id from types where name = 'Ground'), (select id from types where name = 'Electric'), 1),
  ((select id from types where name = 'Ground'), (select id from types where name = 'Fire'), 1),
  ((select id from types where name = 'Ground'), (select id from types where name = 'Grass'), -1),
  ((select id from types where name = 'Ground'), (select id from types where name = 'Poison'), 1),
  ((select id from types where name = 'Ground'), (select id from types where name = 'Rock'), 1),
  ((select id from types where name = 'Ground'), (select id from types where name = 'Steel'), 1),
  ((select id from types where name = 'Ice'), (select id from types where name = 'Dragon'), 1),
  ((select id from types where name = 'Ice'), (select id from types where name = 'Fire'), -1),
  ((select id from types where name = 'Ice'), (select id from types where name = 'Flying'), 1),
  ((select id from types where name = 'Ice'), (select id from types where name = 'Grass'), 1),
  ((select id from types where name = 'Ice'), (select id from types where name = 'Ground'), 1),
  ((select id from types where name = 'Ice'), (select id from types where name = 'Ice'), -1),
  ((select id from types where name = 'Ice'), (select id from types where name = 'Steel'), -1),
  ((select id from types where name = 'Ice'), (select id from types where name = 'Water'), -1),
  ((select id from types where name = 'Normal'), (select id from types where name = 'Rock'), -1),
  ((select id from types where name = 'Normal'), (select id from types where name = 'Steel'), -1),
  ((select id from types where name = 'Poison'), (select id from types where name = 'Fairy'), 1),
  ((select id from types where name = 'Poison'), (select id from types where name = 'Ghost'), -1),
  ((select id from types where name = 'Poison'), (select id from types where name = 'Grass'), 1),
  ((select id from types where name = 'Poison'), (select id from types where name = 'Ground'), -1),
  ((select id from types where name = 'Poison'), (select id from types where name = 'Poison'), -1),
  ((select id from types where name = 'Poison'), (select id from types where name = 'Rock'), -1),
  ((select id from types where name = 'Psychic'), (select id from types where name = 'Fighting'), 1),
  ((select id from types where name = 'Psychic'), (select id from types where name = 'Poison'), 1),
  ((select id from types where name = 'Psychic'), (select id from types where name = 'Psychic'), -1),
  ((select id from types where name = 'Psychic'), (select id from types where name = 'Steel'), -1),
  ((select id from types where name = 'Rock'), (select id from types where name = 'Bug'), 1),
  ((select id from types where name = 'Rock'), (select id from types where name = 'Fighting'), -1),
  ((select id from types where name = 'Rock'), (select id from types where name = 'Fire'), 1),
  ((select id from types where name = 'Rock'), (select id from types where name = 'Flying'), 1),
  ((select id from types where name = 'Rock'), (select id from types where name = 'Ground'), -1),
  ((select id from types where name = 'Rock'), (select id from types where name = 'Ice'), 1),
  ((select id from types where name = 'Rock'), (select id from types where name = 'Steel'), -1),
  ((select id from types where name = 'Steel'), (select id from types where name = 'Electric'), -1),
  ((select id from types where name = 'Steel'), (select id from types where name = 'Fairy'), 1),
  ((select id from types where name = 'Steel'), (select id from types where name = 'Fire'), -1),
  ((select id from types where name = 'Steel'), (select id from types where name = 'Ice'), 1),
  ((select id from types where name = 'Steel'), (select id from types where name = 'Rock'), 1),
  ((select id from types where name = 'Steel'), (select id from types where name = 'Steel'), -1),
  ((select id from types where name = 'Steel'), (select id from types where name = 'Water'), -1),
  ((select id from types where name = 'Water'), (select id from types where name = 'Dragon'), -1),
  ((select id from types where name = 'Water'), (select id from types where name = 'Fire'), 1),
  ((select id from types where name = 'Water'), (select id from types where name = 'Grass'), -1),
  ((select id from types where name = 'Water'), (select id from types where name = 'Ground'), 1),
  ((select id from types where name = 'Water'), (select id from types where name = 'Rock'), 1),
  ((select id from types where name = 'Water'), (select id from types where name = 'Water'), -1)
on conflict (attacking_type_id, defending_type_id) do nothing;

insert into type_immunities (attacking_type_id, defending_type_id) values
  ((select id from types where name = 'Normal'), (select id from types where name = 'Ghost')),
  ((select id from types where name = 'Fighting'), (select id from types where name = 'Ghost')),
  ((select id from types where name = 'Ghost'), (select id from types where name = 'Normal')),
  ((select id from types where name = 'Electric'), (select id from types where name = 'Ground')),
  ((select id from types where name = 'Ground'), (select id from types where name = 'Flying')),
  ((select id from types where name = 'Poison'), (select id from types where name = 'Steel')),
  ((select id from types where name = 'Psychic'), (select id from types where name = 'Dark')),
  ((select id from types where name = 'Dragon'), (select id from types where name = 'Fairy'))
on conflict (attacking_type_id, defending_type_id) do nothing;
