-- Size/Weight tiers for this session's Pokedex-expansion species, sourced from the
-- PTA3 Pokedex sourcebook PDF (page-by-page species stat-blocks) rather than PokeAPI -- confirmed
-- during Design that PokeAPI's raw height/weight can't be mechanically mapped to this game's tiers
-- (two species sharing an exact real height landed in different tiers). Extracted via a parser that
-- cross-validates every name match against this game's own base stats (already known independently
-- from the PokeAPI import) before trusting it, rather than trusting text proximity alone.
--
-- Covers 543 of this session's 635 new species (the rest -- mostly Legendaries/
-- Mythicals/Ultra Beasts -- have no stat-block entry in this PDF at all, a real gap in the source
-- material, not a parser miss; a handful of ordinary species were left out where the PDF's two-column
-- layout defeated extraction and couldn't be safely resolved).

update pokedex set size_id = 4, weight_id = 4 where id = 1088; -- Wartortle
update pokedex set size_id = 5, weight_id = 3 where id = 976; -- Weedle
update pokedex set size_id = 4, weight_id = 4 where id = 977; -- Kakuna
update pokedex set size_id = 4, weight_id = 4 where id = 978; -- Beedrill
update pokedex set size_id = 5, weight_id = 3 where id = 994; -- Wurmple
update pokedex set size_id = 5, weight_id = 3 where id = 995; -- Silcoon
update pokedex set size_id = 4, weight_id = 4 where id = 996; -- Beautifly
update pokedex set size_id = 5, weight_id = 4 where id = 997; -- Cascoon
update pokedex set size_id = 4, weight_id = 4 where id = 998; -- Dustox
update pokedex set size_id = 5, weight_id = 3 where id = 1010; -- Combee
update pokedex set size_id = 4, weight_id = 4 where id = 1011; -- Vespiquen
update pokedex set size_id = 6, weight_id = 1 where id = 1025; -- Cutiefly
update pokedex set size_id = 6, weight_id = 1 where id = 1026; -- Ribombee
update pokedex set size_id = 5, weight_id = 4 where id = 1013; -- Dwebble
update pokedex set size_id = 4, weight_id = 5 where id = 1014; -- Crustle
update pokedex set size_id = 6, weight_id = 1 where id = 1017; -- Joltik
update pokedex set size_id = 3, weight_id = 4 where id = 1018; -- Galvantula
update pokedex set size_id = 5, weight_id = 3 where id = 1015; -- Karrablast
update pokedex set size_id = 4, weight_id = 4 where id = 1016; -- Escavalier
update pokedex set size_id = 5, weight_id = 1 where id = 1006; -- Kricketot
update pokedex set size_id = 4, weight_id = 4 where id = 1007; -- Kricketune
update pokedex set size_id = 4, weight_id = 4 where id = 1022; -- Larvesta
update pokedex set size_id = 3, weight_id = 4 where id = 1023; -- Volcarona
update pokedex set size_id = 4, weight_id = 4 where id = 985; -- Ledyba
update pokedex set size_id = 4, weight_id = 4 where id = 986; -- Ledian
update pokedex set size_id = 6, weight_id = 1 where id = 1034; -- Nymble
update pokedex set size_id = 4, weight_id = 4 where id = 1035; -- Lokix
update pokedex set size_id = 5, weight_id = 3 where id = 979; -- Paras
update pokedex set size_id = 4, weight_id = 4 where id = 980; -- Parasect
update pokedex set size_id = 5, weight_id = 3 where id = 990; -- Pineco
update pokedex set size_id = 3, weight_id = 2 where id = 991; -- Forretress
update pokedex set size_id = 6, weight_id = 1 where id = 1036; -- Rellor
update pokedex set size_id = 5, weight_id = 3 where id = 1037; -- Rabsca
update pokedex set size_id = 5, weight_id = 3 where id = 1019; -- Shelmet
update pokedex set size_id = 4, weight_id = 4 where id = 1020; -- Accelgor
update pokedex set size_id = 5, weight_id = 3 where id = 987; -- Spinarak
update pokedex set size_id = 4, weight_id = 4 where id = 988; -- Ariados
update pokedex set size_id = 5, weight_id = 1 where id = 999; -- Surskit
update pokedex set size_id = 4, weight_id = 3 where id = 1000; -- Masquerain
update pokedex set size_id = 5, weight_id = 3 where id = 1032; -- Tarountula
update pokedex set size_id = 4, weight_id = 4 where id = 1033; -- Spidops
update pokedex set size_id = 4, weight_id = 4 where id = 981; -- Venonat
update pokedex set size_id = 4, weight_id = 4 where id = 982; -- Venomoth
update pokedex set size_id = 5, weight_id = 4 where id = 1027; -- Wimpod
update pokedex set size_id = 3, weight_id = 2 where id = 1028; -- Golisopod
update pokedex set size_id = 4, weight_id = 4 where id = 989; -- Yanma
update pokedex set size_id = 3, weight_id = 4 where id = 1012; -- Yanmega
update pokedex set size_id = 6, weight_id = 3 where id = 1008; -- Burmy
update pokedex set size_id = 4, weight_id = 4 where id = 1009; -- Mothim
update pokedex set size_id = 5, weight_id = 3 where id = 1001; -- Nincada
update pokedex set size_id = 5, weight_id = 3 where id = 1002; -- Ninjask
update pokedex set size_id = 5, weight_id = 1 where id = 1003; -- Shedinja
update pokedex set size_id = 4, weight_id = 2 where id = 992; -- Scizor
update pokedex set size_id = 4, weight_id = 2 where id = 1031; -- Kleavor
update pokedex set size_id = 4, weight_id = 4 where id = 1021; -- Durant
update pokedex set size_id = 4, weight_id = 4 where id = 984; -- Pinsir
update pokedex set size_id = 4, weight_id = 4 where id = 1004; -- Volbeat
update pokedex set size_id = 4, weight_id = 4 where id = 1005; -- Illumise
update pokedex set size_id = 5, weight_id = 4 where id = 1298; -- Deino
update pokedex set size_id = 4, weight_id = 4 where id = 1299; -- Zweilous
update pokedex set size_id = 3, weight_id = 2 where id = 1300; -- Hydreigon
update pokedex set size_id = 5, weight_id = 4 where id = 1294; -- Pawniard
update pokedex set size_id = 4, weight_id = 2 where id = 1295; -- Bisharp
update pokedex set size_id = 3, weight_id = 2 where id = 1312; -- Kingambit
update pokedex set size_id = 3, weight_id = 4 where id = 1307; -- Obstagoon
update pokedex set size_id = 5, weight_id = 3 where id = 1301; -- Inkay
update pokedex set size_id = 3, weight_id = 4 where id = 1302; -- Malamar
update pokedex set size_id = 5, weight_id = 4 where id = 1310; -- Maschiff
update pokedex set size_id = 3, weight_id = 2 where id = 1311; -- Mabosstiff
update pokedex set size_id = 5, weight_id = 1 where id = 1283; -- Murkrow
update pokedex set size_id = 4, weight_id = 4 where id = 1286; -- Honchkrow
update pokedex set size_id = 5, weight_id = 3 where id = 1305; -- Nickit
update pokedex set size_id = 4, weight_id = 4 where id = 1306; -- Thievul
update pokedex set size_id = 5, weight_id = 4 where id = 1284; -- Poochyena
update pokedex set size_id = 4, weight_id = 4 where id = 1285; -- Mightyena
update pokedex set size_id = 5, weight_id = 3 where id = 1288; -- Purrloin
update pokedex set size_id = 4, weight_id = 4 where id = 1289; -- Liepard
update pokedex set size_id = 3, weight_id = 2 where id = 1309; -- Overqwil
update pokedex set size_id = 4, weight_id = 4 where id = 1290; -- Scraggy
update pokedex set size_id = 4, weight_id = 4 where id = 1291; -- Scrafty
update pokedex set size_id = 5, weight_id = 3 where id = 1296; -- Vullaby
update pokedex set size_id = 4, weight_id = 4 where id = 1297; -- Mandibuzz
update pokedex set size_id = 5, weight_id = 4 where id = 1292; -- Zorua
update pokedex set size_id = 4, weight_id = 2 where id = 1293; -- Zoroark
update pokedex set size_id = 5, weight_id = 4 where id = 1265; -- Axew
update pokedex set size_id = 4, weight_id = 4 where id = 1266; -- Fraxure
update pokedex set size_id = 3, weight_id = 2 where id = 1267; -- Haxorus
update pokedex set size_id = 5, weight_id = 4 where id = 1256; -- Bagon
update pokedex set size_id = 4, weight_id = 2 where id = 1257; -- Shelgon
update pokedex set size_id = 3, weight_id = 2 where id = 1258; -- Salamence
update pokedex set size_id = 4, weight_id = 3 where id = 1253; -- Dratini
update pokedex set size_id = 3, weight_id = 4 where id = 1254; -- Dragonair
update pokedex set size_id = 3, weight_id = 5 where id = 1255; -- Dragonite
update pokedex set size_id = 5, weight_id = 1 where id = 1275; -- Dreepy
update pokedex set size_id = 4, weight_id = 4 where id = 1276; -- Drakloak
update pokedex set size_id = 3, weight_id = 4 where id = 1277; -- Dragapult
update pokedex set size_id = 5, weight_id = 4 where id = 1280; -- Frigibax
update pokedex set size_id = 4, weight_id = 4 where id = 1281; -- Arctibax
update pokedex set size_id = 3, weight_id = 2 where id = 1282; -- Baxcalibur
update pokedex set size_id = 5, weight_id = 4 where id = 1262; -- Gible
update pokedex set size_id = 4, weight_id = 4 where id = 1263; -- Gabite
update pokedex set size_id = 3, weight_id = 2 where id = 1264; -- Garchomp
update pokedex set size_id = 5, weight_id = 3 where id = 1272; -- Goomy
update pokedex set size_id = 4, weight_id = 4 where id = 1273; -- Sliggoo
update pokedex set size_id = 3, weight_id = 2 where id = 1274; -- Goodra
update pokedex set size_id = 3, weight_id = 2 where id = 1268; -- Druddigon
update pokedex set size_id = 5, weight_id = 4 where id = 733; -- Elekid
update pokedex set size_id = 4, weight_id = 4 where id = 731; -- Electabuzz
update pokedex set size_id = 3, weight_id = 2 where id = 741; -- Electivire
update pokedex set size_id = 5, weight_id = 3 where id = 759; -- Pawmi
update pokedex set size_id = 5, weight_id = 3 where id = 760; -- Pawmo
update pokedex set size_id = 4, weight_id = 4 where id = 761; -- Pawmot
update pokedex set size_id = 5, weight_id = 3 where id = 737; -- Shinx
update pokedex set size_id = 5, weight_id = 4 where id = 738; -- Luxio
update pokedex set size_id = 4, weight_id = 4 where id = 739; -- Luxray
update pokedex set size_id = 6, weight_id = 1 where id = 744; -- Tynamo
update pokedex set size_id = 4, weight_id = 4 where id = 745; -- Eelektrik
update pokedex set size_id = 3, weight_id = 2 where id = 746; -- Eelektross
update pokedex set size_id = 4, weight_id = 4 where id = 742; -- Blitzle
update pokedex set size_id = 4, weight_id = 2 where id = 743; -- Zebstrika
update pokedex set size_id = 5, weight_id = 3 where id = 747; -- Helioptile
update pokedex set size_id = 4, weight_id = 4 where id = 748; -- Heliolisk
update pokedex set size_id = 6, weight_id = 1 where id = 762; -- Tadbulb
update pokedex set size_id = 4, weight_id = 4 where id = 763; -- Bellibolt
update pokedex set size_id = 5, weight_id = 4 where id = 754; -- Toxel
update pokedex set size_id = 5, weight_id = 3 where id = 764; -- Wattrel
update pokedex set size_id = 4, weight_id = 4 where id = 765; -- Kilowattrel
update pokedex set size_id = 5, weight_id = 4 where id = 752; -- Yamper
update pokedex set size_id = 4, weight_id = 4 where id = 753; -- Boltund
update pokedex set size_id = 3, weight_id = 2 where id = 756; -- Dracozolt
update pokedex set size_id = 5, weight_id = 3 where id = 740; -- Pachirisu
update pokedex set size_id = 5, weight_id = 1 where id = 755; -- Pincurchin
update pokedex set size_id = 5, weight_id = 3 where id = 736; -- Minun
update pokedex set size_id = 5, weight_id = 3 where id = 749; -- Togedemaru
update pokedex set size_id = 5, weight_id = 1 where id = 1315; -- Cleffa
update pokedex set size_id = 4, weight_id = 3 where id = 1313; -- Clefairy
update pokedex set size_id = 4, weight_id = 4 where id = 1314; -- Clefable
update pokedex set size_id = 6, weight_id = 1 where id = 1322; -- Floette
update pokedex set size_id = 4, weight_id = 3 where id = 1323; -- Florges
update pokedex set size_id = 5, weight_id = 3 where id = 1335; -- Tinkatink
update pokedex set size_id = 4, weight_id = 4 where id = 1336; -- Tinkatuff
update pokedex set size_id = 4, weight_id = 2 where id = 1337; -- Tinkaton
update pokedex set size_id = 5, weight_id = 1 where id = 1316; -- Togepi
update pokedex set size_id = 5, weight_id = 3 where id = 1317; -- Togetic
update pokedex set size_id = 3, weight_id = 4 where id = 1320; -- Togekiss
update pokedex set size_id = 5, weight_id = 3 where id = 1333; -- Fidough
update pokedex set size_id = 5, weight_id = 3 where id = 1334; -- Dachsbun
update pokedex set size_id = 6, weight_id = 1 where id = 1330; -- Milcery
update pokedex set size_id = 5, weight_id = 1 where id = 1331; -- Alcremie
update pokedex set size_id = 5, weight_id = 3 where id = 1318; -- Snubbull
update pokedex set size_id = 4, weight_id = 4 where id = 1319; -- Granbull
update pokedex set size_id = 6, weight_id = 1 where id = 1324; -- Spritzee
update pokedex set size_id = 5, weight_id = 4 where id = 1325; -- Aromatisse
update pokedex set size_id = 5, weight_id = 3 where id = 1326; -- Swirlix
update pokedex set size_id = 5, weight_id = 3 where id = 1327; -- Slurpuff
update pokedex set size_id = 6, weight_id = 1 where id = 1329; -- Comfey
update pokedex set size_id = 5, weight_id = 4 where id = 867; -- Machop
update pokedex set size_id = 4, weight_id = 2 where id = 868; -- Machoke
update pokedex set size_id = 3, weight_id = 2 where id = 869; -- Machamp
update pokedex set size_id = 5, weight_id = 4 where id = 865; -- Mankey
update pokedex set size_id = 4, weight_id = 4 where id = 866; -- Primeape
update pokedex set size_id = 3, weight_id = 4 where id = 897; -- Annihilape
update pokedex set size_id = 5, weight_id = 4 where id = 878; -- Timburr
update pokedex set size_id = 4, weight_id = 4 where id = 879; -- Gurdurr
update pokedex set size_id = 3, weight_id = 2 where id = 880; -- Conkeldurr
update pokedex set size_id = 5, weight_id = 3 where id = 891; -- Clobbopus
update pokedex set size_id = 4, weight_id = 4 where id = 892; -- Grapploct
update pokedex set size_id = 4, weight_id = 3 where id = 888; -- Crabrawler
update pokedex set size_id = 4, weight_id = 2 where id = 889; -- Crabominable
update pokedex set size_id = 4, weight_id = 2 where id = 893; -- Sirfetchd
update pokedex set size_id = 4, weight_id = 2 where id = 874; -- Makuhita
update pokedex set size_id = 3, weight_id = 5 where id = 875; -- Hariyama
update pokedex set size_id = 4, weight_id = 4 where id = 876; -- Meditite
update pokedex set size_id = 4, weight_id = 4 where id = 877; -- Medicham
update pokedex set size_id = 4, weight_id = 4 where id = 883; -- Mienfoo
update pokedex set size_id = 4, weight_id = 4 where id = 884; -- Mienshao
update pokedex set size_id = 5, weight_id = 3 where id = 885; -- Pancham
update pokedex set size_id = 3, weight_id = 2 where id = 886; -- Pangoro
update pokedex set size_id = 5, weight_id = 4 where id = 872; -- Tyrogue
update pokedex set size_id = 4, weight_id = 4 where id = 870; -- Hitmonlee
update pokedex set size_id = 4, weight_id = 4 where id = 871; -- Hitmonchan
update pokedex set size_id = 4, weight_id = 4 where id = 873; -- Hitmontop
update pokedex set size_id = 3, weight_id = 4 where id = 894; -- Falinks
update pokedex set size_id = 4, weight_id = 4 where id = 887; -- Hawlucha
update pokedex set size_id = 4, weight_id = 4 where id = 881; -- Throh
update pokedex set size_id = 5, weight_id = 3 where id = 707; -- Cubone
update pokedex set size_id = 5, weight_id = 3 where id = 899; -- Noibat
update pokedex set size_id = 3, weight_id = 2 where id = 900; -- Noivern
update pokedex set size_id = 4, weight_id = 4 where id = 902; -- Bombirdier
update pokedex set size_id = 4, weight_id = 4 where id = 901; -- Cramorant
update pokedex set size_id = 4, weight_id = 4 where id = 903; -- Flamigo
update pokedex set size_id = 5, weight_id = 4 where id = 1040; -- Duskull
update pokedex set size_id = 3, weight_id = 4 where id = 1041; -- Dusclops
update pokedex set size_id = 3, weight_id = 2 where id = 1045; -- Dusknoir
update pokedex set size_id = 4, weight_id = 1 where id = 1055; -- Cursola
update pokedex set size_id = 5, weight_id = 1 where id = 1042; -- Drifloon
update pokedex set size_id = 3, weight_id = 4 where id = 1043; -- Drifblim
update pokedex set size_id = 5, weight_id = 4 where id = 1057; -- Greavard
update pokedex set size_id = 3, weight_id = 4 where id = 1058; -- Houndstone
update pokedex set size_id = 5, weight_id = 3 where id = 1048; -- Phantump
update pokedex set size_id = 4, weight_id = 2 where id = 1049; -- Trevenant
update pokedex set size_id = 4, weight_id = 2 where id = 1050; -- Sandygast
update pokedex set size_id = 3, weight_id = 5 where id = 1051; -- Palossand
update pokedex set size_id = 5, weight_id = 1 where id = 1038; -- Shuppet
update pokedex set size_id = 4, weight_id = 4 where id = 1039; -- Banette
update pokedex set size_id = 6, weight_id = 1 where id = 1053; -- Sinistea
update pokedex set size_id = 5, weight_id = 1 where id = 1054; -- Polteageist
update pokedex set size_id = 5, weight_id = 1 where id = 1046; -- Yamask
update pokedex set size_id = 3, weight_id = 2 where id = 1047; -- Cofagrigus
update pokedex set size_id = 2, weight_id = 5 where id = 1052; -- Dhelmise
update pokedex set size_id = 4, weight_id = 2 where id = 1044; -- Spiritomb
update pokedex set size_id = 5, weight_id = 3 where id = 1152; -- Bellsprout
update pokedex set size_id = 4, weight_id = 3 where id = 1153; -- Weepinbell
update pokedex set size_id = 4, weight_id = 4 where id = 1154; -- Victreebel
update pokedex set size_id = 5, weight_id = 1 where id = 1193; -- Bounsweet
update pokedex set size_id = 5, weight_id = 3 where id = 1194; -- Steenee
update pokedex set size_id = 4, weight_id = 4 where id = 1195; -- Tsareena
update pokedex set size_id = 6, weight_id = 1 where id = 1169; -- Budew
update pokedex set size_id = 5, weight_id = 1 where id = 1166; -- Roselia
update pokedex set size_id = 4, weight_id = 4 where id = 1170; -- Roserade
update pokedex set size_id = 5, weight_id = 3 where id = 1161; -- Seedot
update pokedex set size_id = 4, weight_id = 4 where id = 1162; -- Nuzleaf
update pokedex set size_id = 4, weight_id = 4 where id = 1163; -- Shiftry
update pokedex set size_id = 6, weight_id = 1 where id = 1199; -- Smoliv
update pokedex set size_id = 5, weight_id = 3 where id = 1200; -- Dolliv
update pokedex set size_id = 4, weight_id = 4 where id = 1201; -- Arboliva
update pokedex set size_id = 5, weight_id = 3 where id = 1149; -- Oddish
update pokedex set size_id = 5, weight_id = 3 where id = 1150; -- Gloom
update pokedex set size_id = 3, weight_id = 4 where id = 1151; -- Vileplume
update pokedex set size_id = 5, weight_id = 3 where id = 1158; -- Bellossom
update pokedex set size_id = 5, weight_id = 1 where id = 1202; -- Bramblin
update pokedex set size_id = 4, weight_id = 3 where id = 1203; -- Brambleghast
update pokedex set size_id = 5, weight_id = 4 where id = 1167; -- Cacnea
update pokedex set size_id = 4, weight_id = 2 where id = 1168; -- Cacturne
update pokedex set size_id = 5, weight_id = 3 where id = 1204; -- Capsakid
update pokedex set size_id = 4, weight_id = 4 where id = 1205; -- Scovillain
update pokedex set size_id = 5, weight_id = 1 where id = 1172; -- Cherrim
update pokedex set size_id = 5, weight_id = 3 where id = 1177; -- Cottonee
update pokedex set size_id = 5, weight_id = 3 where id = 1178; -- Whimsicott
update pokedex set size_id = 5, weight_id = 4 where id = 1184; -- Ferroseed
update pokedex set size_id = 4, weight_id = 2 where id = 1185; -- Ferrothorn
update pokedex set size_id = 5, weight_id = 1 where id = 1189; -- Fomantis
update pokedex set size_id = 4, weight_id = 4 where id = 1190; -- Lurantis
update pokedex set size_id = 6, weight_id = 1 where id = 1182; -- Foongus
update pokedex set size_id = 5, weight_id = 3 where id = 1183; -- Amoonguss
update pokedex set size_id = 5, weight_id = 1 where id = 1197; -- Gossifleur
update pokedex set size_id = 5, weight_id = 3 where id = 1198; -- Eldegoss
update pokedex set size_id = 6, weight_id = 1 where id = 1191; -- Morelull
update pokedex set size_id = 4, weight_id = 4 where id = 1192; -- Shiinotic
update pokedex set size_id = 5, weight_id = 4 where id = 1175; -- Pansage
update pokedex set size_id = 4, weight_id = 4 where id = 1176; -- Simisage
update pokedex set size_id = 6, weight_id = 1 where id = 1206; -- Poltchageist
update pokedex set size_id = 5, weight_id = 1 where id = 1207; -- Sinistcha
update pokedex set size_id = 5, weight_id = 3 where id = 1164; -- Shroomish
update pokedex set size_id = 4, weight_id = 4 where id = 1165; -- Breloom
update pokedex set size_id = 4, weight_id = 4 where id = 1187; -- Skiddo
update pokedex set size_id = 4, weight_id = 2 where id = 1188; -- Gogoat
update pokedex set size_id = 5, weight_id = 1 where id = 1159; -- Sunkern
update pokedex set size_id = 5, weight_id = 3 where id = 1160; -- Sunflora
update pokedex set size_id = 4, weight_id = 4 where id = 1157; -- Tangela
update pokedex set size_id = 3, weight_id = 2 where id = 1174; -- Tangrowth
update pokedex set size_id = 5, weight_id = 1 where id = 1155; -- Exeggcute
update pokedex set size_id = 3, weight_id = 2 where id = 1156; -- Exeggutor
update pokedex set size_id = 5, weight_id = 3 where id = 1179; -- Petilil
update pokedex set size_id = 4, weight_id = 4 where id = 1180; -- Lilligant
update pokedex set size_id = 4, weight_id = 4 where id = 1173; -- Carnivine
update pokedex set size_id = 5, weight_id = 4 where id = 719; -- Sandile
update pokedex set size_id = 4, weight_id = 4 where id = 720; -- Krokorok
update pokedex set size_id = 3, weight_id = 2 where id = 721; -- Krookodile
update pokedex set size_id = 4, weight_id = 4 where id = 711; -- Trapinch
update pokedex set size_id = 4, weight_id = 4 where id = 712; -- Vibrava
update pokedex set size_id = 3, weight_id = 2 where id = 713; -- Flygon
update pokedex set size_id = 5, weight_id = 3 where id = 793; -- Teddiursa
update pokedex set size_id = 3, weight_id = 2 where id = 794; -- Ursaring
update pokedex set size_id = 3, weight_id = 2 where id = 728; -- Ursaluna
update pokedex set size_id = 4, weight_id = 4 where id = 708; -- Marowak
update pokedex set size_id = 6, weight_id = 1 where id = 705; -- Diglett
update pokedex set size_id = 4, weight_id = 4 where id = 706; -- Dugtrio
update pokedex set size_id = 5, weight_id = 3 where id = 717; -- Drilbur
update pokedex set size_id = 4, weight_id = 4 where id = 718; -- Excadrill
update pokedex set size_id = 4, weight_id = 4 where id = 715; -- Hippopotas
update pokedex set size_id = 3, weight_id = 5 where id = 716; -- Hippowdon
update pokedex set size_id = 4, weight_id = 2 where id = 723; -- Mudbray
update pokedex set size_id = 3, weight_id = 5 where id = 724; -- Mudsdale
update pokedex set size_id = 5, weight_id = 4 where id = 709; -- Phanpy
update pokedex set size_id = 3, weight_id = 2 where id = 710; -- Donphan
update pokedex set size_id = 5, weight_id = 4 where id = 703; -- Sandshrew
update pokedex set size_id = 4, weight_id = 4 where id = 704; -- Sandslash
update pokedex set size_id = 4, weight_id = 3 where id = 725; -- Silicobra
update pokedex set size_id = 4, weight_id = 4 where id = 726; -- Sandaconda
update pokedex set size_id = 5, weight_id = 1 where id = 729; -- Toedscool
update pokedex set size_id = 3, weight_id = 4 where id = 730; -- Toedscruel
update pokedex set size_id = 3, weight_id = 4 where id = 727; -- Runerigus
update pokedex set size_id = 5, weight_id = 4 where id = 722; -- Stunfisk
update pokedex set size_id = 4, weight_id = 4 where id = 774; -- Wigglytuff
update pokedex set size_id = 5, weight_id = 3 where id = 832; -- Lillipup
update pokedex set size_id = 5, weight_id = 4 where id = 833; -- Herdier
update pokedex set size_id = 3, weight_id = 4 where id = 834; -- Stoutland
update pokedex set size_id = 5, weight_id = 1 where id = 767; -- Pidgey
update pokedex set size_id = 4, weight_id = 4 where id = 768; -- Pidgeotto
update pokedex set size_id = 3, weight_id = 4 where id = 769; -- Pidgeot
update pokedex set size_id = 5, weight_id = 1 where id = 835; -- Pidove
update pokedex set size_id = 5, weight_id = 4 where id = 836; -- Tranquill
update pokedex set size_id = 4, weight_id = 4 where id = 837; -- Unfezant
update pokedex set size_id = 5, weight_id = 1 where id = 846; -- Pikipek
update pokedex set size_id = 4, weight_id = 4 where id = 847; -- Trumbeak
update pokedex set size_id = 3, weight_id = 4 where id = 848; -- Toucannon
update pokedex set size_id = 4, weight_id = 4 where id = 784; -- Porygon
update pokedex set size_id = 4, weight_id = 4 where id = 795; -- Porygon2
update pokedex set size_id = 4, weight_id = 4 where id = 803; -- Slakoth
update pokedex set size_id = 4, weight_id = 4 where id = 804; -- Vigoroth
update pokedex set size_id = 3, weight_id = 2 where id = 805; -- Slaking
update pokedex set size_id = 5, weight_id = 1 where id = 815; -- Starly
update pokedex set size_id = 4, weight_id = 4 where id = 816; -- Staravia
update pokedex set size_id = 3, weight_id = 4 where id = 817; -- Staraptor
update pokedex set size_id = 5, weight_id = 4 where id = 806; -- Whismur
update pokedex set size_id = 4, weight_id = 4 where id = 807; -- Loudred
update pokedex set size_id = 3, weight_id = 2 where id = 808; -- Exploud
update pokedex set size_id = 5, weight_id = 4 where id = 790; -- Aipom
update pokedex set size_id = 4, weight_id = 4 where id = 820; -- Ambipom
update pokedex set size_id = 5, weight_id = 3 where id = 818; -- Bidoof
update pokedex set size_id = 4, weight_id = 4 where id = 819; -- Bibarel
update pokedex set size_id = 5, weight_id = 3 where id = 821; -- Buneary
update pokedex set size_id = 4, weight_id = 4 where id = 822; -- Lopunny
update pokedex set size_id = 5, weight_id = 3 where id = 843; -- Bunnelby
update pokedex set size_id = 4, weight_id = 4 where id = 844; -- Diggersby
update pokedex set size_id = 4, weight_id = 4 where id = 778; -- Doduo
update pokedex set size_id = 3, weight_id = 2 where id = 779; -- Dodrio
update pokedex set size_id = 4, weight_id = 4 where id = 792; -- Dunsparce
update pokedex set size_id = 4, weight_id = 4 where id = 791; -- Girafarig
update pokedex set size_id = 3, weight_id = 2 where id = 863; -- Farigiraf
update pokedex set size_id = 5, weight_id = 3 where id = 823; -- Glameow
update pokedex set size_id = 4, weight_id = 4 where id = 824; -- Purugly
update pokedex set size_id = 5, weight_id = 4 where id = 788; -- Hoothoot
update pokedex set size_id = 4, weight_id = 4 where id = 789; -- Noctowl
update pokedex set size_id = 5, weight_id = 4 where id = 861; -- Lechonk
update pokedex set size_id = 4, weight_id = 4 where id = 780; -- Lickitung
update pokedex set size_id = 3, weight_id = 2 where id = 827; -- Lickilicky
update pokedex set size_id = 5, weight_id = 3 where id = 775; -- Meowth
update pokedex set size_id = 4, weight_id = 4 where id = 776; -- Persian
update pokedex set size_id = 5, weight_id = 3 where id = 838; -- Minccino
update pokedex set size_id = 5, weight_id = 3 where id = 839; -- Cinccino
update pokedex set size_id = 4, weight_id = 2 where id = 826; -- Munchlax
update pokedex set size_id = 3, weight_id = 5 where id = 785; -- Snorlax
update pokedex set size_id = 5, weight_id = 3 where id = 830; -- Patrat
update pokedex set size_id = 4, weight_id = 4 where id = 831; -- Watchog
update pokedex set size_id = 5, weight_id = 3 where id = 770; -- Rattata
update pokedex set size_id = 4, weight_id = 4 where id = 771; -- Raticate
update pokedex set size_id = 5, weight_id = 3 where id = 841; -- Rufflet
update pokedex set size_id = 3, weight_id = 4 where id = 842; -- Braviary
update pokedex set size_id = 5, weight_id = 3 where id = 786; -- Sentret
update pokedex set size_id = 4, weight_id = 4 where id = 787; -- Furret
update pokedex set size_id = 5, weight_id = 3 where id = 809; -- Skitty
update pokedex set size_id = 4, weight_id = 4 where id = 810; -- Delcatty
update pokedex set size_id = 5, weight_id = 3 where id = 856; -- Skwovet
update pokedex set size_id = 4, weight_id = 3 where id = 857; -- Greedent
update pokedex set size_id = 5, weight_id = 1 where id = 772; -- Spearow
update pokedex set size_id = 4, weight_id = 4 where id = 773; -- Fearow
update pokedex set size_id = 4, weight_id = 2 where id = 796; -- Stantler
update pokedex set size_id = 3, weight_id = 2 where id = 860; -- Wyrdeer
update pokedex set size_id = 5, weight_id = 3 where id = 851; -- Stufful
update pokedex set size_id = 3, weight_id = 2 where id = 852; -- Bewear
update pokedex set size_id = 5, weight_id = 1 where id = 801; -- Taillow
update pokedex set size_id = 4, weight_id = 4 where id = 802; -- Swellow
update pokedex set size_id = 6, weight_id = 1 where id = 862; -- Tandemaus
update pokedex set size_id = 4, weight_id = 3 where id = 858; -- Wooloo
update pokedex set size_id = 4, weight_id = 4 where id = 859; -- Dubwool
update pokedex set size_id = 5, weight_id = 3 where id = 849; -- Yungoos
update pokedex set size_id = 4, weight_id = 4 where id = 850; -- Gumshoos
update pokedex set size_id = 5, weight_id = 3 where id = 799; -- Zigzagoon
update pokedex set size_id = 4, weight_id = 4 where id = 800; -- Linoone
update pokedex set size_id = 3, weight_id = 2 where id = 813; -- Castform
update pokedex set size_id = 5, weight_id = 1 where id = 825; -- Chatot
update pokedex set size_id = 5, weight_id = 3 where id = 783; -- Ditto
update pokedex set size_id = 2, weight_id = 5 where id = 855; -- Drampa
update pokedex set size_id = 5, weight_id = 4 where id = 845; -- Furfrou
update pokedex set size_id = 3, weight_id = 2 where id = 781; -- Kangaskhan
update pokedex set size_id = 4, weight_id = 4 where id = 814; -- Kecleon
update pokedex set size_id = 5, weight_id = 4 where id = 854; -- Komala
update pokedex set size_id = 4, weight_id = 2 where id = 782; -- Tauros
update pokedex set size_id = 4, weight_id = 4 where id = 797; -- Smeargle
update pokedex set size_id = 4, weight_id = 3 where id = 811; -- Spinda
update pokedex set size_id = 4, weight_id = 4 where id = 812; -- Zangoose
update pokedex set size_id = 4, weight_id = 4 where id = 906; -- Nidorina
update pokedex set size_id = 3, weight_id = 4 where id = 907; -- Nidoqueen
update pokedex set size_id = 4, weight_id = 4 where id = 908; -- Nidorino
update pokedex set size_id = 3, weight_id = 4 where id = 909; -- Nidoking
update pokedex set size_id = 4, weight_id = 4 where id = 921; -- Croagunk
update pokedex set size_id = 4, weight_id = 4 where id = 922; -- Toxicroak
update pokedex set size_id = 4, weight_id = 3 where id = 904; -- Ekans
update pokedex set size_id = 3, weight_id = 4 where id = 905; -- Arbok
update pokedex set size_id = 4, weight_id = 4 where id = 910; -- Grimer
update pokedex set size_id = 3, weight_id = 4 where id = 911; -- Muk
update pokedex set size_id = 5, weight_id = 4 where id = 914; -- Gulpin
update pokedex set size_id = 3, weight_id = 2 where id = 915; -- Swalot
update pokedex set size_id = 5, weight_id = 3 where id = 927; -- Mareanie
update pokedex set size_id = 4, weight_id = 4 where id = 928; -- Toxapex
update pokedex set size_id = 6, weight_id = 1 where id = 932; -- Shroodle
update pokedex set size_id = 4, weight_id = 4 where id = 933; -- Grafaiai
update pokedex set size_id = 5, weight_id = 3 where id = 919; -- Skorupi
update pokedex set size_id = 3, weight_id = 4 where id = 920; -- Drapion
update pokedex set size_id = 5, weight_id = 3 where id = 925; -- Skrelp
update pokedex set size_id = 3, weight_id = 2 where id = 926; -- Dragalge
update pokedex set size_id = 5, weight_id = 4 where id = 917; -- Stunky
update pokedex set size_id = 4, weight_id = 4 where id = 918; -- Skuntank
update pokedex set size_id = 4, weight_id = 4 where id = 923; -- Trubbish
update pokedex set size_id = 3, weight_id = 2 where id = 924; -- Garbodor
update pokedex set size_id = 3, weight_id = 5 where id = 934; -- Clodsire
update pokedex set size_id = 4, weight_id = 1 where id = 912; -- Koffing
update pokedex set size_id = 4, weight_id = 3 where id = 913; -- Weezing
update pokedex set size_id = 4, weight_id = 4 where id = 1103; -- Slowking
update pokedex set size_id = 3, weight_id = 4 where id = 916; -- Seviper
update pokedex set size_id = 5, weight_id = 4 where id = 1209; -- Abra
update pokedex set size_id = 4, weight_id = 4 where id = 1210; -- Kadabra
update pokedex set size_id = 4, weight_id = 4 where id = 1211; -- Alakazam
update pokedex set size_id = 5, weight_id = 3 where id = 1247; -- Hatenna
update pokedex set size_id = 5, weight_id = 3 where id = 1248; -- Hattrem
update pokedex set size_id = 4, weight_id = 3 where id = 1249; -- Hatterene
update pokedex set size_id = 5, weight_id = 1 where id = 1235; -- Solosis
update pokedex set size_id = 5, weight_id = 3 where id = 1236; -- Duosion
update pokedex set size_id = 4, weight_id = 4 where id = 1237; -- Reuniclus
update pokedex set size_id = 6, weight_id = 1 where id = 1226; -- Chingling
update pokedex set size_id = 5, weight_id = 1 where id = 1224; -- Chimecho
update pokedex set size_id = 4, weight_id = 4 where id = 1212; -- Drowzee
update pokedex set size_id = 4, weight_id = 2 where id = 1213; -- Hypno
update pokedex set size_id = 5, weight_id = 3 where id = 1238; -- Elgyem
update pokedex set size_id = 4, weight_id = 4 where id = 1239; -- Beheeyem
update pokedex set size_id = 6, weight_id = 1 where id = 1251; -- Flittle
update pokedex set size_id = 3, weight_id = 2 where id = 1252; -- Espathra
update pokedex set size_id = 6, weight_id = 1 where id = 1216; -- Natu
update pokedex set size_id = 4, weight_id = 4 where id = 1217; -- Xatu
update pokedex set size_id = 5, weight_id = 4 where id = 1222; -- Spoink
update pokedex set size_id = 4, weight_id = 2 where id = 1223; -- Grumpig
update pokedex set size_id = 5, weight_id = 1 where id = 1232; -- Woobat
update pokedex set size_id = 4, weight_id = 4 where id = 1233; -- Swoobat
update pokedex set size_id = 5, weight_id = 4 where id = 1225; -- Wynaut
update pokedex set size_id = 4, weight_id = 4 where id = 1219; -- Wobbuffet
update pokedex set size_id = 5, weight_id = 3 where id = 1240; -- Espurr
update pokedex set size_id = 4, weight_id = 4 where id = 1234; -- Sigilyph
update pokedex set size_id = 5, weight_id = 3 where id = 1218; -- Unown
update pokedex set size_id = 5, weight_id = 2 where id = 944; -- Larvitar
update pokedex set size_id = 4, weight_id = 2 where id = 945; -- Pupitar
update pokedex set size_id = 3, weight_id = 5 where id = 946; -- Tyranitar
update pokedex set size_id = 5, weight_id = 4 where id = 970; -- Nacli
update pokedex set size_id = 4, weight_id = 2 where id = 971; -- Naclstack
update pokedex set size_id = 3, weight_id = 5 where id = 972; -- Garganacl
update pokedex set size_id = 5, weight_id = 4 where id = 950; -- Anorith
update pokedex set size_id = 3, weight_id = 2 where id = 951; -- Armaldo
update pokedex set size_id = 5, weight_id = 3 where id = 958; -- Archen
update pokedex set size_id = 5, weight_id = 4 where id = 961; -- Binacle
update pokedex set size_id = 3, weight_id = 2 where id = 962; -- Barbaracle
update pokedex set size_id = 4, weight_id = 4 where id = 953; -- Cranidos
update pokedex set size_id = 3, weight_id = 2 where id = 954; -- Rampardos
update pokedex set size_id = 5, weight_id = 3 where id = 974; -- Glimmet
update pokedex set size_id = 4, weight_id = 4 where id = 975; -- Glimmora
update pokedex set size_id = 5, weight_id = 4 where id = 941; -- Kabuto
update pokedex set size_id = 4, weight_id = 4 where id = 942; -- Kabutops
update pokedex set size_id = 5, weight_id = 4 where id = 948; -- Lileep
update pokedex set size_id = 3, weight_id = 4 where id = 949; -- Cradily
update pokedex set size_id = 4, weight_id = 2 where id = 947; -- Nosepass
update pokedex set size_id = 3, weight_id = 5 where id = 957; -- Probopass
update pokedex set size_id = 5, weight_id = 3 where id = 939; -- Omanyte
update pokedex set size_id = 4, weight_id = 4 where id = 940; -- Omastar
update pokedex set size_id = 5, weight_id = 4 where id = 955; -- Shieldon
update pokedex set size_id = 3, weight_id = 2 where id = 956; -- Bastiodon
update pokedex set size_id = 5, weight_id = 4 where id = 963; -- Tyrunt
update pokedex set size_id = 2, weight_id = 5 where id = 964; -- Tyrantrum
update pokedex set size_id = 5, weight_id = 3 where id = 966; -- Rockruff
update pokedex set size_id = 2, weight_id = 4 where id = 943; -- Aerodactyl
update pokedex set size_id = 5, weight_id = 3 where id = 973; -- Klawf
update pokedex set size_id = 2, weight_id = 5 where id = 969; -- Stonjourner
update pokedex set size_id = 5, weight_id = 2 where id = 1062; -- Beldum
update pokedex set size_id = 4, weight_id = 5 where id = 1063; -- Metang
update pokedex set size_id = 3, weight_id = 5 where id = 1064; -- Metagross
update pokedex set size_id = 5, weight_id = 1 where id = 1072; -- Honedge
update pokedex set size_id = 4, weight_id = 3 where id = 1073; -- Doublade
update pokedex set size_id = 5, weight_id = 4 where id = 1068; -- Klink
update pokedex set size_id = 4, weight_id = 4 where id = 1069; -- Klang
update pokedex set size_id = 3, weight_id = 2 where id = 1070; -- Klinklang
update pokedex set size_id = 4, weight_id = 2 where id = 1080; -- Cufant
update pokedex set size_id = 2, weight_id = 5 where id = 1081; -- Copperajah
update pokedex set size_id = 4, weight_id = 4 where id = 1082; -- Duraludon
update pokedex set size_id = 3, weight_id = 2 where id = 1087; -- Archaludon
update pokedex set size_id = 4, weight_id = 4 where id = 1086; -- Gholdengo
update pokedex set size_id = 4, weight_id = 4 where id = 1079; -- Perrserker
update pokedex set size_id = 4, weight_id = 4 where id = 1083; -- Varoom
update pokedex set size_id = 3, weight_id = 2 where id = 1084; -- Revavroom
update pokedex set size_id = 6, weight_id = 3 where id = 1074; -- Klefki
update pokedex set size_id = 5, weight_id = 4 where id = 1061; -- Mawile
update pokedex set size_id = 3, weight_id = 5 where id = 1085; -- Orthworm
update pokedex set size_id = 3, weight_id = 4 where id = 1060; -- Skarmory
update pokedex set size_id = 5, weight_id = 3 where id = 1140; -- Chewtle
update pokedex set size_id = 4, weight_id = 2 where id = 1141; -- Drednaw
update pokedex set size_id = 5, weight_id = 3 where id = 1134; -- Clauncher
update pokedex set size_id = 4, weight_id = 4 where id = 1135; -- Clawitzer
update pokedex set size_id = 5, weight_id = 4 where id = 1114; -- Corphish
update pokedex set size_id = 4, weight_id = 4 where id = 1115; -- Crawdaunt
update pokedex set size_id = 5, weight_id = 3 where id = 1136; -- Dewpider
update pokedex set size_id = 3, weight_id = 4 where id = 1137; -- Araquanid
update pokedex set size_id = 5, weight_id = 3 where id = 1131; -- Ducklett
update pokedex set size_id = 4, weight_id = 4 where id = 1132; -- Swanna
update pokedex set size_id = 5, weight_id = 3 where id = 1116; -- Feebas
update pokedex set size_id = 3, weight_id = 2 where id = 1117; -- Milotic
update pokedex set size_id = 4, weight_id = 4 where id = 1146; -- Finizen
update pokedex set size_id = 5, weight_id = 4 where id = 1099; -- Goldeen
update pokedex set size_id = 4, weight_id = 4 where id = 1100; -- Seaking
update pokedex set size_id = 5, weight_id = 3 where id = 1097; -- Krabby
update pokedex set size_id = 4, weight_id = 4 where id = 1098; -- Kingler
update pokedex set size_id = 4, weight_id = 4 where id = 1125; -- Mantyke
update pokedex set size_id = 3, weight_id = 5 where id = 1108; -- Mantine
update pokedex set size_id = 5, weight_id = 4 where id = 1129; -- Panpour
update pokedex set size_id = 4, weight_id = 4 where id = 1130; -- Simipour
update pokedex set size_id = 4, weight_id = 4 where id = 1089; -- Psyduck
update pokedex set size_id = 4, weight_id = 2 where id = 1090; -- Golduck
update pokedex set size_id = 5, weight_id = 4 where id = 1106; -- Remoraid
update pokedex set size_id = 4, weight_id = 4 where id = 1107; -- Octillery
update pokedex set size_id = 5, weight_id = 3 where id = 1095; -- Shellder
update pokedex set size_id = 4, weight_id = 2 where id = 1096; -- Cloyster
update pokedex set size_id = 5, weight_id = 3 where id = 1123; -- Shellos
update pokedex set size_id = 4, weight_id = 4 where id = 1124; -- Gastrodon
update pokedex set size_id = 4, weight_id = 4 where id = 1101; -- Staryu
update pokedex set size_id = 4, weight_id = 2 where id = 1102; -- Starmie
update pokedex set size_id = 4, weight_id = 4 where id = 1091; -- Tentacool
update pokedex set size_id = 3, weight_id = 4 where id = 1092; -- Tentacruel
update pokedex set size_id = 3, weight_id = 2 where id = 1112; -- Wailmer
update pokedex set size_id = 1, weight_id = 5 where id = 1113; -- Wailord
update pokedex set size_id = 4, weight_id = 1 where id = 1144; -- Wiglett
update pokedex set size_id = 4, weight_id = 3 where id = 1145; -- Wugtrio
update pokedex set size_id = 5, weight_id = 3 where id = 1110; -- Wingull
update pokedex set size_id = 4, weight_id = 4 where id = 1111; -- Pelipper
update pokedex set size_id = 5, weight_id = 4 where id = 1118; -- Clamperl
update pokedex set size_id = 4, weight_id = 4 where id = 1119; -- Huntail
update pokedex set size_id = 4, weight_id = 4 where id = 1120; -- Gorebyss
update pokedex set size_id = 4, weight_id = 4 where id = 1093; -- Slowpoke
update pokedex set size_id = 4, weight_id = 2 where id = 1094; -- Slowbro
update pokedex set size_id = 4, weight_id = 4 where id = 1133; -- Alomomola
update pokedex set size_id = 3, weight_id = 2 where id = 1142; -- Dracovish
update pokedex set size_id = 5, weight_id = 4 where id = 1139; -- Bruxish
update pokedex set size_id = 5, weight_id = 3 where id = 1105; -- Corsola
update pokedex set size_id = 2, weight_id = 5 where id = 1148; -- Dondozo
update pokedex set size_id = 5, weight_id = 3 where id = 1138; -- Pyukumuku
update pokedex set size_id = 5, weight_id = 3 where id = 1104; -- Qwilfish
update pokedex set size_id = 3, weight_id = 2 where id = 1147; -- Veluza
