-- Seeds core reference data extracted from the PTA3 Player's Handbook, and restructures
-- `passives` to support Stat Passives (numeric stat modifiers, max 3 active, 1 per category)
-- vs Ability Passives (unstructured effects). "Pokemon Skills" from the handbook are folded
-- into passives as ability-type passives with context = 'out_of_combat', per clarification
-- that they work like ability passives but apply outside of combat.

alter table passives
  add column passive_type text not null default 'ability' check (passive_type in ('stat', 'ability')),
  add column category text check (category in ('attack', 'defense', 'special_attack', 'special_defense', 'speed', 'mix', 'critical_hit')),
  add column context text check (context in ('combat', 'out_of_combat'));

create table passives_stats (
  passive_id int not null references passives(id) on delete cascade,
  stat_id int not null references stats(id) on delete cascade,
  modifier int not null,
  primary key (passive_id, stat_id)
);

create index on passives_stats (stat_id);

-- Active data: which passives a specific owned Pokemon currently has (mutable, mirrors
-- pokemon_moves/pokemon_afflictions). The max-3 / one-per-category stacking rule is
-- application logic, not enforced here (same approach as other business rules so far).
create table pokemon_passives (
  pokemon_id uuid not null references pokemon(id) on delete cascade,
  passive_id int not null references passives(id) on delete cascade,
  primary key (pokemon_id, passive_id)
);

create index on pokemon_passives (passive_id);

alter table passives_stats enable row level security;
create policy "Public read access" on passives_stats for select using (true);

alter table pokemon_passives enable row level security;
create policy "Owner manages pokemon_passives" on pokemon_passives
  for all using (
    exists (
      select 1 from trainers_pokemon tp
      join trainers t on t.id = tp.trainer_id
      where tp.pokemon_id = pokemon_passives.pokemon_id and t.user_id = auth.uid()
    )
  ) with check (
    exists (
      select 1 from trainers_pokemon tp
      join trainers t on t.id = tp.trainer_id
      where tp.pokemon_id = pokemon_passives.pokemon_id and t.user_id = auth.uid()
    )
  );

insert into stats (name, abbreviation) values
  ('HP', 'HP'),
  ('Attack', 'Atk'),
  ('Defense', 'Def'),
  ('Special Attack', 'SpAtk'),
  ('Special Defense', 'SpDef'),
  ('Speed', 'Spd')
on conflict (name) do nothing;

insert into types (name) values
  ('Bug'),
  ('Dark'),
  ('Dragon'),
  ('Electric'),
  ('Fairy'),
  ('Fighting'),
  ('Fire'),
  ('Flying'),
  ('Ghost'),
  ('Grass'),
  ('Ground'),
  ('Ice'),
  ('Normal'),
  ('Poison'),
  ('Psychic'),
  ('Rock'),
  ('Steel'),
  ('Water')
on conflict (name) do nothing;

insert into natures (name, increased_stat_id, decreased_stat_id) values
  ('Lonely', (select id from stats where name = 'Attack'), (select id from stats where name = 'Defense')),
  ('Brave', (select id from stats where name = 'Attack'), (select id from stats where name = 'Speed')),
  ('Adamant', (select id from stats where name = 'Attack'), (select id from stats where name = 'Special Attack')),
  ('Naughty', (select id from stats where name = 'Attack'), (select id from stats where name = 'Special Defense')),
  ('Bold', (select id from stats where name = 'Defense'), (select id from stats where name = 'Attack')),
  ('Relaxed', (select id from stats where name = 'Defense'), (select id from stats where name = 'Speed')),
  ('Impish', (select id from stats where name = 'Defense'), (select id from stats where name = 'Special Attack')),
  ('Lax', (select id from stats where name = 'Defense'), (select id from stats where name = 'Special Defense')),
  ('Timid', (select id from stats where name = 'Speed'), (select id from stats where name = 'Attack')),
  ('Hasty', (select id from stats where name = 'Speed'), (select id from stats where name = 'Defense')),
  ('Jolly', (select id from stats where name = 'Speed'), (select id from stats where name = 'Special Attack')),
  ('Naive', (select id from stats where name = 'Speed'), (select id from stats where name = 'Special Defense')),
  ('Modest', (select id from stats where name = 'Special Attack'), (select id from stats where name = 'Attack')),
  ('Mild', (select id from stats where name = 'Special Attack'), (select id from stats where name = 'Defense')),
  ('Quiet', (select id from stats where name = 'Special Attack'), (select id from stats where name = 'Speed')),
  ('Rash', (select id from stats where name = 'Special Attack'), (select id from stats where name = 'Special Defense')),
  ('Calm', (select id from stats where name = 'Special Defense'), (select id from stats where name = 'Attack')),
  ('Gentle', (select id from stats where name = 'Special Defense'), (select id from stats where name = 'Defense')),
  ('Sassy', (select id from stats where name = 'Special Defense'), (select id from stats where name = 'Speed')),
  ('Careful', (select id from stats where name = 'Special Defense'), (select id from stats where name = 'Special Attack'))
on conflict (name) do nothing;

insert into loyalties (name, description) values
  ('0', 'Pokemon at loyalty 0 are constantly trying to escape their trainers. If they aren''t trying to actively flee, they''re ignoring any comment from their trainers, or even trying to attack their own trainers. Loyalty 0 is earned, you have to be really awful to your Pokemon for them to be here. Pokemon who are captured while unconscious always start here.'),
  ('1', 'Pokemon at loyalty 1 do not trust their trainers, but are not outwardly hostile towards them. Pokemon here might occasionally ignore their trainer''s commands, choosing to try something else during combat. Many newly captured Pokemon who believe their trainers are unworthy of their strength will be at loyalty 1.'),
  ('2', 'Loyalty 2 is marked by obedient Pokemon who are not really close to you. Most loyalty 2 Pokemon like their trainers but may see their relationship mostly as a means to an end. Their obedience and performance in battle gets them food and a safe place to rest. Most hatched Pokemon start at loyalty 2 once they imprint onto you.'),
  ('3', 'In general, loyalty 3 is a great place for your Pokemon to be. Pokemon at loyalty 3 obey commands in battle and perform the best they can to protect their friends and allies. They value their trainers as much as their trainers value them.'),
  ('4', 'Loyalty 4 often represents the closest relationship that a trainer might have. Most often, trainers will have Pokemon with loyalty 4 be their first Pokemon, their Pokemon who is always out of their Poke Ball, or maybe a starter that grew particularly close to their trainer.'),
  ('5', 'A trainer might spend their whole life with loving partnerships with their Pokemon and never have a Pokemon with loyalty 5. Pokemon with loyalty 5 have perfect understandings of their trainer''s needs and desires, and are often proactive, almost acting without command.')
on conflict (name) do nothing;

insert into habitats (name, description) values
  ('Beach', 'Rocky and sandy beaches play home to many semiaquatic Pokemon that are content only spending some of their time in the sea. The intertidal zone also supports rock pools where some hardier Water-types make their homes.'),
  ('Desert', 'Sandy, arid deserts support many Ground-type Pokemon that can burrow away from the sun''s heat. Resilient Steel- and Ground-types stand out, though Dark-, Dragon-, and even Flying-types appear as well.'),
  ('Forest', 'Temperate, broadleaf forests with mild, seasonal weather and healthy tree growth play home to many common Pokemon, with Grass-, Bug-, Flying-, and Normal-types the most abundant.'),
  ('Freshwater', 'Ponds, lakes, streams, and rivers, on their shores or in the waters themselves. Water-types are abundant, with Bug-types also common around ponds.'),
  ('Grasslands', 'Covers woodlands, fields, meadows, savannas, plains, and prairies. Fire- and Electric-types can start brushfires, Poison- and Normal-types are common in tall grass, and Bug-, Dark-, Ghost-, and Fairy-types may appear in woodlands at night.'),
  ('Jungle', 'Tropical jungles are warm and humid year-round with frequent rainfall and dense vegetation. Grass- and Bug-types thrive in these prolific habitats.'),
  ('Mountain', 'The exposed earth on mountain ranges, the caves underneath, and volcanic mountains. Rock- and Steel-types favor open mountainsides, Fighting-types train in the quiet remoteness, Ground-, Rock-, and Steel-types dwell underground, and Fire-types thrive near volcanic heat.'),
  ('Ocean', 'The open ocean, continental shelf, tropical seas and coral reefs, and the deep abyss. Marine Water-types of all kinds are found here, particularly sensitive to temperature, salinity, and cleanliness.'),
  ('Polar', 'The top of frozen mountains, massive glaciers, icy caves, and the polar seas. Primarily Ice-types, adapted to withstand freezing temperatures and scarce food.'),
  ('Tundra', 'Characterized by permafrost supporting only grasses, mosses, and lichens, plus boreal forests of evergreen trees. Ice-types are most common, with heartier Normal-types sometimes present.'),
  ('Urban', 'Cities and other areas defined by human habitation. Normal-, Psychic-, Fighting-, and Ghost-types often coexist with people, Poison-types thrive on waste, and Electric-types congregate around electrical activity.'),
  ('Wetlands', 'Swamps, bogs, and marshes are rich terrestrial habitats. Grass-, Bug-, Water-, and Poison-types take advantage of the acidic, oxygen-poor soils.')
on conflict (name) do nothing;

insert into egg_groups (name) values
  ('Amorphous'),
  ('Bug'),
  ('Dragon'),
  ('Fairy'),
  ('Field'),
  ('Flying'),
  ('Grass'),
  ('Human-Like'),
  ('Mineral'),
  ('Monster'),
  ('Water 1'),
  ('Water 2'),
  ('Water 3'),
  ('Ditto')
on conflict (name) do nothing;

insert into diets (name, description) values
  ('Carnivore', 'Primarily feeds on other Pokemon.'),
  ('Herbivore', 'Needs leafy food, vegetables, nuts and fruits to survive.'),
  ('Omnivore', 'Can eat plants or other Pokemon.'),
  ('Phototroph', 'Can photosynthesize its own food and energy.'),
  ('Terravore', 'Feeds on the minerals found in rock and dirt.'),
  ('Nullivore', 'Does not need to eat anything to sustain itself.'),
  ('Saprophyte', 'Feeds on decaying matter or minerals off the ground.'),
  ('Ergovore', 'Feeds on electricity and other energy.'),
  ('Glacievore', 'Survives by consuming ice and water.'),
  ('Pollutivore', 'Feeds on pollution of any kind.'),
  ('Psiotroph', 'Sustains itself off the thoughts and life force of others.')
on conflict (name) do nothing;

insert into afflictions (name, description) values
  ('Frozen', 'Immobilized by frost, unable to move or take an action. Recovers by rolling at least 18 on a 1d20 saving throw, or automatically after ten minutes. Ice-type Pokemon are immune.'),
  ('Asleep', 'Unable to wake and move. May attempt to wake on your turn with a 1d20 saving throw (starts at 16, decreasing by 2 each turn to a minimum of 6). Cured automatically after one minute.'),
  ('Burned', 'Lose 1d10 HP upon taking an action, and have -2 Attack. Cured at 0 HP or after one minute without attacking or moving. Fire-type Pokemon are immune.'),
  ('Confused', 'Attempting an action requires a 1d20 saving throw (11 or higher to act normally, cured on 16+ or after two minutes). A failed roll deals 1d12 HP of self-harm.'),
  ('Cursed', 'Lose 1/6th of max HP after taking an action. Cured at 0 HP. Only Pokemon can be cursed.'),
  ('Stunned', 'Cannot take a turn. Cured automatically on the following turn.'),
  ('Infatuated', 'Cannot attack the object of infatuation unless a 1d20 saving throw of 13+ is rolled. Cured on a roll of 19+ or after two minutes. Only Pokemon may be infatuated.'),
  ('Paralyzed', 'Have -2 Speed, and attempting an action requires a 1d20 saving throw (starts at 6, increasing by 2 each turn to a maximum of 16). Cured automatically after five minutes.'),
  ('Poisoned', 'Lose 1d10 HP upon taking an action, and have -2 Special Attack. Cured at 0 HP or after one minute without attacking or moving. Poison- and Steel-type Pokemon are immune.'),
  ('Toxified', 'Lose HP upon taking an action (1d8, then 1d12, 1d20, 2d20, 3d20, and so on), and have -2 Special Attack. Cured at 0 HP or after one minute without attacking or moving. Poison- and Steel-type Pokemon are immune.')
on conflict (name) do nothing;

insert into afflictions_stats (affliction_id, stat_id, modifier) values
  ((select id from afflictions where name = 'Burned'), (select id from stats where name = 'Attack'), -2),
  ((select id from afflictions where name = 'Paralyzed'), (select id from stats where name = 'Speed'), -2),
  ((select id from afflictions where name = 'Poisoned'), (select id from stats where name = 'Special Attack'), -2),
  ((select id from afflictions where name = 'Toxified'), (select id from stats where name = 'Special Attack'), -2)
on conflict (affliction_id, stat_id) do nothing;

insert into passives (name, description, passive_type, category) values
  ('Gorilla Tactics', '+1 Attack', 'stat', 'attack'),
  ('Howl', '+1 Attack', 'stat', 'attack'),
  ('Leer', '+1 Attack', 'stat', 'attack'),
  ('Meditate', '+1 Attack', 'stat', 'attack'),
  ('Moxie', '+1 Attack', 'stat', 'attack'),
  ('Sharpen', '+1 Attack', 'stat', 'attack'),
  ('Tail Whip', '+1 Attack', 'stat', 'attack'),
  ('Hone Claws', '+2 Attack', 'stat', 'attack'),
  ('Screech', '+2 Attack', 'stat', 'attack'),
  ('Swords Dance', '+2 Attack', 'stat', 'attack'),
  ('Huge Power', '+6 Attack', 'stat', 'attack'),
  ('Pure Power', '+6 Attack', 'stat', 'attack'),
  ('Baby-Doll Eyes', '+1 Defense', 'stat', 'defense'),
  ('Charm', '+1 Defense', 'stat', 'defense'),
  ('Defense Curl', '+1 Defense', 'stat', 'defense'),
  ('Growl', '+1 Defense', 'stat', 'defense'),
  ('Harden', '+1 Defense', 'stat', 'defense'),
  ('Intimidate', '+1 Defense', 'stat', 'defense'),
  ('Play Nice', '+1 Defense', 'stat', 'defense'),
  ('Withdraw', '+1 Defense', 'stat', 'defense'),
  ('Acid Armor', '+2 Defense', 'stat', 'defense'),
  ('Barrier', '+2 Defense', 'stat', 'defense'),
  ('Feather Dance', '+2 Defense', 'stat', 'defense'),
  ('Iron Defense', '+2 Defense', 'stat', 'defense'),
  ('Stamina', '+2 Defense', 'stat', 'defense'),
  ('Cotton Guard', '+3 Defense', 'stat', 'defense'),
  ('Shelter', '+3 Defense', 'stat', 'defense'),
  ('Metal Sound', '+1 Special Attack', 'stat', 'special_attack'),
  ('Nasty Plot', '+1 Special Attack', 'stat', 'special_attack'),
  ('Fake Tears', '+2 Special Attack', 'stat', 'special_attack'),
  ('Tail Glow', '+3 Special Attack', 'stat', 'special_attack'),
  ('Confide', '+1 Special Defense', 'stat', 'special_defense'),
  ('Amnesia', '+2 Special Defense', 'stat', 'special_defense'),
  ('Captivate', '+2 Special Defense', 'stat', 'special_defense'),
  ('Eerie Impulse', '+2 Special Defense', 'stat', 'special_defense'),
  ('Gooey', '+1 Speed', 'stat', 'speed'),
  ('Run Away', '+1 Speed', 'stat', 'speed'),
  ('Tangling Hair', '+1 Speed', 'stat', 'speed'),
  ('Agility', '+2 Speed', 'stat', 'speed'),
  ('Autotomize', '+2 Speed', 'stat', 'speed'),
  ('Cotton Spore', '+2 Speed', 'stat', 'speed'),
  ('Rock Polish', '+2 Speed', 'stat', 'speed'),
  ('Scary Face', '+2 Speed', 'stat', 'speed'),
  ('Speed Boost', '+2 Speed', 'stat', 'speed'),
  ('String Shot', '+2 Speed', 'stat', 'speed'),
  ('Tailwind', '+2 Speed', 'stat', 'speed'),
  ('Bulk Up', '+1 Attack, +1 Defense', 'stat', 'mix'),
  ('Calm Mind', '+1 Special Attack, +1 Special Defense', 'stat', 'mix'),
  ('Coil', '+2 Attack, +1 Defense', 'stat', 'mix'),
  ('Cosmic Power', '+1 Defense, +1 Special Defense', 'stat', 'mix'),
  ('Dragon Dance', '+1 Attack, +1 Speed', 'stat', 'mix'),
  ('Growth', '+1 Attack, +1 Special Attack', 'stat', 'mix'),
  ('Majesty’s Order', '+1 Attack, +1 Special Attack, +1 Defense, +1 Special Defense (Vespiquen only)', 'stat', 'mix'),
  ('Quiver Dance', '+1 Special Attack, +1 Special Defense, +1 Speed', 'stat', 'mix'),
  ('Rototiller', '+1 Attack, +1 Special Attack', 'stat', 'mix'),
  ('Shift Gear', '+1 Attack, +2 Speed', 'stat', 'mix'),
  ('Tearful Look', '+1 Defense, +1 Special Defense', 'stat', 'mix'),
  ('Tickle', '+1 Attack, +1 Defense', 'stat', 'mix'),
  ('Work Up', '+1 Attack, +1 Special Attack', 'stat', 'mix'),
  ('Focus Energy', 'Attacks are critical hits on natural 18-20', 'stat', 'critical_hit'),
  ('Super Luck', 'Attacks are critical hits on natural 18-20', 'stat', 'critical_hit')
on conflict (name) do nothing;

insert into passives_stats (passive_id, stat_id, modifier) values
  ((select id from passives where name = 'Gorilla Tactics'), (select id from stats where name = 'Attack'), 1),
  ((select id from passives where name = 'Howl'), (select id from stats where name = 'Attack'), 1),
  ((select id from passives where name = 'Leer'), (select id from stats where name = 'Attack'), 1),
  ((select id from passives where name = 'Meditate'), (select id from stats where name = 'Attack'), 1),
  ((select id from passives where name = 'Moxie'), (select id from stats where name = 'Attack'), 1),
  ((select id from passives where name = 'Sharpen'), (select id from stats where name = 'Attack'), 1),
  ((select id from passives where name = 'Tail Whip'), (select id from stats where name = 'Attack'), 1),
  ((select id from passives where name = 'Hone Claws'), (select id from stats where name = 'Attack'), 2),
  ((select id from passives where name = 'Screech'), (select id from stats where name = 'Attack'), 2),
  ((select id from passives where name = 'Swords Dance'), (select id from stats where name = 'Attack'), 2),
  ((select id from passives where name = 'Huge Power'), (select id from stats where name = 'Attack'), 6),
  ((select id from passives where name = 'Pure Power'), (select id from stats where name = 'Attack'), 6),
  ((select id from passives where name = 'Baby-Doll Eyes'), (select id from stats where name = 'Defense'), 1),
  ((select id from passives where name = 'Charm'), (select id from stats where name = 'Defense'), 1),
  ((select id from passives where name = 'Defense Curl'), (select id from stats where name = 'Defense'), 1),
  ((select id from passives where name = 'Growl'), (select id from stats where name = 'Defense'), 1),
  ((select id from passives where name = 'Harden'), (select id from stats where name = 'Defense'), 1),
  ((select id from passives where name = 'Intimidate'), (select id from stats where name = 'Defense'), 1),
  ((select id from passives where name = 'Play Nice'), (select id from stats where name = 'Defense'), 1),
  ((select id from passives where name = 'Withdraw'), (select id from stats where name = 'Defense'), 1),
  ((select id from passives where name = 'Acid Armor'), (select id from stats where name = 'Defense'), 2),
  ((select id from passives where name = 'Barrier'), (select id from stats where name = 'Defense'), 2),
  ((select id from passives where name = 'Feather Dance'), (select id from stats where name = 'Defense'), 2),
  ((select id from passives where name = 'Iron Defense'), (select id from stats where name = 'Defense'), 2),
  ((select id from passives where name = 'Stamina'), (select id from stats where name = 'Defense'), 2),
  ((select id from passives where name = 'Cotton Guard'), (select id from stats where name = 'Defense'), 3),
  ((select id from passives where name = 'Shelter'), (select id from stats where name = 'Defense'), 3),
  ((select id from passives where name = 'Metal Sound'), (select id from stats where name = 'Special Attack'), 1),
  ((select id from passives where name = 'Nasty Plot'), (select id from stats where name = 'Special Attack'), 1),
  ((select id from passives where name = 'Fake Tears'), (select id from stats where name = 'Special Attack'), 2),
  ((select id from passives where name = 'Tail Glow'), (select id from stats where name = 'Special Attack'), 3),
  ((select id from passives where name = 'Confide'), (select id from stats where name = 'Special Defense'), 1),
  ((select id from passives where name = 'Amnesia'), (select id from stats where name = 'Special Defense'), 2),
  ((select id from passives where name = 'Captivate'), (select id from stats where name = 'Special Defense'), 2),
  ((select id from passives where name = 'Eerie Impulse'), (select id from stats where name = 'Special Defense'), 2),
  ((select id from passives where name = 'Gooey'), (select id from stats where name = 'Speed'), 1),
  ((select id from passives where name = 'Run Away'), (select id from stats where name = 'Speed'), 1),
  ((select id from passives where name = 'Tangling Hair'), (select id from stats where name = 'Speed'), 1),
  ((select id from passives where name = 'Agility'), (select id from stats where name = 'Speed'), 2),
  ((select id from passives where name = 'Autotomize'), (select id from stats where name = 'Speed'), 2),
  ((select id from passives where name = 'Cotton Spore'), (select id from stats where name = 'Speed'), 2),
  ((select id from passives where name = 'Rock Polish'), (select id from stats where name = 'Speed'), 2),
  ((select id from passives where name = 'Scary Face'), (select id from stats where name = 'Speed'), 2),
  ((select id from passives where name = 'Speed Boost'), (select id from stats where name = 'Speed'), 2),
  ((select id from passives where name = 'String Shot'), (select id from stats where name = 'Speed'), 2),
  ((select id from passives where name = 'Tailwind'), (select id from stats where name = 'Speed'), 2),
  ((select id from passives where name = 'Bulk Up'), (select id from stats where name = 'Attack'), 1),
  ((select id from passives where name = 'Bulk Up'), (select id from stats where name = 'Defense'), 1),
  ((select id from passives where name = 'Calm Mind'), (select id from stats where name = 'Special Attack'), 1),
  ((select id from passives where name = 'Calm Mind'), (select id from stats where name = 'Special Defense'), 1),
  ((select id from passives where name = 'Coil'), (select id from stats where name = 'Attack'), 2),
  ((select id from passives where name = 'Coil'), (select id from stats where name = 'Defense'), 1),
  ((select id from passives where name = 'Cosmic Power'), (select id from stats where name = 'Defense'), 1),
  ((select id from passives where name = 'Cosmic Power'), (select id from stats where name = 'Special Defense'), 1),
  ((select id from passives where name = 'Dragon Dance'), (select id from stats where name = 'Attack'), 1),
  ((select id from passives where name = 'Dragon Dance'), (select id from stats where name = 'Speed'), 1),
  ((select id from passives where name = 'Growth'), (select id from stats where name = 'Attack'), 1),
  ((select id from passives where name = 'Growth'), (select id from stats where name = 'Special Attack'), 1),
  ((select id from passives where name = 'Majesty’s Order'), (select id from stats where name = 'Attack'), 1),
  ((select id from passives where name = 'Majesty’s Order'), (select id from stats where name = 'Special Attack'), 1),
  ((select id from passives where name = 'Majesty’s Order'), (select id from stats where name = 'Defense'), 1),
  ((select id from passives where name = 'Majesty’s Order'), (select id from stats where name = 'Special Defense'), 1),
  ((select id from passives where name = 'Quiver Dance'), (select id from stats where name = 'Special Attack'), 1),
  ((select id from passives where name = 'Quiver Dance'), (select id from stats where name = 'Special Defense'), 1),
  ((select id from passives where name = 'Quiver Dance'), (select id from stats where name = 'Speed'), 1),
  ((select id from passives where name = 'Rototiller'), (select id from stats where name = 'Attack'), 1),
  ((select id from passives where name = 'Rototiller'), (select id from stats where name = 'Special Attack'), 1),
  ((select id from passives where name = 'Shift Gear'), (select id from stats where name = 'Attack'), 1),
  ((select id from passives where name = 'Shift Gear'), (select id from stats where name = 'Speed'), 2),
  ((select id from passives where name = 'Tearful Look'), (select id from stats where name = 'Defense'), 1),
  ((select id from passives where name = 'Tearful Look'), (select id from stats where name = 'Special Defense'), 1),
  ((select id from passives where name = 'Tickle'), (select id from stats where name = 'Attack'), 1),
  ((select id from passives where name = 'Tickle'), (select id from stats where name = 'Defense'), 1),
  ((select id from passives where name = 'Work Up'), (select id from stats where name = 'Attack'), 1),
  ((select id from passives where name = 'Work Up'), (select id from stats where name = 'Special Attack'), 1)
on conflict (passive_id, stat_id) do nothing;

insert into passives (name, description, passive_type, context) values
  ('Adaptability', 'Moves that are the same type as you deal +4 damage.', 'ability', 'combat'),
  ('Aerilate', 'Normal-type moves performed by you are treated as Flying-type moves.', 'ability', 'combat'),
  ('Aftermath', 'When knocked out by a melee attack, the attacker loses 1d20 HP.', 'ability', 'combat'),
  ('Analytic', 'When attacking a foe who has already acted this round, deal +4 damage.', 'ability', 'combat'),
  ('Anger Point', 'When hit by a critical hit, raise Attack +6 for 10 mins.', 'ability', 'combat'),
  ('Anger Shell', 'While you are below 20 HP, your attacks deal +4 damage.', 'ability', 'combat'),
  ('Armor Tail', 'You are immune to priority attacks that are used out of turn order during combat.', 'ability', 'combat'),
  ('Aroma Veil', 'You and your allies within 10ft of you are immune to the effects of the moves Heal Block, Taunt, Encore, and Disable and the passive Cursed Body.', 'ability', 'combat'),
  ('Battery', 'Allies within 15 ft of you have +1 Special Attack.', 'ability', 'combat'),
  ('Battle Armor', 'Critical hits are treated as normal hits against you.', 'ability', 'combat'),
  ('Berserk', 'While below half HP, you have +2 Special Attack.', 'ability', 'combat'),
  ('Big Pecks', 'Your Defense cannot be lowered by a foe’s effects.', 'ability', 'combat'),
  ('Blaze', 'When you are below 20 HP, your Fire type attacks deal +4 damage.', 'ability', 'combat'),
  ('Cheek Pouch', 'Whenever you consume a berry, you recover 10 HP in addition to any other effects.', 'ability', 'combat'),
  ('Chlorophyll', 'While in Sunny Weather, your Speed is +2.', 'ability', 'combat'),
  ('Clear Body', 'Your stats cannot be lowered by a foe’s effects.', 'ability', 'combat'),
  ('Cloud Nine', 'As a free action you may deplete one use of Defog and use Defog.', 'ability', 'combat'),
  ('Color Change', 'Whenever you are attacked, your type is changed to the same type as the attack after taking damage and effects for 5 mins.', 'ability', 'combat'),
  ('Comatose', 'You are always Asleep but can still act as if you aren’t. You are also immune to other afflictions.', 'ability', 'combat'),
  ('Commander', 'When adjacent to an allied Dondozo, Tatsugiri can go into Dondozo’s mouth as a free action. While inside the allied Dondozo’s mouth, Tatsugiri cannot act and its Skills and Passives cannot be used, but the allied Dondozo has +2 to its Attack, Defense, Special Attack, Special Defense, and Speed. Additionally, Tatsugiri cannot be targeted or hit by any attacks, is unaffected by the effects of any moves, and allows the allied Dondozo to use any of Tatsugiri’s moves.', 'ability', 'combat'),
  ('Competitive', 'If a foe lowers any of your stats, you have +2 Special Attack until your lowered stats are returned to normal.', 'ability', 'combat'),
  ('Compound Eyes', 'Add +1 during accuracy check whenever you use a ranged attack.', 'ability', 'combat'),
  ('Corrosion', 'You can Poison and Toxify Steel-types and Poisontypes.', 'ability', 'combat'),
  ('Costar', 'At the start of combat, copy a stat passive from your nearest ally until the end of combat.', 'ability', 'combat'),
  ('Cud Chew', 'When you consume a berry, its effect will activate a second time 1 round of combat later.', 'ability', 'combat'),
  ('Curious Medicine', 'Your stats and your adjacent ally’s stats cannot be lowered by a foe’s effects.', 'ability', 'combat'),
  ('Cursed Body', 'When you are hit by a foe’s melee attack, disable that attack for 10 mins. Cursed Body can only affect one attack at a time.', 'ability', 'combat'),
  ('Cute Charm', 'Whenever you are hit with a melee attack, roll 1d4. On 4, Infatuate the attacker.', 'ability', 'combat'),
  ('Damp', 'Chloroblast, Explosion, Misty Explosion, and Self- Destruct fail to do anything if used within 40ft of you.', 'ability', 'combat'),
  ('Dazzling', 'You may not be targeted by Priority moves that are being used out of turn order.', 'ability', 'combat'),
  ('Defeatist', 'When your HP is below half of your max hit points, your stats are all -2.', 'ability', 'combat'),
  ('Defiant', 'If a foe lowers any of your stats, you have +2 Attack until your lowered stats are returned to normal.', 'ability', 'combat'),
  ('Disguise', 'The first time you are hit with an attack each encounter, the attack is negated.', 'ability', 'combat'),
  ('Download', 'Your Attack is +1 against targets with lower Defense than Special Defense. Your Special Attack is +1 against targets with lower Special Defense than Defense.', 'ability', 'combat'),
  ('Drizzle', 'As a free action you may deplete one use of Rain Dance and use Rain Dance.', 'ability', 'combat'),
  ('Drought', 'As a free action you may deplete one use of Sunny Day and use Sunny Day.', 'ability', 'combat'),
  ('Dry Skin', 'In sunny weather, you lose 4 HP at the end of your actions. In rainy weather, you recover 4 HP at the end of your actions. You are immune to Water-type attacks.', 'ability', 'combat'),
  ('Early Bird', 'You roll twice during checks to wake from Sleep and use the higher result.', 'ability', 'combat'),
  ('Earth Eater', 'When you are hit by a Ground-type attack, halve the damage, then you heal that much HP instead of taking damage.', 'ability', 'combat'),
  ('Effect Spore', 'Whenever you are hit with a melee attack, roll 1d4. On 4, randomly either Paralyze, Poison, or put to Sleep the attacker.', 'ability', 'combat'),
  ('Electric Surge', 'As a free action you may deplete one use of Electric Terrain and use Electric Terrain.', 'ability', 'combat'),
  ('Electromorphosis', 'When hit by an attack that deals damage, you may use the move Charge as a free action', 'ability', 'combat'),
  ('Emergency Exit', 'You cannot fight when first damaged below half of Max HP. You will want to run away or return to a Poke Ball for 2 rounds. During those two rounds, your speed is doubled.', 'ability', 'combat'),
  ('Exposed', 'When you move or use an attack, you have –8 Defense and –8 Special Defense until your next turn. You also deal –8 damage with all attacks.', 'ability', 'combat'),
  ('Filter', 'Super-effective attacks against you deal –4 damage after applying weakness.', 'ability', 'combat'),
  ('Flame Body', 'Whenever you are hit with a melee attack, roll 1d4. On 4, Burn the attacker.', 'ability', 'combat'),
  ('Flare Boost', 'While Burned, your Special Attack is +4.', 'ability', 'combat'),
  ('Flash Fire', 'You are immune to Fire-type attacks. If you would be hit by a Fire-type attack, your Fire type attacks deal +4 damage for 2 mins.', 'ability', 'combat'),
  ('Flower Gift', 'While Cherrim is in Sunny Weather, Cherrim’s Attack and Special Defense is +6.', 'ability', 'combat'),
  ('Flower Veil', 'You and your allied Grass-type’s stats cannot be lowered by effects within 25ft of you.', 'ability', 'combat'),
  ('Fluffy', 'If hit by a melee attack, you only take half the damage. If hit by a Fire-type attack, you take twice the damage.', 'ability', 'combat'),
  ('Forecast', 'Your appearance and type changes with the weather. In Hailing, Hazy, or Misty weather, Castform is Ice-type. In Raining weather, Castform is Water-type. In Sandstorming weather, Castform is Rock-type. In Sunny weather, Castform is Fire-type.', 'ability', 'combat'),
  ('Friend Guard', 'Allies within 25ft of you take -1d4 damage when attacked.', 'ability', 'combat'),
  ('Fur Coat', 'If hit by a move using the Attack stat, you only take half the damage you would take.', 'ability', 'combat'),
  ('Gale Wings', 'If you use a Flying Type Move during your turn, your Speed is +2 until the end of your next turn.', 'ability', 'combat'),
  ('Galvanize', 'Normal-type moves performed by you are treated as Electric-type moves.', 'ability', 'combat'),
  ('Good as Gold', 'You are immune to Effect moves).', 'ability', 'combat'),
  ('Grass Pelt', 'While in Grassy Terrain, your Defense is +2.', 'ability', 'combat'),
  ('Grassy Surge', 'As a free action you may deplete one use of Grassy Terrain and use Grassy Terrain.', 'ability', 'combat'),
  ('Guard Dog', 'If a foe’s effect would cause you to flee or be moved, instead your Attack is raised +1 for 10 mins.', 'ability', 'combat'),
  ('Gulp Missile', 'Whenever Cramorant goes underwater, it gathers waste in its mouth. When hit by an attack within 30ft while Cramorant has waste, Cramorant ejects the waste at the offender, dealing 4 damage or 8 damage if Cramorant has less than 20 HP . Waste is held for up to 5 mins.', 'ability', 'combat'),
  ('Guts', 'While afflicted, your Attack is +2.', 'ability', 'combat'),
  ('Harvest', 'When using a Berry, you only use half of it while still gaining its full effects. You can only use half of a Berry if you have Harvest.', 'ability', 'combat'),
  ('Healer', 'After acting, you may roll 1d20. On 16 or higher, any adjacent allies are cured of all afflictions.', 'ability', 'combat'),
  ('Heatproof', 'Fire-type attacks are resisted by you. If you are already resistant to Fire-type, remove an additional damage die.', 'ability', 'combat'),
  ('Hospitality', '1/day, the first time you move adjacent to an ally per encounter, they are healed 12 HP.', 'ability', 'combat'),
  ('Hunger Switch', 'Whenever Morpeko acts, it changes from Full Belly mode to Hangry mode or back into Full Belly mode from Hangry mode. Aura Wheel is Electric-type in Full Belly mode, Aura Wheel is Dark-type in Hangry mode.', 'ability', 'combat'),
  ('Hustle', 'Your attacks against foes have -2 Accuracy. After the first time you miss an attack during an encounter, the -2 Accuracy penalty is removed and you gain +4 Attack until the end of the encounter.', 'ability', 'combat'),
  ('Hydration', 'While in Raining weather, you are cured of any afflictions.', 'ability', 'combat'),
  ('Hyper Cutter', 'Your Attack cannot be lowered by a foe’s effects.', 'ability', 'combat'),
  ('Ice Body', 'If in Hailing weather, you recover 4 HP after you act and you don’t take damage from Hailing weather.', 'ability', 'combat'),
  ('Ice Face', 'The first time Eiscue is hit with a melee attack each encounter; the attack is negated and you change to No Ice Face Form. Ice Face is reset whenever it starts Hailing while you are within its area of effect.', 'ability', 'combat'),
  ('Ice Scales', 'If hit by a Special Attack, you only take half the damage you would take.', 'ability', 'combat'),
  ('Illusion', 'As a free action, you may change your appearance to look like any Pokémon you have interacted with within the past hour. You may not appear as a Pokémon more than twice your size and the illusion is dropped when you are hit by an attack.', 'ability', 'combat'),
  ('Immunity', 'You are immune to getting Poisoned and Toxified.', 'ability', 'combat'),
  ('Imposter', 'As a free action you may use Transform.', 'ability', 'combat'),
  ('Infiltrator', 'Hindering terrain and Walls do not affect you or your attacks.', 'ability', 'combat'),
  ('Innards Out', 'When you are knocked out by a melee attack, deal damage to the attacker equal to the damage you just took.', 'ability', 'combat'),
  ('Inner Focus', 'You are immune to being Stunned.', 'ability', 'combat'),
  ('Insomnia', 'You are immune to being put to Sleep.', 'ability', 'combat'),
  ('Iron Barbs', 'Whenever you are hit with a melee attack, the attacker takes 4 damage.', 'ability', 'combat'),
  ('Iron Fist', 'Your punching attacks deal +4 damage.', 'ability', 'combat'),
  ('Justified', 'When a foe hits you with a Dark-type attack, your Attack is +1 for 10 mins.', 'ability', 'combat'),
  ('Keen Eye', 'Your accuracy checks cannot be negatively affected by foes.', 'ability', 'combat'),
  ('Leaf Guard', 'While in sunny weather, you are cured of any afflictions.', 'ability', 'combat'),
  ('Levitate', 'You are immune to Ground-type moves while you are airborne.', 'ability', 'combat'),
  ('Libero', 'You may change your types to the same types as an attack you are making while making it for 10 mins.', 'ability', 'combat'),
  ('Lightning Rod', 'Any foe’s ranged Electric-type attacks within 25ft or any adjacent foe’s Electric-type attacks are negated and drawn to you. Your Special Attack is +2 until the end of your next turn whenever you negate an Electric-type attack.', 'ability', 'combat'),
  ('Limber', 'You are immune to being Paralyzed.', 'ability', 'combat'),
  ('Lingering Aroma', 'When you are hit by a foe’s melee attack, disable all of the foe’s ability passives, then they gain Lingering Aroma for 10 mins.', 'ability', 'combat'),
  ('Liquid Ooze', 'If you are hit by an attack that damages you and heals the attacker, the attacker is dealt damage equal to what they would have healed, instead of healing.', 'ability', 'combat'),
  ('Liquid Voice', 'Sound-based moves made by you are Watertype.', 'ability', 'combat'),
  ('Magic Bounce', 'If you are hit by an attack that does not deal damage, the attacker is instead affected by the effects of their own attack.', 'ability', 'combat'),
  ('Magic Guard', 'Foes can only deal damage to you with attacks that deal damage. You are unaffected by damage from afflictions, coats, hazards, weather or any passives given by foes.', 'ability', 'combat'),
  ('Magician', 'When hitting with a melee attack, you steal the target’s held item, if any.', 'ability', 'combat'),
  ('Magma Armor', 'You are immune to being Frozen.', 'ability', 'combat'),
  ('Marvel Scale', 'While afflicted, your Defense is +2.', 'ability', 'combat'),
  ('Mega Launcher', 'Your pulse attacks deal +4 damage.', 'ability', 'combat'),
  ('Merciless', 'On hit, your attacks are critical hits if the target is Poisoned or Toxified.', 'ability', 'combat'),
  ('Mimicry', 'After acting, your type changes to reflect your current surroundings. If you are in a grassy field, Grass type; if you are in water, Water type; if you are on a mountain, Rock type; etc.', 'ability', 'combat'),
  ('Minus', 'If at least one ally has Plus or Minus within 10ft of you, you have +3 Special Attack.', 'ability', 'combat'),
  ('Mirror Armor', 'If your stats would be lowered by a foe’s effects, instead that offender’s stat is lowered.', 'ability', 'combat'),
  ('Misty Surge', 'As a free action you may deplete one use of Misty Terrain and use Misty Terrain.', 'ability', 'combat'),
  ('Mold Breaker', 'Your attacks ignore any passives that would redirect, negate or weaken your attacks.', 'ability', 'combat'),
  ('Motor Drive', 'Any Electric-type attack that hits you is negated and your speed is +1 for 10 mins. This can stack.', 'ability', 'combat'),
  ('Multiscale', 'When you are at Max HP, you take –4 damage from all attacks.', 'ability', 'combat'),
  ('Mummy', 'When you are hit by a foe’s melee attack, disable all of the foe’s ability passives, then they gain Mummy for 10 mins.', 'ability', 'combat'),
  ('Mycelium Might', 'When using an attack that can cause afflictions, ignore any immunities that foes may have when applying the affliction.', 'ability', 'combat'),
  ('Natural Cure', 'Whenever returned to a Poke Ball, you are cured of any afflictions.', 'ability', 'combat'),
  ('Neutralizing Gas', 'Ability passives other than your own do not work within 10ft of you.', 'ability', 'combat'),
  ('No Guard', 'You cannot miss your attacks, and attacks made against you cannot miss.', 'ability', 'combat'),
  ('Normalize', 'Attacks performed by you are treated as Normaltype attacks.', 'ability', 'combat'),
  ('Oblivious', 'You are immune to Infatuation.', 'ability', 'combat'),
  ('Overcoat', 'You are immune to damage from weather.', 'ability', 'combat'),
  ('Overgrow', 'When you are below 20 HP, your Grass-type attacks deal +4 damage', 'ability', 'combat'),
  ('Own Tempo', 'You are immune to being Confused.', 'ability', 'combat'),
  ('Pastel Veil', 'You and your allies within 10ft of you are immune to being Poisoned or Toxified.', 'ability', 'combat'),
  ('Perish Body', 'When you are hit by a melee attack, the offender receives 3 Perish Coats. The Coat has the following ability: After acting, destroy one of your Perish Coats. If this is the third Perish Coat you’ve destroyed this way during this encounter, set your HP to 0.', 'ability', 'combat'),
  ('Pickpocket', 'When you are hit by a melee attack, you steal the offender’s held item, if any.', 'ability', 'combat'),
  ('Pixilate', 'Normal-type moves performed by you are treated as Fairy-type moves.', 'ability', 'combat'),
  ('Plus', 'If at least one ally has Plus or Minus within 10ft of you, you have +3 Special Attack.', 'ability', 'combat'),
  ('Poison Heal', 'While afflicted with Poison or Toxification, you are healed instead of damaged by those afflictions. You are cured of Poison or Toxin once you are at Max HP.', 'ability', 'combat'),
  ('Poison Point', 'Whenever you are hit with a melee attack, roll 1d4. On 4, Poison the attacker.', 'ability', 'combat'),
  ('Poison Touch', 'Whenever you hit with a melee attack, you may roll 1d6. On 6, Poison the target.', 'ability', 'combat'),
  ('Power of Alchemy', 'When an ally is knocked out within 10ft of you, you gain one of your ally’s passives for 2 mins.', 'ability', 'combat'),
  ('Power Spot', 'Attacks made within 10ft of you deal +4 damage, regardless if the attacker is friend or foe.', 'ability', 'combat'),
  ('Prankster', 'Your attacks that do not deal damage on hit have Priority.', 'ability', 'combat'),
  ('Pressure', 'If you are hit by a 3/day attack, the attacker can’t use that attack for the remainder of the day.', 'ability', 'combat'),
  ('Propeller Tail', 'Your attacks cannot be redirected by passives or any other effect (except by interception), instead only hitting a target your attack was directed at.', 'ability', 'combat'),
  ('Protean', 'You may change your types to the same type as an attack you are making while making it for 10 mins.', 'ability', 'combat'),
  ('Psychic Surge', 'As a free action you may deplete one use of Psychic Terrain and use Psychic Terrain.', 'ability', 'combat'),
  ('Punk Rock', 'Your sound-based attacks deal +4 damage. You take 4 less damage from sound-based attacks.', 'ability', 'combat'),
  ('Purifying Salt', 'You are immune to status afflictions. You are resistant to Ghost-type attacks.', 'ability', 'combat'),
  ('Queenly Majesty', 'You may not be targeted by Priority moves that are being used out of turn order.', 'ability', 'combat'),
  ('Quick Draw', '1/day, you may give one of your moves priority.', 'ability', 'combat'),
  ('Quick Feet', 'While afflicted, your Speed is +2.', 'ability', 'combat'),
  ('Rain Dish', 'If in Raining Weather, you regain 4 HP after you act.', 'ability', 'combat'),
  ('Rattled', 'When a foe hits you with a Bug-type, Ghost-type, or Dark-type attack, your Speed is +1 for 10 mins. This can stack.', 'ability', 'combat'),
  ('Receiver', 'When an ally is knocked out within 10ft of you, you gain one of your ally’s passives for 2 mins.', 'ability', 'combat'),
  ('Reckless', 'Your attacks that damage yourself on hit, deal +4 damage.', 'ability', 'combat'),
  ('Refrigerate', 'Normal-type moves performed by you are treated as Ice-type moves.', 'ability', 'combat'),
  ('Regenerator', 'When returned to a Poke Ball, you recover to Max HP after being stored for 1 hour.', 'ability', 'combat'),
  ('Ripen', 'When you use a Berry, double any effects it has.', 'ability', 'combat'),
  ('Rock Head', 'Your attacks that damage yourself on hit do not damage yourself.', 'ability', 'combat'),
  ('Rocky Payload', 'Your Rock-type attacks deal +4 damage.', 'ability', 'combat'),
  ('Rough Skin', 'Whenever you are hit with a melee attack, the attacker takes 4 damage.', 'ability', 'combat'),
  ('Sand Force', 'While in Sandstorming Weather, your Rock-type and Ground-type attacks deal +4 damage and you don’t take damage from Sandstorming weather.', 'ability', 'combat'),
  ('Sand Rush', 'While in Sandstorming Weather, your Speed is +2 and you don’t take damage from Sandstorming weather.', 'ability', 'combat'),
  ('Sand Spit', 'When you are hit by a melee attack, as a free action you may deplete one use of Sandstorm and use Sandstorm immediately.', 'ability', 'combat'),
  ('Sand Stream', 'As a free action you may deplete one use of Sandstorm and use Sandstorm.', 'ability', 'combat'),
  ('Sand Veil', 'While in Sandstorming Weather, any foe’s attacks made against you have -1 during accuracy check and you don’t take damage from Sandstorming weather.', 'ability', 'combat'),
  ('Sap Sipper', 'You are immune to Grass-type attacks. If you would be hit by a Grass-type attack, your Attack is +2 for 10 mins.', 'ability', 'combat'),
  ('Schooling', 'When Wishiwashi is at half its HP or higher, it is in its School form. In its School form, Wishiwashi summons hundreds of fish-shaped balls of water and surrounds itself making it appear larger and making it stronger. When Wishiwashi is below half of its max hit points, Wishiwashi is in its Single form, dropping its façade and appearing much smaller on its own.', 'ability', 'combat'),
  ('Scrappy', 'Your Normal-type and Fighting-type attacks can hit Ghost-type targets.', 'ability', 'combat'),
  ('Screen Cleaner', 'Whenever you move through a Wall, Hazard, or adjacent to someone with a Coat, destroy all Walls, Hazards and Coats.', 'ability', 'combat'),
  ('Seed Sower', 'When you are hit by an attack that dealt damage, as a free action you may deplete one use of Grassy Terrain and use Grassy Terrain immediately.', 'ability', 'combat'),
  ('Sharpness', 'Your slashing attacks deal +4 damage.', 'ability', 'combat'),
  ('Shed Skin', 'After acting, you may roll 1d4. On 4, you are cured of any afflictions.', 'ability', 'combat'),
  ('Sheer Force', 'Your attacks that have additional effects that affect the target may deal +4 damage, but will not have those additional effects.', 'ability', 'combat'),
  ('Shell Armor', 'Critical hits are treated as normal hits against you.', 'ability', 'combat'),
  ('Shields Down', 'When Minior’s HP is at or below half of its max hit points, its form changes to Core Revealed. While Minior is not in its Core Revealed form, it is immune to afflictions.', 'ability', 'combat'),
  ('Shield Dust', 'You are unaffected by additional effects from attacks that deal damage.', 'ability', 'combat'),
  ('Skill Link', 'Your scatter moves have +2 during Accuracy Check.', 'ability', 'combat'),
  ('Slush Rush', 'While in Hailing weather, your Speed is +2 and you don’t take damage from Hailing weather.', 'ability', 'combat'),
  ('Sniper', 'When you land a critical hit, you deal an additional 8 damage.', 'ability', 'combat'),
  ('Snow Cloak', 'While in Hailing weather, any foe’s attacks made against you have -1 during Accuracy Check and you don’t take damage from Hailing weather.', 'ability', 'combat'),
  ('Snow Warning', 'As a free action you may deplete one use of Hail and use Hail.', 'ability', 'combat'),
  ('Solar Power', 'While in Sunny weather, you deal an additional 4 damage while attacking. After acting in Sunny weather, you take 4 damage.', 'ability', 'combat'),
  ('Solid Rock', 'Super-effective attacks against you deal –4 damage.', 'ability', 'combat'),
  ('Soundproof', 'You are immune to sound-based attacks.) **Sound based attacks: Boomburst, Bug Buzz, Chatter, Clanging Scales, Disarming Voice, Echoed Voice, Eerie Spell, Grass Whistle, Hyper Voice, Overdrive, Perish Song, Roar, Round, Sing, Snore, Sparkling Aria, Supersonic, Uproar', 'ability', 'combat'),
  ('Stakeout', 'When you attack a target who has just joined the encounter since your last turn, you deal +4 damage.', 'ability', 'combat'),
  ('Stalwart', 'Your attacks cannot be redirected by passives or any other effect (except by interception), instead only hitting a target your attack was directed at.', 'ability', 'combat'),
  ('Stance Change', 'Aegislash has two forms it constantly changes between. When you attack a foe, before making your accuracy check change into your Sword Form. When using a reaction move such as King’s Shield or Protect, or a protective move like Safeguard or Light Screen, immediately change to Shield Form.', 'ability', 'combat'),
  ('Static', 'Whenever you are hit with a melee attack, roll 1d4. On 4, Paralyze the attacker.', 'ability', 'combat'),
  ('Steadfast', 'When you are Stunned, your Speed is +1 for 10 mins.', 'ability', 'combat'),
  ('Steam Engine', 'When a foe hits you with a Fire-type or Watertype attack, your Speed is +2 for 10 mins.', 'ability', 'combat'),
  ('Steelworker', 'Your Steel-type attacks deal +4 damage.', 'ability', 'combat'),
  ('Steely Spirit', 'Steel-type attacks used within 10ft of you by yourself or allies deal +4 damage.', 'ability', 'combat'),
  ('Stench', 'Whenever you are hit with a melee attack, roll 1d4. On 4, Stun the attacker.', 'ability', 'combat'),
  ('Sticky Hold', 'You cannot drop held items or have held items stolen from you.', 'ability', 'combat'),
  ('Storm Drain', 'Any foe’s ranged Water-type attacks within 25ft or any adjacent foe’s Water-type attacks are negated and drawn to you. Your Special Attack is +2 until the end of your next turn whenever you negate a Water-type attack.', 'ability', 'combat'),
  ('Strong Jaw', 'Your biting attacks deal +4 damage.', 'ability', 'combat'),
  ('Sturdy', 'If you would be brought from Max HP to 0 or below, you are instead brought to 1 HP.', 'ability', 'combat'),
  ('Suction Cups', 'You cannot be moved by a foe’s attacks.', 'ability', 'combat'),
  ('Supreme Overlord', 'When you join combat, your Attack and Special Attack are each raised +1 for each ally who has already been knocked out in the current encounter, for 10 mins. Supreme Overlord can only raise your Attack and Special Attack each up to +4.', 'ability', 'combat'),
  ('Surge Surfer', 'While in Electrified terrain, your Speed is +2.', 'ability', 'combat'),
  ('Swarm', 'When you are below 20 HP, your Bug-type attacks deal +4 damage', 'ability', 'combat'),
  ('Sweet Veil', 'You and your allies within 10ft of you are immune to being put to Sleep.', 'ability', 'combat'),
  ('Swift Swim', 'While in Raining weather or in water, your Speed is +2.', 'ability', 'combat'),
  ('Symbiosis', 'You can pass held items to allies within 10ft as a free action.', 'ability', 'combat'),
  ('Synchronize', 'When you are Burned, Confused, Frozen, Poisoned, Paralyzed, put to Sleep, or Toxified by a foe, the offender is also given the same affliction.', 'ability', 'combat'),
  ('Tangled Feet', 'While you are confused, any foe’s attacks made against you have -1 during accuracy check.', 'ability', 'combat'),
  ('Technician', 'When rolling damage, replace any rolled 1s or 2s with 3.', 'ability', 'combat'),
  ('Telepathy', 'Your allies within 25ft do not harm you when the ally is using attacks that have an area of effect.', 'ability', 'combat'),
  ('Thermal Exchange', 'You are immune to being Burned. When you are hit by a Fire-type attack, your Attack is +2 for 10 mins.', 'ability', 'combat'),
  ('Thick Fat', 'You take -4 damage from Fire-type attacks and Icetype attacks.', 'ability', 'combat'),
  ('Tinted Lens', 'Your resisted attacks deal +4 damage.', 'ability', 'combat'),
  ('Too Pure', 'All attacks made against you are treated as if they are super-effective. If the attack already is, the attacker rolls +1 dice while rolling for damage.', 'ability', 'combat'),
  ('Torrent', 'When you are below 20 HP, your Water-type attacks deal +4 damage', 'ability', 'combat'),
  ('Tough Claws', 'Your slashing attacks deal +4 damage.', 'ability', 'combat'),
  ('Toxic Boost', 'If you would have been Poisoned, or Toxified, you are not and your Attack is +2 for 2 mins.', 'ability', 'combat'),
  ('Toxic Debris', 'When you are hit by an attack that dealt damage, as a free action you may deplete one use of Toxic Spikes and use Toxic Spikes immediately.', 'ability', 'combat'),
  ('Triage', 'Any moves you know that can heal have Reaction.', 'ability', 'combat'),
  ('Truant', 'All your moves have recharge turns. Truant cannot be removed, ignored, or disabled by any means.', 'ability', 'combat'),
  ('Unnerve', 'Foes within 25ft of you cannot consume food.', 'ability', 'combat'),
  ('Vital Spirit', 'You are immune to being put to Sleep.', 'ability', 'combat'),
  ('Volt Absorb', 'When you are hit by an electric-type attack, halve the damage, then you heal that much HP instead of taking damage.', 'ability', 'combat'),
  ('Wandering Spirit', 'Whenever you are hit with a melee attack, you gain all of the offender’s ability passives and lose Wandering Spirit, then they gain Wandering Spirit and lose all of their ability Passives for 10 mins.', 'ability', 'combat'),
  ('Water Absorb', 'When you are hit by a water-type attack, halve the damage, then you heal that much HP instead of taking damage.', 'ability', 'combat'),
  ('Water Bubble', 'You take -4 damage from Fire-type attacks. You add +4 damage to Water-type attacks. You are immune to being Burned.', 'ability', 'combat'),
  ('Water Compaction', 'When a foe hits you with a Water-type attack, your Defense is +2 for 10 mins.', 'ability', 'combat'),
  ('Water Veil', 'You are immune to being Burned.', 'ability', 'combat'),
  ('Weak Armor', 'When you are hit by a melee attack, your Defense is -3 and your Speed is +3 for 10 mins.', 'ability', 'combat'),
  ('Well-Baked Body', 'You are immune to Fire-type attacks. When you are hit by Fire-type attacks, instead your Defense is +2 for 10 mins.', 'ability', 'combat'),
  ('White Smoke', 'Your stats cannot be lowered by a foe’s effects.', 'ability', 'combat'),
  ('Wind Power', 'When hit by a wind based attack, you may use the move Charge as a free action) **Wind based attacks: Air Cutter, Blizzard, Fairy Wind, Gust, Heat Wave, Hurricane, Icy Wind, Petal Blizzard, Twister, Whirlwind', 'ability', 'combat'),
  ('Wind Rider', 'When hit by a wind based attack, your Attack is +1 for 10 mins.) **Wind based attacks: Air Cutter, Blizzard, Fairy Wind, Gust, Heat Wave, Hurricane, Icy Wind, Petal Blizzard, Twister, Whirlwind', 'ability', 'combat'),
  ('Wonder Guard', 'Shedinja is immune to attacks that are not super-effective. Wonder Guard cannot be removed, ignored, or disabled by any means.', 'ability', 'combat'),
  ('Wonder Skin', 'Your stats cannot be lowered by a foe’s effects.', 'ability', 'combat'),
  ('Zen Mode', 'Darmanitan changes to its Zen Mode when it is at or below half of its max HP.', 'ability', 'combat'),
  ('Zero to Hero', 'When Palafin is reduced to 30 or less HP or if an ally is knocked out within 30ft of Palafin, you change from your Zero form to your Hero form for 10 mins.', 'ability', 'combat')
on conflict (name) do nothing;

insert into passives (name, description, passive_type, context) values
  ('Alluring', 'Pokémon who are alluring smell very pleasant. They may attract wild Pokémon easily. Attention is commonly turned toward fragrant, alluring Pokémon by wilds. If a Pokémon learns the move Aromatherapy or Sweet Scent and does not have the alluring skill, they gain alluring. (attracts others with their aroma)', 'ability', 'out_of_combat'),
  ('Amorphous', 'Amorphous Pokémon have an inconsistent shape. They can flatten and reform themselves like gel. They can stretch out their body material and condense themselves as well. By doing this, a Pokémon can access places others couldn’t, or bypass a door or two, only to let their non-amorphous friends in afterwards. (can change their body into a liquid-like state)', 'ability', 'out_of_combat'),
  ('Beached', 'When a Pokémon has the beached skill, they need to stay in water. Beached means the Pokémon has a hard time battling when not submerged in water. For every round of an encounter the Pokémon is not at least half way submerged in water, they lose 10% of their max HP. If the Pokémon is lowered to -100% HP for more than 10 rounds of combat, make a deaths savings roll as usual. Beached Pokémon can calmly remain out of water. If a Pokémon learns the move Slippin Slide or Tidepools, it loses the Beached skill. (needs to be in water)', 'ability', 'out_of_combat'),
  ('Burrow', 'Pokémon with burrow can quickly dig through solid earth, rock, clay, or even soft sand. When moving through any earth, burrowing Pokémon treat underground as normal terrain, without penalizing their movement speed. If a Pokémon learns the move Dig and does not have the burrow skill, they gain burrow (moves through earth easily)', 'ability', 'out_of_combat'),
  ('Chilled', 'Chilled Pokémon are always cold to the touch. (always cold)', 'ability', 'out_of_combat'),
  ('Climber', 'Pokémon with an aptitude for climbing, or just many sticky legs, treat vertical terrain and even ceiling surfaces as normal terrain that they can navigate without affecting their movement speed. (treats walls and ceilings as normal terrain)', 'ability', 'out_of_combat'),
  ('Firestarter', 'A Pokémon who has the firestarter skill can produce flames. They can control how lightly or powerfully they produce the fire, creates puffs of fire the size of a lighter or a large burst of fire capable of engulfing a tree. If a Pokémon learns the move Blast Burn, Blaze Kick, Ember, Fiery Dance, Fire Blast, Fire Fang, Fire Lash, Fire Punch, Fire Spin, Flame Burst, Flame Charge, Flame Wheel, Flamethrower, Flare Blitz, Heat Crash, Heat Wave, or Incinerate and does not have the firestarter Skill, they gain firestarter. (can create fire)', 'ability', 'out_of_combat'),
  ('Flopper', 'A Pokémon with the flopper Skill probably doesn’t like being out of water. While it’s not dangerous to move around on, a flopper treats all normal terrain as difficult terrain and all difficult terrain as blocking terrain. If anything modifies how a Pokémon moves making movement easier, Pokémon with flopper will still treat difficult terrain as difficult terrain but can then flop around on normal terrain without trouble. If a Pokémon learns the move Slippin Slide or Tidepools, it loses the Flopper skill. (treats dry land as special terrain)', 'ability', 'out_of_combat'),
  ('Flight', 'Pokémon with flight are not bound to the ground. Through means of wings, or psychic ability, or electromagnetic levitation, these Pokémon can remain in the air for hours at a time, sometimes never needing to return to the ground. These Pokémon can use their movements speeds in the air. If a Pokémon learns the move Fly and does not have the flight Skill, they gain flight. (can fly)', 'ability', 'out_of_combat'),
  ('Fountain', 'A Pokémon who has the fountain skill can produce freshwater. They can control how lightly or powerfully they produce the water, sprinkling water or forcefully shooting water with the strength of a fire hose. If a Poké- mon learns the move Hydro Cannon, Hydro Pump, Liquidation, Scald, Soak, Water Gun, Water Pulse, Waterfall, Whirlpool and does not have the fountain Skill, they gain fountain. (can create water)', 'ability', 'out_of_combat'),
  ('Freezer', 'When a Pokémon has the freezer skill, they can produce ice at a controlled rate. They can make puffs of snow, or ice cubes, or spread icicles across surfaces. As their action, a Pokémon with freezer can target an area on the ground and slowly turn it into icy, difficult terrain. They can make one 5x5 ft. area into icy, difficult terrain or fluffy, snowy, difficult terrain per 6 seconds. If a Pokémon learns the move Aurora Beam, Blizzard, Freeze-Dry, Frost Breath, Ice Beam, Ice Fang, Ice Punch, Icy Wind, Powder Snow, or Sheer Cold, and does not have the freezer skill, they gain freezer. (can create ice)', 'ability', 'out_of_combat'),
  ('Gilled', 'A gilled Pokémon can breathe underwater. It never needs to come up for air, remaining underwater for as long as it wants to. (can breathe underwater)', 'ability', 'out_of_combat'),
  ('Glow', 'A Pokémon with the glow skill can emit light from a part of its body. Depending on the variety of wild Pokémon nearby, it might attract Pokémon or ward them away. If a Pokémon learns the move Flash or stat passive Tail Glow and does not have the glow skill, they gain glow. (can produce light)', 'ability', 'out_of_combat'),
  ('Groundshaper', 'A Pokémon with the groundshaper skill can skillfully and precisely transform the terrain around them to create difficult terrain or flatten out rough terrain to create normal terrain. As their action, a Pokémon with groundshaper can target an area on the ground and slowly turn it into sandy, or rock covered difficult terrain, or change difficult terrain into smooth dirt-covered, normal terrain. They can make one 5x5 ft. area into difficult terrain or normal terrain per 6 seconds. If a Pokémon learns the move Bulldoze, Earth Power, Earthquake, Sand Tomb, or Stomping Tantrum and does not have the groundshaper Skill, they gain groundshaper. (can manipulate the ground)', 'ability', 'out_of_combat'),
  ('Guster', 'The guster can create bursts of wind. The power can vary from a light breeze to a powerful burst of air capable of lifting light objects into the air or providing lift for a chute. If a Pokémon learns the move Gust, or Hurricane, or the stat passive Tailwind and does not have the guster Skill, they gain guster. (can produce wind)', 'ability', 'out_of_combat'),
  ('Heater', 'A Pokémon with the heater skill is always warm when touched. (always warm)', 'ability', 'out_of_combat'),
  ('Hover', 'hovering Pokémon use some force in order to float above the ground, or even over water, without touching the surface. Whether its magnetic, gravitational, air currents, or some other magical power, it’s uncertain what keeps some of these Pokémon in the air, but they can’t go higher than 10 ft off the ground while staying airborne indefinitely. If a Pokémon learns the move Magnet Rise or the ability Levitate and does not have the hover skill, they gain hover. (can hover)', 'ability', 'out_of_combat'),
  ('Inflatable', 'A Pokémon with the skill inflatable can expand its size from tiny to small, small to medium, medium to large, large to huge, or huge to gigantic. They do so by inhaling vast amounts of air or temporarily growing the size of their plant-like bodies. While inflated, a Pokémon does not change its weight. A Pokémon can maintain its larger size for up to 5 mins. If a Pokémon learns the move Stockpile or the stat passive Growth and does not have the inflatable skill, they gain inflatable. (can expand)', 'ability', 'out_of_combat'),
  ('Intelligence', 'Intelligence marks a Pokémon for higher brain function and often these Pokémon can surpass human intellect. While intelligent Pokémon are capable of independent decisions, they still trust your leadership and will usually wait for your instruction. If you are unconscious or otherwise unable to make decisions, an intelligent Poké- mon will act on its own accord, once per round if none of your other Pokémon are acting that round. Intelligent Poké- mon are problem solvers and can be dangerous foes if encountered in the wild. (very smart)', 'ability', 'out_of_combat'),
  ('Invisibility', 'Pokémon who have the invisibility skill can turn invisible. Pokémon may not perform moves while invisible. While invisible, foes must roll +4 during an accuracy checks to hit you and still need a general idea of where you last were to hit you. When a Pokémon turns invisible, they can only remain invisible for up to 4 minutes. After becoming visible, they must wait two plus the number of minutes they spent invisible before using their invisibility again. You cannot turn invisible in the same turn you’ve attacked. (can turn invisible)', 'ability', 'out_of_combat'),
  ('Magnetic', 'Magnetic Pokémon can lightly manipulate magnetic fields. With this, they can repel iron and/or steel or attract iron and/or steel, holding it too their body or pushing it away. Through this magnetic manipulation, they can also feel magnetic fields and discern north. If a Pokémon learns the move Magnet Rise, Magnet Pull or Magnet Bomb and does not have the magnetic Skill, they gain magnetic. (controls magnetic fields)', 'ability', 'out_of_combat'),
  ('Mind Lock', 'Pokémon who have the skill mind lock cannot have their minds read. (minds can’t be read)', 'ability', 'out_of_combat'),
  ('Modular', 'Modular Pokémon are often made up of separate units that make of their body or consciousness. Modular Pokémon can often take up different spaces simultaneously during combat and reshape themselves to fit in different ways at different sizes everywhere. Modular Poké- mon stats do not change no matter how they are configured. Modular Pokémon cannot separate a part of themselves further than 50ft from any other part of their body. Consider the Pokémon– Falinks can reconfigure into six bodies, Magneton into three. If a Pokémon learns the move Substitute and does not have the Modular skill, they gain Modular 2 while the substitute is active. (consists of X parts)', 'ability', 'out_of_combat'),
  ('Phasing', 'A Pokémon with phasing may move through hindering or blocking terrain without their movement speed being affected. They can turn intangible and move through solid walls or another Pokémon. A Pokémon can remain intangible with phasing for up to 30 seconds. If a Pokémon remains intangible, they may not perform moves during their turn. Attacks that use the Special Attack stat can still target and hit a phasing Pokémon. If a Pokémon learns the move Phantom Force and does not have the phasing skill, they gain phasing. (can move through solid objects)', 'ability', 'out_of_combat'),
  ('Reach', 'A Pokémon with reach may make melee attacks from up to 25 ft. away. Pokémon with reach are either really large or have a stretchy limb with which they can strike foes from a distance. (melee range is X ft.)', 'ability', 'out_of_combat'),
  ('Repulsive', 'This Pokémon can emit an unpleasant odor that Wild Pokémon find repulsive. Wild Pokémon may ignore this smell to protect something precious to them. If a Pokémon learns the move Corrosive Gas, Gastro Acid, Gunk Shot, Poison Gas, Sludge, Sludge Bomb, Sludge Wave, Smog, or Venom Drench and does not have the repulsive Skill, they gain repulsive. (repels others with a foul smell)', 'ability', 'out_of_combat'),
  ('Shrinkable', 'A Pokémon with the skill shrinkable can shrink its size from gigantic to huge, huge to large, large to medium, medium to small, or small to tiny. While shrunken, a Pokémon may not perform any moves and it does not change its weight. A Pokémon can maintain its smaller size for up to 5 mins. If a Pokémon learns the move Minimize and does not have the shrinkable skill, they gain shrinkable. (can shrink)', 'ability', 'out_of_combat'),
  ('Sinker', 'Sinker means the Pokémon cannot swim, or move while submerged in water. For every round of an encounter the Pokémon is in water that is deep enough for them to stand submerged in, they lose 10% of their max HP. If the Pokémon is lowered to -100% HP for more than 10 rounds of combat, make a deaths savings roll as usual. If a Pokémon gains the swimmer skill, they lose their sinker skill. (can’t swim)', 'ability', 'out_of_combat'),
  ('Sprouter', 'A Pokémon with the sprouter skill can rapidly influence the growth of plants and flora around them. Over 6 seconds, a sprouter can grow a plant 5 ft taller or wider than it currently was. Through the use of sprouter, the Pokémon can also make plants grow up to twice of the normal size they would become naturally. If a Pokémon learns the move Frenzy Plant, Grass Knot, Ingrain, Leech Seed, or Synthesis and does not have the sprouter Skill, they gain sprouter. (can manipulate plant life)', 'ability', 'out_of_combat'),
  ('Stealth', 'Not all Pokémon are allowed to make a stealth check. With stealth, Pokémon may roll a stealth check like a human trainer, adding their Speed modifier, calculated like a human’s, to see if they can silently move during or outside of battle without being detected. (can make stealth skill checks)', 'ability', 'out_of_combat'),
  ('Strength', 'A Pokémon with the strength skill is exceptionally strong, physically. With little effort, they can lift and move things vastly heavier than themselves. If they are featherweight, they can easily lift medium weights; if light weight, they can easily lift heavy weights; if medium weighted, they can easily lift over 400-600 lbs.; at heavy weight, they can easily lift over 800-1000 lbs.; superweights with strength can lift or push up to 1000-1500 lbs. If a Poké- mon learns the move Strength, they gain the strength skill. (very strong)', 'ability', 'out_of_combat'),
  ('Swimmer', 'A swimmer loves the water. They treat kneedeep water as normal terrain as well as anything deeper than that. Swimmers are not always gilled, so make sure they’re coming up for air when they need to. If a Pokémon learns the move Aqua Jet or Slippin Slide, they gain the swimmer skill. (can swim)', 'ability', 'out_of_combat'),
  ('Telekinetic', 'Telekinetic Pokémon can move objects with their mind. They can lift things that are lighter than themselves. They can move objects up to 25 ft. away. If a Poké- mon learns the move Confusion, Extrasensory, Psychic, or Trick and does not have the telekinetic skill, they gain telekinetic. (can move things with their mind)', 'ability', 'out_of_combat'),
  ('Telepath', 'A telepathic Pokémon can read the minds of people and another Pokémon. Telepathic Pokémon can project their thoughts to humans and Pokémon. The Poké- mon can only read surface thoughts. Some species can only read emotions and will specify if that’s the case. If a Poké- mon learns the move Mind Reader or the ability Telepathy and does not have the telepath skill, they gain telepath. (can read minds) or (can read emotions)', 'ability', 'out_of_combat'),
  ('Threaded', 'If a Pokémon has the threaded skill they may move around with their threaded skill by shooting out silk webs or strong vines. A threaded movement is when a Pokémon targets an object less than 30 ft. away and shoots a strong, thin line of silk, or extends a vine from themselves, and then quickly retracts that silk, or vine, pulling itself towards the object if the Pokémon is lighter than the object or pulling the object towards the Pokémon if the object is lighter than it is. If you target another Pokémon or person with a threaded movement, roll your accuracy check against their Speed stat. You may still use a move on the same turn you perform a threaded movement. If a Pokémon learns the move Electro Web, Spider Web, Vine Whip or Power Whip, or the stat passive String Shot, and does not have the threaded skill, they gain threaded. (can move around on spun threads/vines)', 'ability', 'out_of_combat'),
  ('Tough Cookie', 'A tough cookie has it rough and is used to be knocked unconscious due to its frail constitution. If a Pokémon with Tough Cookie is knocked unconscious, the attacker must deal enough damage for the Tough Cookie to be at –25HP or lower with the intention to kill in order to force a death saving throw. This only matters if you are playing with death saving throws. (lowers chance of death)', 'ability', 'out_of_combat'),
  ('Tracker', 'Pokémon with the skill tracker have a strong sense of smell that they can use to follow other Pokémon or people using a Investigate skill check, adding their Special Attack modifier. If the Pokémon has smelled whom they want to track in the past day, or one of their personal belongings, they can pursue that prey with a skill check of 11 or better. To pick up a random scent from nothing, a skill check of 16 or better will allow the Pokémon to follow that scent. To pick up a specific scent from nothing, a skill check of 20 will allow the Pokémon to follow that scent. A Pokémon may only make these checks once per hour. If a Pokémon learns the move Odor Sleuth and does not have the tracker Skill, they gain tracker. (can follow scents)', 'ability', 'out_of_combat'),
  ('Wired', 'Wired Pokémon have a special relation to electronic devices. They can enter machines and travel through connected electronics through any cords that connect them instantly. While inside machines, they can read data on the machine or they can even take control of the machine on a programming skill check adding their Special Attack modifier. (can go into electronics)', 'ability', 'out_of_combat'),
  ('Zapper', 'Pokémon with the zapper skill can produce controlled electricity or send electrical currents through various conductive materials. If an electrical device is capable of being recharged, a Pokémon with zapper can recharge it to full power slowly. If a Pokémon learns the move Charge, Charge Beam, Discharge, Electrify, Electro Ball, Parabolic Charge, Shock Wave, Spark, Thunder, Thunder Fang, Thunder Punch, Thunder Shock, Thunder Wave, Thunderbolt, Volt Tackle, Wild Charge, or Zap Cannon and does not have the zapper skill, they gain zapper. (can produce electricity)', 'ability', 'out_of_combat')
on conflict (name) do nothing;

