-- Same fix as 20260918200000_fix_pokedex_moves_level_learned.sql, applied to
-- pokedex_passives.level_learned -- same import provenance (20260726140000_pokedex_learnset_columns.sql:
-- "some PokeAPI level-up 'moves' are modeled as Passives instead of Moves in PTA3, e.g. Growl"), same
-- spurious level-1 spike (980 of ~2236+983 non-null rows were at level 1 before this fix, an anomalous
-- spike versus a normal-looking curve at every neighboring level), same two rules, re-using the
-- already-cached PokeAPI species data from the Moves fix:
--
-- [confirmed] rows (394): the same passive/move shows a level > 1 in one game version and level 1 in
-- another, for the same species -- corrected to the minimum level > 1 seen.
--
-- [estimate] rows (13): flat at level 1 in every game for a non-evolved species, but the same
-- passive is typically learned well past level 10 by other species -- corrected to the lowest level
-- any other species is recorded learning it at (an estimate, not confirmed per-species data).
--
-- Not touched: 553 rows with no evidence of a problem; 20 rows across 14 species that failed to match
-- PokeAPI at all (custom regional/form variants like "Arcanine (Ancient)"/"Basculin (Blue)", plus
-- "Pyroar" which 404'd for the same unclear reason the original 2026-08-05 import's own report
-- documented); 3 rows ("Play nice"/"String shot"/"Rototiller") where PokeAPI genuinely lists no move
-- of that name at all for the species in question -- checked, this isn't a slug-formatting quirk like
-- "Smoke screen" was, so there's no known fix available from this data source.
update pokedex_passives set level_learned = 4 where pokedex_id = 472 and passive_id = 324; -- [confirmed] Absol / Leer: 1 -> 4 (versions saw: 5,4,1)
update pokedex_passives set level_learned = 8 where pokedex_id = 943 and passive_id = 360; -- [confirmed] Aerodactyl / Agility: 1 -> 8 (versions saw: 1,8,17,28,50)
update pokedex_passives set level_learned = 15 where pokedex_id = 943 and passive_id = 364; -- [confirmed] Aerodactyl / Scary face: 1 -> 15 (versions saw: 36,1,15)
update pokedex_passives set level_learned = 4 where pokedex_id = 628 and passive_id = 338; -- [confirmed] Aggron / Harden: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 11 where pokedex_id = 1211 and passive_id = 369; -- [confirmed] Alakazam / Calm mind: 1 -> 11 (versions saw: 33,36,42,41,0,1,50,11)
update pokedex_passives set level_learned = 6 where pokedex_id = 1183 and passive_id = 373; -- [confirmed] Amoonguss / Growth: 1 -> 6 (versions saw: 1,6)
update pokedex_passives set level_learned = 5 where pokedex_id = 481 and passive_id = 337; -- [confirmed] Ampharos / Growl: 1 -> 5 (versions saw: 1,5)
update pokedex_passives set level_learned = 7 where pokedex_id = 950 and passive_id = 338; -- [confirmed] Anorith / Harden: 1 -> 7 (versions saw: 7,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 905 and passive_id = 324; -- [confirmed] Arbok / Leer: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 5 where pokedex_id = 988 and passive_id = 364; -- [confirmed] Ariados / Scary face: 1 -> 5 (versions saw: 1,6,5,12)
update pokedex_passives set level_learned = 7 where pokedex_id = 951 and passive_id = 338; -- [confirmed] Armaldo / Harden: 1 -> 7 (versions saw: 1,7)
update pokedex_passives set level_learned = 4 where pokedex_id = 626 and passive_id = 338; -- [confirmed] Aron / Harden: 1 -> 4 (versions saw: 4,1)
update pokedex_passives set level_learned = 16 where pokedex_id = 598 and passive_id = 337; -- [confirmed] Audino / Growl: 1 -> 16 (versions saw: 1,16)
update pokedex_passives set level_learned = 27 where pokedex_id = 581 and passive_id = 345; -- [confirmed] Avalugg / Iron defense: 1 -> 27 (versions saw: 1,27)
update pokedex_passives set level_learned = 4 where pokedex_id = 1265 and passive_id = 324; -- [confirmed] Axew / Leer: 1 -> 4 (versions saw: 4,1)
update pokedex_passives set level_learned = 2 where pokedex_id = 633 and passive_id = 336; -- [confirmed] Azumarill / Defense curl: 1 -> 2 (versions saw: 1,3,2,10)
update pokedex_passives set level_learned = 2 where pokedex_id = 633 and passive_id = 328; -- [confirmed] Azumarill / Tail whip: 1 -> 2 (versions saw: 1,6,7,2)
update pokedex_passives set level_learned = 2 where pokedex_id = 631 and passive_id = 328; -- [confirmed] Azurill / Tail whip: 1 -> 2 (versions saw: 6,7,2,1)
update pokedex_passives set level_learned = 7 where pokedex_id = 1256 and passive_id = 324; -- [confirmed] Bagon / Leer: 1 -> 7 (versions saw: 9,10,7,1)
update pokedex_passives set level_learned = 3 where pokedex_id = 549 and passive_id = 338; -- [confirmed] Baltoy / Harden: 1 -> 3 (versions saw: 3,4,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 1039 and passive_id = 330; -- [confirmed] Banette / Screech: 1 -> 4 (versions saw: 1,8,5,4)
update pokedex_passives set level_learned = 7 where pokedex_id = 962 and passive_id = 341; -- [confirmed] Barbaracle / Withdraw: 1 -> 7 (versions saw: 7,1)
update pokedex_passives set level_learned = 10 where pokedex_id = 956 and passive_id = 349; -- [confirmed] Bastiodon / Metal sound: 1 -> 10 (versions saw: 1,10)
update pokedex_passives set level_learned = 5 where pokedex_id = 568 and passive_id = 337; -- [confirmed] Beartic / Growl: 1 -> 5 (versions saw: 1,5)
update pokedex_passives set level_learned = 4 where pokedex_id = 1239 and passive_id = 337; -- [confirmed] Beheeyem / Growl: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 39 where pokedex_id = 1158 and passive_id = 375; -- [confirmed] Bellossom / Quiver dance: 1 -> 39 (versions saw: 39,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 1152 and passive_id = 373; -- [confirmed] Bellsprout / Growth: 1 -> 4 (versions saw: 1,6,7,4)
update pokedex_passives set level_learned = 5 where pokedex_id = 819 and passive_id = 337; -- [confirmed] Bibarel / Growl: 1 -> 5 (versions saw: 1,5)
update pokedex_passives set level_learned = 5 where pokedex_id = 818 and passive_id = 337; -- [confirmed] Bidoof / Growl: 1 -> 5 (versions saw: 5,1)
update pokedex_passives set level_learned = 6 where pokedex_id = 1295 and passive_id = 324; -- [confirmed] Bisharp / Leer: 1 -> 6 (versions saw: 1,6)
update pokedex_passives set level_learned = 4 where pokedex_id = 410 and passive_id = 328; -- [confirmed] Blastoise / Tail whip: 1 -> 4 (versions saw: 1,4,5)
update pokedex_passives set level_learned = 10 where pokedex_id = 410 and passive_id = 341; -- [confirmed] Blastoise / Withdraw: 1 -> 10 (versions saw: 31,1,10,14)
update pokedex_passives set level_learned = 7 where pokedex_id = 389 and passive_id = 382; -- [confirmed] Blaziken / Focus energy: 1 -> 7 (versions saw: 1,7,37,35)
update pokedex_passives set level_learned = 31 where pokedex_id = 592 and passive_id = 336; -- [confirmed] Blissey / Defense curl: 1 -> 31 (versions saw: 33,31,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 592 and passive_id = 337; -- [confirmed] Blissey / Growl: 1 -> 4 (versions saw: 4,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 616 and passive_id = 338; -- [confirmed] Boldore / Harden: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 14 where pokedex_id = 842 and passive_id = 329; -- [confirmed] Braviary / Hone claws: 1 -> 14 (versions saw: 14,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 428 and passive_id = 337; -- [confirmed] Brionne / Growl: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 4 where pokedex_id = 1169 and passive_id = 373; -- [confirmed] Budew / Growth: 1 -> 4 (versions saw: 4,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 656 and passive_id = 337; -- [confirmed] Buizel / Growl: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 3 where pokedex_id = 352 and passive_id = 337; -- [confirmed] Bulbasaur / Growl: 1 -> 3 (versions saw: 1,4,3)
update pokedex_passives set level_learned = 4 where pokedex_id = 821 and passive_id = 336; -- [confirmed] Buneary / Defense curl: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 45 where pokedex_id = 1029 and passive_id = 382; -- [confirmed] Buzzwole / Focus energy: 1 -> 45 (versions saw: 1,45)
update pokedex_passives set level_learned = 7 where pokedex_id = 1168 and passive_id = 373; -- [confirmed] Cacturne / Growth: 1 -> 7 (versions saw: 1,9,7)
update pokedex_passives set level_learned = 8 where pokedex_id = 514 and passive_id = 382; -- [confirmed] Camerupt / Focus energy: 1 -> 8 (versions saw: 25,15,12,1,8)
update pokedex_passives set level_learned = 7 where pokedex_id = 997 and passive_id = 338; -- [confirmed] Cascoon / Harden: 1 -> 7 (versions saw: 1,7,0)
update pokedex_passives set level_learned = 5 where pokedex_id = 1075 and passive_id = 338; -- [confirmed] Celesteela / Harden: 1 -> 5 (versions saw: 1,5)
update pokedex_passives set level_learned = 4 where pokedex_id = 591 and passive_id = 336; -- [confirmed] Chansey / Defense curl: 1 -> 4 (versions saw: 44,41,31,1,4)
update pokedex_passives set level_learned = 5 where pokedex_id = 591 and passive_id = 337; -- [confirmed] Chansey / Growl: 1 -> 5 (versions saw: 30,5,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 591 and passive_id = 328; -- [confirmed] Chansey / Tail whip: 1 -> 4 (versions saw: 1,9,5,8,4)
update pokedex_passives set level_learned = 4 where pokedex_id = 382 and passive_id = 337; -- [confirmed] Charizard / Growl: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 15 where pokedex_id = 382 and passive_id = 324; -- [confirmed] Charizard / Leer: 1 -> 15 (versions saw: 1,15)
update pokedex_passives set level_learned = 4 where pokedex_id = 456 and passive_id = 366; -- [confirmed] Charjabug / String shot: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 4 where pokedex_id = 380 and passive_id = 337; -- [confirmed] Charmander / Growl: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 4 where pokedex_id = 381 and passive_id = 337; -- [confirmed] Charmeleon / Growl: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 7 where pokedex_id = 1172 and passive_id = 373; -- [confirmed] Cherrim / Growth: 1 -> 7 (versions saw: 1,7)
update pokedex_passives set level_learned = 4 where pokedex_id = 1224 and passive_id = 337; -- [confirmed] Chimecho / Growl: 1 -> 4 (versions saw: 6,1,4)
update pokedex_passives set level_learned = 3 where pokedex_id = 550 and passive_id = 338; -- [confirmed] Claydol / Harden: 1 -> 3 (versions saw: 1,3,4)
update pokedex_passives set level_learned = 4 where pokedex_id = 1313 and passive_id = 336; -- [confirmed] Clefairy / Defense curl: 1 -> 4 (versions saw: 39,26,25,13,4,1)
update pokedex_passives set level_learned = 20 where pokedex_id = 1315 and passive_id = 335; -- [confirmed] Cleffa / Charm: 1 -> 20 (versions saw: 1,20)
update pokedex_passives set level_learned = 49 where pokedex_id = 1071 and passive_id = 380; -- [confirmed] Cobalion / Work up: 1 -> 49 (versions saw: 61,1,49)
update pokedex_passives set level_learned = 34 where pokedex_id = 1047 and passive_id = 364; -- [confirmed] Cofagrigus / Scary face: 1 -> 34 (versions saw: 34,0,1)
update pokedex_passives set level_learned = 7 where pokedex_id = 388 and passive_id = 382; -- [confirmed] Combusken / Focus energy: 1 -> 7 (versions saw: 1,7,36,35)
update pokedex_passives set level_learned = 13 where pokedex_id = 1329 and passive_id = 373; -- [confirmed] Comfey / Growth: 1 -> 13 (versions saw: 13,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 880 and passive_id = 382; -- [confirmed] Conkeldurr / Focus energy: 1 -> 4 (versions saw: 1,4,12)
update pokedex_passives set level_learned = 5 where pokedex_id = 1114 and passive_id = 338; -- [confirmed] Corphish / Harden: 1 -> 5 (versions saw: 7,5,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 1105 and passive_id = 338; -- [confirmed] Corsola / Harden: 1 -> 4 (versions saw: 7,6,4,1)
update pokedex_passives set level_learned = 9 where pokedex_id = 889 and passive_id = 324; -- [confirmed] Crabominable / Leer: 1 -> 9 (versions saw: 1,9)
update pokedex_passives set level_learned = 5 where pokedex_id = 1115 and passive_id = 338; -- [confirmed] Crawdaunt / Harden: 1 -> 5 (versions saw: 1,7,5)
update pokedex_passives set level_learned = 10 where pokedex_id = 1115 and passive_id = 324; -- [confirmed] Crawdaunt / Leer: 1 -> 10 (versions saw: 1,13,10)
update pokedex_passives set level_learned = 7 where pokedex_id = 1014 and passive_id = 341; -- [confirmed] Crustle / Withdraw: 1 -> 7 (versions saw: 1,7)
update pokedex_passives set level_learned = 9 where pokedex_id = 586 and passive_id = 327; -- [confirmed] Cryogonal / Sharpen: 1 -> 9 (versions saw: 9,1)
update pokedex_passives set level_learned = 5 where pokedex_id = 567 and passive_id = 337; -- [confirmed] Cubchoo / Growl: 1 -> 5 (versions saw: 5,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 371 and passive_id = 337; -- [confirmed] Dartrix / Growl: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 4 where pokedex_id = 372 and passive_id = 337; -- [confirmed] Decidueye / Growl: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 4 where pokedex_id = 1298 and passive_id = 382; -- [confirmed] Deino / Focus energy: 1 -> 4 (versions saw: 4,1)
update pokedex_passives set level_learned = 11 where pokedex_id = 398 and passive_id = 323; -- [confirmed] Delphox / Howl: 1 -> 11 (versions saw: 11,1)
update pokedex_passives set level_learned = 3 where pokedex_id = 667 and passive_id = 337; -- [confirmed] Dewgong / Growl: 1 -> 3 (versions saw: 1,30,5,9,3,4)
update pokedex_passives set level_learned = 5 where pokedex_id = 421 and passive_id = 328; -- [confirmed] Dewott / Tail whip: 1 -> 5 (versions saw: 1,5)
update pokedex_passives set level_learned = 16 where pokedex_id = 1052 and passive_id = 373; -- [confirmed] Dhelmise / Growth: 1 -> 16 (versions saw: 1,16)
update pokedex_passives set level_learned = 43 where pokedex_id = 844 and passive_id = 331; -- [confirmed] Diggersby / Swords dance: 1 -> 43 (versions saw: 1,43)
update pokedex_passives set level_learned = 20 where pokedex_id = 779 and passive_id = 337; -- [confirmed] Dodrio / Growl: 1 -> 20 (versions saw: 1,20)
update pokedex_passives set level_learned = 20 where pokedex_id = 778 and passive_id = 337; -- [confirmed] Doduo / Growl: 1 -> 20 (versions saw: 20,1)
update pokedex_passives set level_learned = 9 where pokedex_id = 710 and passive_id = 336; -- [confirmed] Donphan / Defense curl: 1 -> 9 (versions saw: 9,1)
update pokedex_passives set level_learned = 18 where pokedex_id = 1073 and passive_id = 361; -- [confirmed] Doublade / Autotomize: 1 -> 18 (versions saw: 18,1)
update pokedex_passives set level_learned = 50 where pokedex_id = 1073 and passive_id = 331; -- [confirmed] Doublade / Swords dance: 1 -> 50 (versions saw: 1,50)
update pokedex_passives set level_learned = 20 where pokedex_id = 1255 and passive_id = 360; -- [confirmed] Dragonite / Agility: 1 -> 20 (versions saw: 1,20,38,25,21)
update pokedex_passives set level_learned = 30 where pokedex_id = 920 and passive_id = 329; -- [confirmed] Drapion / Hone claws: 1 -> 30 (versions saw: 48,30,1)
update pokedex_passives set level_learned = 6 where pokedex_id = 920 and passive_id = 324; -- [confirmed] Drapion / Leer: 1 -> 6 (versions saw: 1,6)
update pokedex_passives set level_learned = 13 where pokedex_id = 1043 and passive_id = 382; -- [confirmed] Drifblim / Focus energy: 1 -> 13 (versions saw: 14,13,1)
update pokedex_passives set level_learned = 12 where pokedex_id = 706 and passive_id = 360; -- [confirmed] Dugtrio / Agility: 1 -> 12 (versions saw: 1,12)
update pokedex_passives set level_learned = 4 where pokedex_id = 706 and passive_id = 337; -- [confirmed] Dugtrio / Growl: 1 -> 4 (versions saw: 1,15,5,4,8)
update pokedex_passives set level_learned = 4 where pokedex_id = 792 and passive_id = 336; -- [confirmed] Dunsparce / Defense curl: 1 -> 4 (versions saw: 5,4,1)
update pokedex_passives set level_learned = 46 where pokedex_id = 1021 and passive_id = 345; -- [confirmed] Durant / Iron defense: 1 -> 46 (versions saw: 56,1,46,52)
update pokedex_passives set level_learned = 40 where pokedex_id = 1021 and passive_id = 349; -- [confirmed] Durant / Metal sound: 1 -> 40 (versions saw: 66,1,56,40)
update pokedex_passives set level_learned = 9 where pokedex_id = 440 and passive_id = 337; -- [confirmed] Eevee / Growl: 1 -> 9 (versions saw: 16,15,9,1)
update pokedex_passives set level_learned = 3 where pokedex_id = 440 and passive_id = 328; -- [confirmed] Eevee / Tail whip: 1 -> 3 (versions saw: 31,1,3)
update pokedex_passives set level_learned = 4 where pokedex_id = 904 and passive_id = 324; -- [confirmed] Ekans / Leer: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 6 where pokedex_id = 483 and passive_id = 356; -- [confirmed] Electrode / Eerie impulse: 1 -> 6 (versions saw: 8,6,1)
update pokedex_passives set level_learned = 8 where pokedex_id = 483 and passive_id = 330; -- [confirmed] Electrode / Screech: 1 -> 8 (versions saw: 1,9,8,19,13,24)
update pokedex_passives set level_learned = 4 where pokedex_id = 1238 and passive_id = 337; -- [confirmed] Elgyem / Growl: 1 -> 4 (versions saw: 4,1)
update pokedex_passives set level_learned = 3 where pokedex_id = 395 and passive_id = 328; -- [confirmed] Emboar / Tail whip: 1 -> 3 (versions saw: 1,3)
update pokedex_passives set level_learned = 7 where pokedex_id = 700 and passive_id = 328; -- [confirmed] Emolga / Tail whip: 1 -> 7 (versions saw: 7,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 419 and passive_id = 337; -- [confirmed] Empoleon / Growl: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 4 where pokedex_id = 1016 and passive_id = 324; -- [confirmed] Escavalier / Leer: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 22 where pokedex_id = 718 and passive_id = 329; -- [confirmed] Excadrill / Hone claws: 1 -> 22 (versions saw: 22,1)
update pokedex_passives set level_learned = 11 where pokedex_id = 808 and passive_id = 323; -- [confirmed] Exploud / Howl: 1 -> 11 (versions saw: 1,15,11)
update pokedex_passives set level_learned = 5 where pokedex_id = 777 and passive_id = 324; -- [confirmed] Farfetchd / Leer: 1 -> 5 (versions saw: 7,13,11,1,5)
update pokedex_passives set level_learned = 11 where pokedex_id = 773 and passive_id = 382; -- [confirmed] Fearow / Focus energy: 1 -> 11 (versions saw: 32,1,11)
update pokedex_passives set level_learned = 3 where pokedex_id = 773 and passive_id = 337; -- [confirmed] Fearow / Growl: 1 -> 3 (versions saw: 1,3)
update pokedex_passives set level_learned = 4 where pokedex_id = 773 and passive_id = 324; -- [confirmed] Fearow / Leer: 1 -> 4 (versions saw: 1,9,7,5,4,8)
update pokedex_passives set level_learned = 30 where pokedex_id = 413 and passive_id = 360; -- [confirmed] Feraligatr / Agility: 1 -> 30 (versions saw: 30,1)
update pokedex_passives set level_learned = 5 where pokedex_id = 480 and passive_id = 337; -- [confirmed] Flaaffy / Growl: 1 -> 5 (versions saw: 1,5)
update pokedex_passives set level_learned = 3 where pokedex_id = 443 and passive_id = 328; -- [confirmed] Flareon / Tail whip: 1 -> 3 (versions saw: 37,1,3)
update pokedex_passives set level_learned = 4 where pokedex_id = 657 and passive_id = 337; -- [confirmed] Floatzel / Growl: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 32 where pokedex_id = 991 and passive_id = 361; -- [confirmed] Forretress / Autotomize: 1 -> 32 (versions saw: 32,0,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 1266 and passive_id = 324; -- [confirmed] Fraxure / Leer: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 4 where pokedex_id = 787 and passive_id = 336; -- [confirmed] Furret / Defense curl: 1 -> 4 (versions saw: 1,5,4)
update pokedex_passives set level_learned = 25 where pokedex_id = 611 and passive_id = 369; -- [confirmed] Gallade / Calm mind: 1 -> 25 (versions saw: 1,25)
update pokedex_passives set level_learned = 12 where pokedex_id = 1018 and passive_id = 366; -- [confirmed] Galvantula / String shot: 1 -> 12 (versions saw: 1,12)
update pokedex_passives set level_learned = 4 where pokedex_id = 1124 and passive_id = 338; -- [confirmed] Gastrodon / Harden: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 7 where pokedex_id = 1024 and passive_id = 330; -- [confirmed] Genesect / Screech: 1 -> 7 (versions saw: 1,7)
update pokedex_passives set level_learned = 6 where pokedex_id = 612 and passive_id = 336; -- [confirmed] Geodude / Defense curl: 1 -> 6 (versions saw: 11,6,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 617 and passive_id = 338; -- [confirmed] Gigalith / Harden: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 7 where pokedex_id = 552 and passive_id = 338; -- [confirmed] Gliscor / Harden: 1 -> 7 (versions saw: 1,9,7)
update pokedex_passives set level_learned = 4 where pokedex_id = 1150 and passive_id = 373; -- [confirmed] Gloom / Growth: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 9 where pokedex_id = 1188 and passive_id = 328; -- [confirmed] Gogoat / Tail whip: 1 -> 9 (versions saw: 9,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 1090 and passive_id = 328; -- [confirmed] Golduck / Tail whip: 1 -> 4 (versions saw: 1,28,5,4)
update pokedex_passives set level_learned = 6 where pokedex_id = 614 and passive_id = 336; -- [confirmed] Golem / Defense curl: 1 -> 6 (versions saw: 1,11,6)
update pokedex_passives set level_learned = 6 where pokedex_id = 614 and passive_id = 363; -- [confirmed] Golem / Rock polish: 1 -> 6 (versions saw: 1,8,6)
update pokedex_passives set level_learned = 4 where pokedex_id = 684 and passive_id = 336; -- [confirmed] Golett / Defense curl: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 10 where pokedex_id = 607 and passive_id = 351; -- [confirmed] Gothitelle / Fake tears: 1 -> 10 (versions saw: 1,10,28)
update pokedex_passives set level_learned = 7 where pokedex_id = 607 and passive_id = 379; -- [confirmed] Gothitelle / Tickle: 1 -> 7 (versions saw: 1,7)
update pokedex_passives set level_learned = 10 where pokedex_id = 606 and passive_id = 351; -- [confirmed] Gothorita / Fake tears: 1 -> 10 (versions saw: 1,10,28)
update pokedex_passives set level_learned = 7 where pokedex_id = 606 and passive_id = 379; -- [confirmed] Gothorita / Tickle: 1 -> 7 (versions saw: 1,7)
update pokedex_passives set level_learned = 8 where pokedex_id = 1319 and passive_id = 335; -- [confirmed] Granbull / Charm: 1 -> 8 (versions saw: 8,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 1319 and passive_id = 328; -- [confirmed] Granbull / Tail whip: 1 -> 4 (versions saw: 4,1)
update pokedex_passives set level_learned = 6 where pokedex_id = 613 and passive_id = 336; -- [confirmed] Graveler / Defense curl: 1 -> 6 (versions saw: 1,11,6)
update pokedex_passives set level_learned = 6 where pokedex_id = 613 and passive_id = 363; -- [confirmed] Graveler / Rock polish: 1 -> 6 (versions saw: 1,8,6)
update pokedex_passives set level_learned = 5 where pokedex_id = 362 and passive_id = 341; -- [confirmed] Grotle / Withdraw: 1 -> 5 (versions saw: 1,5)
update pokedex_passives set level_learned = 5 where pokedex_id = 714 and passive_id = 364; -- [confirmed] Groudon / Scary face: 1 -> 5 (versions saw: 5,1)
update pokedex_passives set level_learned = 7 where pokedex_id = 507 and passive_id = 324; -- [confirmed] Growlithe / Leer: 1 -> 7 (versions saw: 23,18,13,9,8,7,1)
update pokedex_passives set level_learned = 3 where pokedex_id = 850 and passive_id = 324; -- [confirmed] Gumshoos / Leer: 1 -> 3 (versions saw: 1,3)
update pokedex_passives set level_learned = 4 where pokedex_id = 879 and passive_id = 382; -- [confirmed] Gurdurr / Focus energy: 1 -> 4 (versions saw: 1,4,12)
update pokedex_passives set level_learned = 6 where pokedex_id = 681 and passive_id = 324; -- [confirmed] Gyarados / Leer: 1 -> 6 (versions saw: 1,32,30,26,21,6)
update pokedex_passives set level_learned = 20 where pokedex_id = 590 and passive_id = 335; -- [confirmed] Happiny / Charm: 1 -> 20 (versions saw: 1,20)
update pokedex_passives set level_learned = 4 where pokedex_id = 1267 and passive_id = 324; -- [confirmed] Haxorus / Leer: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 40 where pokedex_id = 528 and passive_id = 329; -- [confirmed] Heatmor / Hone claws: 1 -> 40 (versions saw: 1,40)
update pokedex_passives set level_learned = 20 where pokedex_id = 833 and passive_id = 380; -- [confirmed] Herdier / Work up: 1 -> 20 (versions saw: 20,1)
update pokedex_passives set level_learned = 6 where pokedex_id = 871 and passive_id = 360; -- [confirmed] Hitmonchan / Agility: 1 -> 6 (versions saw: 1,7,6,10,28)
update pokedex_passives set level_learned = 35 where pokedex_id = 871 and passive_id = 382; -- [confirmed] Hitmonchan / Focus energy: 1 -> 35 (versions saw: 35,1)
update pokedex_passives set level_learned = 21 where pokedex_id = 870 and passive_id = 382; -- [confirmed] Hitmonlee / Focus energy: 1 -> 21 (versions saw: 43,21,35,1)
update pokedex_passives set level_learned = 5 where pokedex_id = 870 and passive_id = 325; -- [confirmed] Hitmonlee / Meditate: 1 -> 5 (versions saw: 1,6,5)
update pokedex_passives set level_learned = 6 where pokedex_id = 873 and passive_id = 382; -- [confirmed] Hitmontop / Focus energy: 1 -> 6 (versions saw: 7,6,1)
update pokedex_passives set level_learned = 44 where pokedex_id = 1072 and passive_id = 331; -- [confirmed] Honedge / Swords dance: 1 -> 44 (versions saw: 1,44)
update pokedex_passives set level_learned = 8 where pokedex_id = 634 and passive_id = 324; -- [confirmed] Horsea / Leer: 1 -> 8 (versions saw: 24,15,8,9,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 469 and passive_id = 323; -- [confirmed] Houndoom / Howl: 1 -> 4 (versions saw: 1,7,4)
update pokedex_passives set level_learned = 60 where pokedex_id = 469 and passive_id = 350; -- [confirmed] Houndoom / Nasty plot: 1 -> 60 (versions saw: 60,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 1300 and passive_id = 382; -- [confirmed] Hydreigon / Focus energy: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 46 where pokedex_id = 1213 and passive_id = 350; -- [confirmed] Hypno / Nasty plot: 1 -> 46 (versions saw: 55,53,1,46,47)
update pokedex_passives set level_learned = 20 where pokedex_id = 593 and passive_id = 335; -- [confirmed] Igglybuff / Charm: 1 -> 20 (versions saw: 1,20)
update pokedex_passives set level_learned = 4 where pokedex_id = 401 and passive_id = 337; -- [confirmed] Incineroar / Growl: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 25 where pokedex_id = 392 and passive_id = 350; -- [confirmed] Infernape / Nasty plot: 1 -> 25 (versions saw: 1,25)
update pokedex_passives set level_learned = 3 where pokedex_id = 353 and passive_id = 337; -- [confirmed] Ivysaur / Growl: 1 -> 3 (versions saw: 1,4,3)
update pokedex_passives set level_learned = 28 where pokedex_id = 353 and passive_id = 373; -- [confirmed] Ivysaur / Growth: 1 -> 28 (versions saw: 38,28,39,1)
update pokedex_passives set level_learned = 3 where pokedex_id = 594 and passive_id = 336; -- [confirmed] JIgglypuff / Defense curl: 1 -> 3 (versions saw: 19,4,5,3,6,1)
update pokedex_passives set level_learned = 3 where pokedex_id = 442 and passive_id = 328; -- [confirmed] Jolteon / Tail whip: 1 -> 3 (versions saw: 37,1,3)
update pokedex_passives set level_learned = 12 where pokedex_id = 1017 and passive_id = 366; -- [confirmed] Joltik / String shot: 1 -> 12 (versions saw: 1,12)
update pokedex_passives set level_learned = 5 where pokedex_id = 688 and passive_id = 328; -- [confirmed] Jumpluff / Tail whip: 1 -> 5 (versions saw: 1,5,7,6)
update pokedex_passives set level_learned = 6 where pokedex_id = 941 and passive_id = 338; -- [confirmed] Kabuto / Harden: 1 -> 6 (versions saw: 1,6)
update pokedex_passives set level_learned = 6 where pokedex_id = 942 and passive_id = 338; -- [confirmed] Kabutops / Harden: 1 -> 6 (versions saw: 1,6)
update pokedex_passives set level_learned = 11 where pokedex_id = 942 and passive_id = 324; -- [confirmed] Kabutops / Leer: 1 -> 11 (versions saw: 46,19,1,11,12,20)
update pokedex_passives set level_learned = 7 where pokedex_id = 977 and passive_id = 338; -- [confirmed] Kakuna / Harden: 1 -> 7 (versions saw: 1,7,0)
update pokedex_passives set level_learned = 7 where pokedex_id = 781 and passive_id = 324; -- [confirmed] Kangaskhan / Leer: 1 -> 7 (versions saw: 41,7,1)
update pokedex_passives set level_learned = 10 where pokedex_id = 781 and passive_id = 328; -- [confirmed] Kangaskhan / Tail whip: 1 -> 10 (versions saw: 31,19,13,10,11,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 1015 and passive_id = 324; -- [confirmed] Karrablast / Leer: 1 -> 4 (versions saw: 4,1)
update pokedex_passives set level_learned = 8 where pokedex_id = 636 and passive_id = 324; -- [confirmed] Kingdra / Leer: 1 -> 8 (versions saw: 1,15,8,9)
update pokedex_passives set level_learned = 11 where pokedex_id = 1098 and passive_id = 338; -- [confirmed] Kingler / Harden: 1 -> 11 (versions saw: 49,16,1,11,14)
update pokedex_passives set level_learned = 5 where pokedex_id = 1098 and passive_id = 324; -- [confirmed] Kingler / Leer: 1 -> 5 (versions saw: 1,5,9)
update pokedex_passives set level_learned = 5 where pokedex_id = 1097 and passive_id = 324; -- [confirmed] Krabby / Leer: 1 -> 5 (versions saw: 1,5,9)
update pokedex_passives set level_learned = 5 where pokedex_id = 1122 and passive_id = 364; -- [confirmed] Kyogre / Scary face: 1 -> 5 (versions saw: 5,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 627 and passive_id = 338; -- [confirmed] Lairon / Harden: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 6 where pokedex_id = 672 and passive_id = 337; -- [confirmed] Lapras / Growl: 1 -> 6 (versions saw: 1,6)
update pokedex_passives set level_learned = 7 where pokedex_id = 1259 and passive_id = 335; -- [confirmed] Latias / Charm: 1 -> 7 (versions saw: 50,55,1,7)
update pokedex_passives set level_learned = 7 where pokedex_id = 1260 and passive_id = 372; -- [confirmed] Latios / Dragon dance: 1 -> 7 (versions saw: 50,55,1,7)
update pokedex_passives set level_learned = 9 where pokedex_id = 827 and passive_id = 336; -- [confirmed] Lickilicky / Defense curl: 1 -> 9 (versions saw: 9,1)
update pokedex_passives set level_learned = 9 where pokedex_id = 780 and passive_id = 336; -- [confirmed] Lickitung / Defense curl: 1 -> 9 (versions saw: 23,13,12,9,1)
update pokedex_passives set level_learned = 3 where pokedex_id = 1289 and passive_id = 337; -- [confirmed] Liepard / Growl: 1 -> 3 (versions saw: 1,3)
update pokedex_passives set level_learned = 28 where pokedex_id = 1180 and passive_id = 375; -- [confirmed] Lilligant / Quiver dance: 1 -> 28 (versions saw: 28,1)
update pokedex_passives set level_learned = 5 where pokedex_id = 800 and passive_id = 328; -- [confirmed] Linoone / Tail whip: 1 -> 5 (versions saw: 1,5)
update pokedex_passives set level_learned = 4 where pokedex_id = 399 and passive_id = 337; -- [confirmed] Litten / Growl: 1 -> 4 (versions saw: 4,1)
update pokedex_passives set level_learned = 3 where pokedex_id = 638 and passive_id = 337; -- [confirmed] Lombre / Growl: 1 -> 3 (versions saw: 3,1)
update pokedex_passives set level_learned = 3 where pokedex_id = 637 and passive_id = 337; -- [confirmed] Lotad / Growl: 1 -> 3 (versions saw: 3,1)
update pokedex_passives set level_learned = 11 where pokedex_id = 807 and passive_id = 323; -- [confirmed] Loudred / Howl: 1 -> 11 (versions saw: 1,15,11)
update pokedex_passives set level_learned = 16 where pokedex_id = 493 and passive_id = 380; -- [confirmed] Lucario / Work up: 1 -> 16 (versions saw: 42,1,16)
update pokedex_passives set level_learned = 14 where pokedex_id = 1190 and passive_id = 373; -- [confirmed] Lurantis / Growth: 1 -> 14 (versions saw: 1,14)
update pokedex_passives set level_learned = 4 where pokedex_id = 1121 and passive_id = 335; -- [confirmed] Luvdisc / Charm: 1 -> 4 (versions saw: 4,1)
update pokedex_passives set level_learned = 5 where pokedex_id = 738 and passive_id = 324; -- [confirmed] Luxio / Leer: 1 -> 5 (versions saw: 1,5)
update pokedex_passives set level_learned = 5 where pokedex_id = 739 and passive_id = 324; -- [confirmed] Luxray / Leer: 1 -> 5 (versions saw: 1,5)
update pokedex_passives set level_learned = 3 where pokedex_id = 869 and passive_id = 382; -- [confirmed] Machamp / Focus energy: 1 -> 3 (versions saw: 36,1,8,7,3,4)
update pokedex_passives set level_learned = 25 where pokedex_id = 869 and passive_id = 324; -- [confirmed] Machamp / Leer: 1 -> 25 (versions saw: 1,25)
update pokedex_passives set level_learned = 3 where pokedex_id = 868 and passive_id = 382; -- [confirmed] Machoke / Focus energy: 1 -> 3 (versions saw: 36,1,8,7,3,4)
update pokedex_passives set level_learned = 25 where pokedex_id = 868 and passive_id = 324; -- [confirmed] Machoke / Leer: 1 -> 25 (versions saw: 1,25)
update pokedex_passives set level_learned = 25 where pokedex_id = 867 and passive_id = 324; -- [confirmed] Machop / Leer: 1 -> 25 (versions saw: 25,1)
update pokedex_passives set level_learned = 7 where pokedex_id = 500 and passive_id = 324; -- [confirmed] Magby / Leer: 1 -> 7 (versions saw: 7,1)
update pokedex_passives set level_learned = 6 where pokedex_id = 1076 and passive_id = 336; -- [confirmed] Magearna / Defense curl: 1 -> 6 (versions saw: 1,6)
update pokedex_passives set level_learned = 48 where pokedex_id = 1076 and passive_id = 377; -- [confirmed] Magearna / Shift gear: 1 -> 48 (versions saw: 1,48)
update pokedex_passives set level_learned = 7 where pokedex_id = 501 and passive_id = 324; -- [confirmed] Magmar / Leer: 1 -> 7 (versions saw: 36,1,7)
update pokedex_passives set level_learned = 25 where pokedex_id = 476 and passive_id = 349; -- [confirmed] Magnemite / Metal sound: 1 -> 25 (versions saw: 1,29,25,40)
update pokedex_passives set level_learned = 25 where pokedex_id = 477 and passive_id = 349; -- [confirmed] Magneton / Metal sound: 1 -> 25 (versions saw: 1,29,25,46)
update pokedex_passives set level_learned = 25 where pokedex_id = 478 and passive_id = 349; -- [confirmed] Magnezone / Metal sound: 1 -> 25 (versions saw: 1,29,25,46)
update pokedex_passives set level_learned = 58 where pokedex_id = 561 and passive_id = 364; -- [confirmed] Mamoswine / Scary face: 1 -> 58 (versions saw: 65,58,1)
update pokedex_passives set level_learned = 7 where pokedex_id = 702 and passive_id = 323; -- [confirmed] Manectric / Howl: 1 -> 7 (versions saw: 1,12,7)
update pokedex_passives set level_learned = 4 where pokedex_id = 702 and passive_id = 324; -- [confirmed] Manectric / Leer: 1 -> 4 (versions saw: 1,9,4)
update pokedex_passives set level_learned = 5 where pokedex_id = 865 and passive_id = 382; -- [confirmed] Mankey / Focus energy: 1 -> 5 (versions saw: 27,21,1,5)
update pokedex_passives set level_learned = 55 where pokedex_id = 1181 and passive_id = 347; -- [confirmed] Maractus / Cotton guard: 1 -> 55 (versions saw: 55,1,60)
update pokedex_passives set level_learned = 5 where pokedex_id = 479 and passive_id = 337; -- [confirmed] Mareep / Growl: 1 -> 5 (versions saw: 1,5)
update pokedex_passives set level_learned = 2 where pokedex_id = 632 and passive_id = 336; -- [confirmed] Marill / Defense curl: 1 -> 2 (versions saw: 3,2,10,1)
update pokedex_passives set level_learned = 2 where pokedex_id = 632 and passive_id = 328; -- [confirmed] Marill / Tail whip: 1 -> 2 (versions saw: 6,7,2,1)
update pokedex_passives set level_learned = 17 where pokedex_id = 708 and passive_id = 382; -- [confirmed] Marowak / Focus energy: 1 -> 17 (versions saw: 1,33,21,17,24,36)
update pokedex_passives set level_learned = 6 where pokedex_id = 708 and passive_id = 324; -- [confirmed] Marowak / Leer: 1 -> 6 (versions saw: 1,25,17,13,6)
update pokedex_passives set level_learned = 2 where pokedex_id = 708 and passive_id = 328; -- [confirmed] Marowak / Tail whip: 1 -> 2 (versions saw: 1,13,5,3,2)
update pokedex_passives set level_learned = 52 where pokedex_id = 1000 and passive_id = 375; -- [confirmed] Masquerain / Quiver dance: 1 -> 52 (versions saw: 68,1,52)
update pokedex_passives set level_learned = 4 where pokedex_id = 877 and passive_id = 325; -- [confirmed] Medicham / Meditate: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 9 where pokedex_id = 1078 and passive_id = 328; -- [confirmed] Melmetal / Tail whip: 1 -> 9 (versions saw: 1,9)
update pokedex_passives set level_learned = 24 where pokedex_id = 1064 and passive_id = 364; -- [confirmed] Metagross / Scary face: 1 -> 24 (versions saw: 1,26,24,35,42)
update pokedex_passives set level_learned = 7 where pokedex_id = 453 and passive_id = 338; -- [confirmed] Metapod / Harden: 0 -> 7 (versions saw: 1,7,0)
update pokedex_passives set level_learned = 8 where pokedex_id = 1214 and passive_id = 343; -- [confirmed] Mewtwo / Barrier: 1 -> 8 (versions saw: 63,11,8,1,64,77)
update pokedex_passives set level_learned = 5 where pokedex_id = 884 and passive_id = 325; -- [confirmed] Mienshao / Meditate: 1 -> 5 (versions saw: 1,5)
update pokedex_passives set level_learned = 4 where pokedex_id = 1285 and passive_id = 323; -- [confirmed] Mightyena / Howl: 1 -> 4 (versions saw: 1,5,4,13)
update pokedex_passives set level_learned = 3 where pokedex_id = 798 and passive_id = 337; -- [confirmed] Miltank / Growl: 1 -> 3 (versions saw: 4,3,1)
update pokedex_passives set level_learned = 46 where pokedex_id = 736 and passive_id = 350; -- [confirmed] Minun / Nasty plot: 1 -> 46 (versions saw: 51,56,1,46)
update pokedex_passives set level_learned = 25 where pokedex_id = 391 and passive_id = 350; -- [confirmed] Monferno / Nasty plot: 1 -> 25 (versions saw: 1,25)
update pokedex_passives set level_learned = 50 where pokedex_id = 1009 and passive_id = 375; -- [confirmed] Mothim / Quiver dance: 1 -> 50 (versions saw: 50,0,1)
update pokedex_passives set level_learned = 29 where pokedex_id = 724 and passive_id = 345; -- [confirmed] Mudsdale / Iron defense: 1 -> 29 (versions saw: 29,1)
update pokedex_passives set level_learned = 8 where pokedex_id = 724 and passive_id = 376; -- [confirmed] Mudsdale / Rototiller: 1 -> 8 (versions saw: 1,8)
update pokedex_passives set level_learned = 4 where pokedex_id = 911 and passive_id = 338; -- [confirmed] Muk / Harden: 1 -> 4 (versions saw: 45,1,33,4,6)
update pokedex_passives set level_learned = 3 where pokedex_id = 906 and passive_id = 328; -- [confirmed] Nidorina / Tail whip: 1 -> 3 (versions saw: 23,27,8,7,1,3)
update pokedex_passives set level_learned = 3 where pokedex_id = 908 and passive_id = 382; -- [confirmed] Nidorino / Focus energy: 1 -> 3 (versions saw: 23,27,8,7,1,3)
update pokedex_passives set level_learned = 10 where pokedex_id = 967 and passive_id = 379; -- [confirmed] Nihilego / Tickle: 1 -> 10 (versions saw: 1,10)
update pokedex_passives set level_learned = 5 where pokedex_id = 1001 and passive_id = 338; -- [confirmed] Nincada / Harden: 1 -> 5 (versions saw: 1,5)
update pokedex_passives set level_learned = 9 where pokedex_id = 524 and passive_id = 350; -- [confirmed] Ninetales / Nasty plot: 1 -> 9 (versions saw: 1,9)
update pokedex_passives set level_learned = 20 where pokedex_id = 1002 and passive_id = 330; -- [confirmed] Ninjask / Screech: 1 -> 20 (versions saw: 20,0,1)
update pokedex_passives set level_learned = 40 where pokedex_id = 899 and passive_id = 330; -- [confirmed] Noibat / Screech: 1 -> 40 (versions saw: 1,40)
update pokedex_passives set level_learned = 40 where pokedex_id = 900 and passive_id = 330; -- [confirmed] Noivern / Screech: 1 -> 40 (versions saw: 1,40)
update pokedex_passives set level_learned = 3 where pokedex_id = 1162 and passive_id = 338; -- [confirmed] Nuzleaf / Harden: 1 -> 3 (versions saw: 3,1)
update pokedex_passives set level_learned = 22 where pokedex_id = 1107 and passive_id = 382; -- [confirmed] Octillery / Focus energy: 1 -> 22 (versions saw: 38,23,22,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 1149 and passive_id = 373; -- [confirmed] Oddish / Growth: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 4 where pokedex_id = 939 and passive_id = 341; -- [confirmed] Omanyte / Withdraw: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 11 where pokedex_id = 940 and passive_id = 324; -- [confirmed] Omastar / Leer: 1 -> 11 (versions saw: 39,31,19,1,11,20)
update pokedex_passives set level_learned = 4 where pokedex_id = 940 and passive_id = 341; -- [confirmed] Omastar / Withdraw: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 19 where pokedex_id = 629 and passive_id = 338; -- [confirmed] Onix / Harden: 1 -> 19 (versions saw: 43,23,21,19,1)
update pokedex_passives set level_learned = 6 where pokedex_id = 629 and passive_id = 330; -- [confirmed] Onix / Screech: 1 -> 6 (versions saw: 1,6,31,15,24)
update pokedex_passives set level_learned = 10 where pokedex_id = 886 and passive_id = 380; -- [confirmed] Pangoro / Work up: 1 -> 10 (versions saw: 10,1,20)
update pokedex_passives set level_learned = 4 where pokedex_id = 496 and passive_id = 324; -- [confirmed] Passimian / Leer: 1 -> 4 (versions saw: 4,1)
update pokedex_passives set level_learned = 6 where pokedex_id = 1294 and passive_id = 324; -- [confirmed] Pawniard / Leer: 1 -> 6 (versions saw: 6,1)
update pokedex_passives set level_learned = 44 where pokedex_id = 1111 and passive_id = 367; -- [confirmed] Pelipper / Tailwind: 1 -> 44 (versions saw: 50,52,1,44)
update pokedex_passives set level_learned = 17 where pokedex_id = 776 and passive_id = 330; -- [confirmed] Persian / Screech: 1 -> 17 (versions saw: 1,24,38,34,17,23,36)
update pokedex_passives set level_learned = 4 where pokedex_id = 1179 and passive_id = 373; -- [confirmed] Petilil / Growth: 1 -> 4 (versions saw: 4,1)
update pokedex_passives set level_learned = 9 where pokedex_id = 709 and passive_id = 336; -- [confirmed] Phanpy / Defense curl: 1 -> 9 (versions saw: 9,1)
update pokedex_passives set level_learned = 5 where pokedex_id = 1030 and passive_id = 324; -- [confirmed] Pheromosa / Leer: 1 -> 5 (versions saw: 1,5)
update pokedex_passives set level_learned = 65 where pokedex_id = 1030 and passive_id = 375; -- [confirmed] Pheromosa / Quiver dance: 1 -> 65 (versions saw: 1,65)
update pokedex_passives set level_learned = 20 where pokedex_id = 436 and passive_id = 335; -- [confirmed] Pichu / Charm: 1 -> 20 (versions saw: 1,20)
update pokedex_passives set level_learned = 5 where pokedex_id = 436 and passive_id = 328; -- [confirmed] Pichu / Tail whip: 1 -> 5 (versions saw: 6,5,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 835 and passive_id = 337; -- [confirmed] Pidove / Growl: 1 -> 4 (versions saw: 4,1)
update pokedex_passives set level_learned = 3 where pokedex_id = 394 and passive_id = 328; -- [confirmed] Pignite / Tail whip: 1 -> 3 (versions saw: 1,3)
update pokedex_passives set level_learned = 5 where pokedex_id = 437 and passive_id = 337; -- [confirmed] Pikachu / Growl: 1 -> 5 (versions saw: 1,5)
update pokedex_passives set level_learned = 7 where pokedex_id = 437 and passive_id = 340; -- [confirmed] Pikachu / Play nice: 1 -> 7 (versions saw: 7,1)
update pokedex_passives set level_learned = 3 where pokedex_id = 437 and passive_id = 328; -- [confirmed] Pikachu / Tail whip: 1 -> 3 (versions saw: 6,5,1,3)
update pokedex_passives set level_learned = 4 where pokedex_id = 984 and passive_id = 382; -- [confirmed] Pinsir / Focus energy: 1 -> 4 (versions saw: 36,7,1,4)
update pokedex_passives set level_learned = 11 where pokedex_id = 984 and passive_id = 338; -- [confirmed] Pinsir / Harden: 1 -> 11 (versions saw: 43,25,19,13,11,12,1)
update pokedex_passives set level_learned = 46 where pokedex_id = 735 and passive_id = 350; -- [confirmed] Plusle / Nasty plot: 1 -> 46 (versions saw: 51,56,1,46)
update pokedex_passives set level_learned = 21 where pokedex_id = 735 and passive_id = 340; -- [confirmed] Plusle / Play nice: 1 -> 21 (versions saw: 1,21)
update pokedex_passives set level_learned = 4 where pokedex_id = 517 and passive_id = 337; -- [confirmed] Ponyta / Growl: 1 -> 4 (versions saw: 35,4,5,7,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 517 and passive_id = 328; -- [confirmed] Ponyta / Tail whip: 1 -> 4 (versions saw: 30,8,9,10,6,4,1,5)
update pokedex_passives set level_learned = 4 where pokedex_id = 427 and passive_id = 337; -- [confirmed] Popplio / Growl: 1 -> 4 (versions saw: 4,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 784 and passive_id = 327; -- [confirmed] Porygon / Sharpen: 1 -> 4 (versions saw: 1,24,4)
update pokedex_passives set level_learned = 24 where pokedex_id = 795 and passive_id = 336; -- [confirmed] Porygon2 / Defense curl: 1 -> 24 (versions saw: 24,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 429 and passive_id = 337; -- [confirmed] Primarina / Growl: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 5 where pokedex_id = 866 and passive_id = 382; -- [confirmed] Primeape / Focus energy: 1 -> 5 (versions saw: 27,21,1,5)
update pokedex_passives set level_learned = 4 where pokedex_id = 418 and passive_id = 337; -- [confirmed] Prinplup / Growl: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 4 where pokedex_id = 957 and passive_id = 345; -- [confirmed] Probopass / Iron defense: 1 -> 4 (versions saw: 1,7,4,18)
update pokedex_passives set level_learned = 4 where pokedex_id = 1089 and passive_id = 328; -- [confirmed] Psyduck / Tail whip: 1 -> 4 (versions saw: 28,5,4,1)
update pokedex_passives set level_learned = 10 where pokedex_id = 945 and passive_id = 330; -- [confirmed] Pupitar / Screech: 1 -> 10 (versions saw: 1,15,10,21)
update pokedex_passives set level_learned = 3 where pokedex_id = 1288 and passive_id = 337; -- [confirmed] Purrloin / Growl: 1 -> 3 (versions saw: 3,1)
update pokedex_passives set level_learned = 8 where pokedex_id = 824 and passive_id = 337; -- [confirmed] Purugly / Growl: 1 -> 8 (versions saw: 1,8)
update pokedex_passives set level_learned = 6 where pokedex_id = 954 and passive_id = 382; -- [confirmed] Rampardos / Focus energy: 1 -> 6 (versions saw: 6,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 518 and passive_id = 337; -- [confirmed] Rapidash / Growl: 1 -> 4 (versions saw: 1,35,4,5,7)
update pokedex_passives set level_learned = 4 where pokedex_id = 518 and passive_id = 328; -- [confirmed] Rapidash / Tail whip: 1 -> 4 (versions saw: 1,30,8,9,10,6,4)
update pokedex_passives set level_learned = 7 where pokedex_id = 771 and passive_id = 382; -- [confirmed] Raticate / Focus energy: 1 -> 7 (versions saw: 27,1,7,9)
update pokedex_passives set level_learned = 20 where pokedex_id = 771 and passive_id = 364; -- [confirmed] Raticate / Scary face: 1 -> 20 (versions saw: 20,0,1)
update pokedex_passives set level_learned = 3 where pokedex_id = 771 and passive_id = 328; -- [confirmed] Raticate / Tail whip: 1 -> 3 (versions saw: 1,3)
update pokedex_passives set level_learned = 3 where pokedex_id = 770 and passive_id = 328; -- [confirmed] Rattata / Tail whip: 1 -> 3 (versions saw: 1,3)
update pokedex_passives set level_learned = 5 where pokedex_id = 1261 and passive_id = 364; -- [confirmed] Rayquaza / Scary face: 1 -> 5 (versions saw: 5,1)
update pokedex_passives set level_learned = 9 where pokedex_id = 547 and passive_id = 364; -- [confirmed] Rhydon / Scary face: 1 -> 9 (versions saw: 31,24,21,19,1,9,20)
update pokedex_passives set level_learned = 35 where pokedex_id = 547 and passive_id = 328; -- [confirmed] Rhydon / Tail whip: 1 -> 35 (versions saw: 1,35)
update pokedex_passives set level_learned = 35 where pokedex_id = 546 and passive_id = 328; -- [confirmed] Rhyhorn / Tail whip: 1 -> 35 (versions saw: 35,1)
update pokedex_passives set level_learned = 9 where pokedex_id = 548 and passive_id = 364; -- [confirmed] Rhyperior / Scary face: 1 -> 9 (versions saw: 21,19,1,9,20)
update pokedex_passives set level_learned = 4 where pokedex_id = 1166 and passive_id = 373; -- [confirmed] Roselia / Growth: 1 -> 4 (versions saw: 5,4,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 370 and passive_id = 337; -- [confirmed] Rowlet / Growl: 1 -> 4 (versions saw: 4,1)
update pokedex_passives set level_learned = 7 where pokedex_id = 1258 and passive_id = 324; -- [confirmed] Salamence / Leer: 1 -> 7 (versions saw: 1,9,10,7)
update pokedex_passives set level_learned = 5 where pokedex_id = 422 and passive_id = 328; -- [confirmed] Samurott / Tail whip: 1 -> 5 (versions saw: 1,5)
update pokedex_passives set level_learned = 3 where pokedex_id = 703 and passive_id = 336; -- [confirmed] Sandshrew / Defense curl: 1 -> 3 (versions saw: 6,3,1)
update pokedex_passives set level_learned = 3 where pokedex_id = 704 and passive_id = 336; -- [confirmed] Sandslash / Defense curl: 1 -> 3 (versions saw: 1,6,3)
update pokedex_passives set level_learned = 5 where pokedex_id = 882 and passive_id = 382; -- [confirmed] Sawk / Focus energy: 1 -> 5 (versions saw: 9,1,5)
update pokedex_passives set level_learned = 4 where pokedex_id = 597 and passive_id = 337; -- [confirmed] Sawsbuck / Growl: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 17 where pokedex_id = 992 and passive_id = 360; -- [confirmed] Scizor / Agility: 1 -> 17 (versions saw: 24,21,17,1)
update pokedex_passives set level_learned = 8 where pokedex_id = 466 and passive_id = 330; -- [confirmed] Scolipede / Screech: 1 -> 8 (versions saw: 1,8,16)
update pokedex_passives set level_learned = 17 where pokedex_id = 983 and passive_id = 324; -- [confirmed] Scyther / Leer: 1 -> 17 (versions saw: 17,1)
update pokedex_passives set level_learned = 8 where pokedex_id = 635 and passive_id = 324; -- [confirmed] Seadra / Leer: 1 -> 8 (versions saw: 24,1,15,8,9)
update pokedex_passives set level_learned = 3 where pokedex_id = 1161 and passive_id = 338; -- [confirmed] Seedot / Harden: 1 -> 3 (versions saw: 3,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 366 and passive_id = 324; -- [confirmed] Serperior / Leer: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 4 where pokedex_id = 365 and passive_id = 324; -- [confirmed] Servine / Leer: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 8 where pokedex_id = 659 and passive_id = 382; -- [confirmed] Sharpedo / Focus energy: 1 -> 8 (versions saw: 1,13,8)
update pokedex_passives set level_learned = 7 where pokedex_id = 1257 and passive_id = 324; -- [confirmed] Shelgon / Leer: 1 -> 7 (versions saw: 1,9,10,7)
update pokedex_passives set level_learned = 4 where pokedex_id = 1095 and passive_id = 341; -- [confirmed] Shellder / Withdraw: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 5 where pokedex_id = 737 and passive_id = 324; -- [confirmed] Shinx / Leer: 1 -> 5 (versions saw: 5,1)
update pokedex_passives set level_learned = 7 where pokedex_id = 995 and passive_id = 338; -- [confirmed] Silcoon / Harden: 1 -> 7 (versions saw: 1,7,0)
update pokedex_passives set level_learned = 30 where pokedex_id = 853 and passive_id = 364; -- [confirmed] Silvally / Scary face: 1 -> 30 (versions saw: 30,1)
update pokedex_passives set level_learned = 5 where pokedex_id = 687 and passive_id = 328; -- [confirmed] Skiploom / Tail whip: 1 -> 5 (versions saw: 1,5,7,6)
update pokedex_passives set level_learned = 3 where pokedex_id = 809 and passive_id = 328; -- [confirmed] Skitty / Tail whip: 1 -> 3 (versions saw: 3,1)
update pokedex_passives set level_learned = 6 where pokedex_id = 919 and passive_id = 324; -- [confirmed] Skorupi / Leer: 1 -> 6 (versions saw: 6,1)
update pokedex_passives set level_learned = 15 where pokedex_id = 918 and passive_id = 382; -- [confirmed] Skuntank / Focus energy: 1 -> 15 (versions saw: 1,15)
update pokedex_passives set level_learned = 7 where pokedex_id = 918 and passive_id = 330; -- [confirmed] Skuntank / Screech: 1 -> 7 (versions saw: 7,1,24)
update pokedex_passives set level_learned = 5 where pokedex_id = 1094 and passive_id = 337; -- [confirmed] Slowbro / Growl: 1 -> 5 (versions saw: 27,1,6,5)
update pokedex_passives set level_learned = 37 where pokedex_id = 1094 and passive_id = 341; -- [confirmed] Slowbro / Withdraw: 1 -> 37 (versions saw: 37,0,1)
update pokedex_passives set level_learned = 5 where pokedex_id = 1103 and passive_id = 337; -- [confirmed] Slowking / Growl: 1 -> 5 (versions saw: 6,5,1)
update pokedex_passives set level_learned = 36 where pokedex_id = 1103 and passive_id = 350; -- [confirmed] Slowking / Nasty plot: 1 -> 36 (versions saw: 39,36,1)
update pokedex_passives set level_learned = 8 where pokedex_id = 1327 and passive_id = 340; -- [confirmed] Slurpuff / Play nice: 1 -> 8 (versions saw: 8,1)
update pokedex_passives set level_learned = 5 where pokedex_id = 785 and passive_id = 354; -- [confirmed] Snorlax / Amnesia: 1 -> 5 (versions saw: 1,8,6,5,9,45,36)
update pokedex_passives set level_learned = 4 where pokedex_id = 785 and passive_id = 336; -- [confirmed] Snorlax / Defense curl: 1 -> 4 (versions saw: 15,10,9,4,6,1)
update pokedex_passives set level_learned = 39 where pokedex_id = 785 and passive_id = 330; -- [confirmed] Snorlax / Screech: 1 -> 39 (versions saw: 39,1)
update pokedex_passives set level_learned = 5 where pokedex_id = 583 and passive_id = 324; -- [confirmed] Snorunt / Leer: 1 -> 5 (versions saw: 1,5)
update pokedex_passives set level_learned = 8 where pokedex_id = 1318 and passive_id = 335; -- [confirmed] Snubbull / Charm: 1 -> 8 (versions saw: 8,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 1318 and passive_id = 328; -- [confirmed] Snubbull / Tail whip: 1 -> 4 (versions saw: 4,1)
update pokedex_passives set level_learned = 3 where pokedex_id = 772 and passive_id = 337; -- [confirmed] Spearow / Growl: 1 -> 3 (versions saw: 1,3)
update pokedex_passives set level_learned = 4 where pokedex_id = 556 and passive_id = 337; -- [confirmed] Spheal / Growl: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 4 where pokedex_id = 408 and passive_id = 328; -- [confirmed] Squirtle / Tail whip: 1 -> 4 (versions saw: 1,4,5)
update pokedex_passives set level_learned = 22 where pokedex_id = 1101 and passive_id = 338; -- [confirmed] Staryu / Harden: 1 -> 22 (versions saw: 22,1)
update pokedex_passives set level_learned = 19 where pokedex_id = 630 and passive_id = 338; -- [confirmed] Steelix / Harden: 1 -> 19 (versions saw: 23,21,19,1)
update pokedex_passives set level_learned = 30 where pokedex_id = 630 and passive_id = 363; -- [confirmed] Steelix / Rock polish: 1 -> 30 (versions saw: 30,1)
update pokedex_passives set level_learned = 6 where pokedex_id = 630 and passive_id = 330; -- [confirmed] Steelix / Screech: 1 -> 6 (versions saw: 1,6,31,24)
update pokedex_passives set level_learned = 5 where pokedex_id = 1194 and passive_id = 340; -- [confirmed] Steenee / Play nice: 1 -> 5 (versions saw: 1,5)
update pokedex_passives set level_learned = 20 where pokedex_id = 834 and passive_id = 380; -- [confirmed] Stoutland / Work up: 1 -> 20 (versions saw: 20,1)
update pokedex_passives set level_learned = 15 where pokedex_id = 917 and passive_id = 382; -- [confirmed] Stunky / Focus energy: 1 -> 15 (versions saw: 1,15)
update pokedex_passives set level_learned = 36 where pokedex_id = 1109 and passive_id = 367; -- [confirmed] Suicune / Tailwind: 1 -> 36 (versions saw: 57,1,36)
update pokedex_passives set level_learned = 4 where pokedex_id = 1160 and passive_id = 373; -- [confirmed] Sunflora / Growth: 1 -> 4 (versions saw: 4,6,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 1159 and passive_id = 373; -- [confirmed] Sunkern / Growth: 1 -> 4 (versions saw: 4,6,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 802 and passive_id = 382; -- [confirmed] Swellow / Focus energy: 1 -> 4 (versions saw: 1,4,5)
update pokedex_passives set level_learned = 12 where pokedex_id = 1174 and passive_id = 373; -- [confirmed] Tangrowth / Growth: 1 -> 12 (versions saw: 12,20,1)
update pokedex_passives set level_learned = 3 where pokedex_id = 782 and passive_id = 328; -- [confirmed] Tauros / Tail whip: 1 -> 3 (versions saw: 28,4,1,3,6)
update pokedex_passives set level_learned = 19 where pokedex_id = 793 and passive_id = 351; -- [confirmed] Teddiursa / Fake tears: 1 -> 19 (versions saw: 19,1)
update pokedex_passives set level_learned = 49 where pokedex_id = 960 and passive_id = 380; -- [confirmed] Terrakion / Work up: 1 -> 49 (versions saw: 61,1,49)
update pokedex_passives set level_learned = 5 where pokedex_id = 881 and passive_id = 382; -- [confirmed] Throh / Focus energy: 1 -> 5 (versions saw: 9,1,5)
update pokedex_passives set level_learned = 12 where pokedex_id = 1316 and passive_id = 335; -- [confirmed] Togepi / Charm: 1 -> 12 (versions saw: 1,12)
update pokedex_passives set level_learned = 12 where pokedex_id = 1317 and passive_id = 335; -- [confirmed] Togetic / Charm: 1 -> 12 (versions saw: 1,12)
update pokedex_passives set level_learned = 4 where pokedex_id = 400 and passive_id = 337; -- [confirmed] Torracat / Growl: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 5 where pokedex_id = 363 and passive_id = 341; -- [confirmed] Torterra / Withdraw: 1 -> 5 (versions saw: 1,5)
update pokedex_passives set level_learned = 3 where pokedex_id = 848 and passive_id = 337; -- [confirmed] Toucannon / Growl: 1 -> 3 (versions saw: 1,3)
update pokedex_passives set level_learned = 4 where pokedex_id = 836 and passive_id = 337; -- [confirmed] Tranquill / Growl: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 8 where pokedex_id = 836 and passive_id = 324; -- [confirmed] Tranquill / Leer: 1 -> 8 (versions saw: 1,8)
update pokedex_passives set level_learned = 8 where pokedex_id = 1049 and passive_id = 373; -- [confirmed] Trevenant / Growth: 1 -> 8 (versions saw: 8,1,24)
update pokedex_passives set level_learned = 7 where pokedex_id = 545 and passive_id = 373; -- [confirmed] Tropius / Growth: 1 -> 7 (versions saw: 7,1)
update pokedex_passives set level_learned = 3 where pokedex_id = 847 and passive_id = 337; -- [confirmed] Trumbeak / Growl: 1 -> 3 (versions saw: 1,3)
update pokedex_passives set level_learned = 10 where pokedex_id = 946 and passive_id = 330; -- [confirmed] Tyranitar / Screech: 1 -> 10 (versions saw: 1,15,10,21)
update pokedex_passives set level_learned = 4 where pokedex_id = 837 and passive_id = 337; -- [confirmed] Unfezant / Growl: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 8 where pokedex_id = 837 and passive_id = 324; -- [confirmed] Unfezant / Leer: 1 -> 8 (versions saw: 1,8)
update pokedex_passives set level_learned = 19 where pokedex_id = 794 and passive_id = 351; -- [confirmed] Ursaring / Fake tears: 1 -> 19 (versions saw: 19,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 563 and passive_id = 338; -- [confirmed] Vanillish / Harden: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 4 where pokedex_id = 562 and passive_id = 338; -- [confirmed] Vanillite / Harden: 1 -> 4 (versions saw: 4,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 564 and passive_id = 338; -- [confirmed] Vanilluxe / Harden: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 3 where pokedex_id = 441 and passive_id = 328; -- [confirmed] Vaporeon / Tail whip: 1 -> 3 (versions saw: 37,1,3)
update pokedex_passives set level_learned = 55 where pokedex_id = 982 and passive_id = 375; -- [confirmed] Venomoth / Quiver dance: 1 -> 55 (versions saw: 63,1,55)
update pokedex_passives set level_learned = 3 where pokedex_id = 354 and passive_id = 337; -- [confirmed] Venusaur / Growl: 1 -> 3 (versions saw: 1,4,3)
update pokedex_passives set level_learned = 28 where pokedex_id = 354 and passive_id = 373; -- [confirmed] Venusaur / Growth: 1 -> 28 (versions saw: 43,41,28,44,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 457 and passive_id = 366; -- [confirmed] Vikavolt / String shot: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 49 where pokedex_id = 1186 and passive_id = 380; -- [confirmed] Virizion / Work up: 1 -> 49 (versions saw: 61,1,49)
update pokedex_passives set level_learned = 54 where pokedex_id = 1023 and passive_id = 354; -- [confirmed] Volcarona / Amnesia: 1 -> 54 (versions saw: 1,54)
update pokedex_passives set level_learned = 59 where pokedex_id = 1023 and passive_id = 375; -- [confirmed] Volcarona / Quiver dance: 1 -> 59 (versions saw: 59,1,0)
update pokedex_passives set level_learned = 8 where pokedex_id = 482 and passive_id = 330; -- [confirmed] Voltorb / Screech: 1 -> 8 (versions saw: 1,9,8,19,13,24)
update pokedex_passives set level_learned = 3 where pokedex_id = 523 and passive_id = 328; -- [confirmed] Vulpix / Tail whip: 1 -> 3 (versions saw: 1,5,4,3)
update pokedex_passives set level_learned = 4 where pokedex_id = 1113 and passive_id = 337; -- [confirmed] Wailord / Growl: 1 -> 4 (versions saw: 1,5,4)
update pokedex_passives set level_learned = 4 where pokedex_id = 1088 and passive_id = 328; -- [confirmed] Wartortle / Tail whip: 1 -> 4 (versions saw: 1,4,5)
update pokedex_passives set level_learned = 10 where pokedex_id = 1088 and passive_id = 341; -- [confirmed] Wartortle / Withdraw: 1 -> 10 (versions saw: 31,10,1,14)
update pokedex_passives set level_learned = 3 where pokedex_id = 831 and passive_id = 324; -- [confirmed] Watchog / Leer: 1 -> 3 (versions saw: 1,3)
update pokedex_passives set level_learned = 4 where pokedex_id = 1153 and passive_id = 373; -- [confirmed] Weepinbell / Growth: 1 -> 4 (versions saw: 1,6,7,4)
update pokedex_passives set level_learned = 28 where pokedex_id = 1178 and passive_id = 367; -- [confirmed] Whimsicott / Tailwind: 1 -> 28 (versions saw: 28,1)
update pokedex_passives set level_learned = 22 where pokedex_id = 465 and passive_id = 345; -- [confirmed] Whirlipede / Iron defense: 0 -> 22 (versions saw: 22,0,1)
update pokedex_passives set level_learned = 8 where pokedex_id = 465 and passive_id = 330; -- [confirmed] Whirlipede / Screech: 1 -> 8 (versions saw: 1,8,16)
update pokedex_passives set level_learned = 27 where pokedex_id = 1217 and passive_id = 367; -- [confirmed] Xatu / Tailwind: 1 -> 27 (versions saw: 27,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 812 and passive_id = 324; -- [confirmed] Zangoose / Leer: 1 -> 4 (versions saw: 4,1)
update pokedex_passives set level_learned = 4 where pokedex_id = 743 and passive_id = 328; -- [confirmed] Zebstrika / Tail whip: 1 -> 4 (versions saw: 1,4)
update pokedex_passives set level_learned = 9 where pokedex_id = 1293 and passive_id = 329; -- [confirmed] Zoroark / Hone claws: 1 -> 9 (versions saw: 1,9)
update pokedex_passives set level_learned = 4 where pokedex_id = 1299 and passive_id = 382; -- [confirmed] Zweilous / Focus energy: 1 -> 4 (versions saw: 1,4)

-- Rule 2: estimated from other species (no per-species PokeAPI evidence for these)
update pokedex_passives set level_learned = 22 where pokedex_id = 829 and passive_id = 371; -- [estimate] Arceus / Cosmic power: 1 -> 22 (no per-species data; other species' earliest is 22, median 23.5)
update pokedex_passives set level_learned = 6 where pokedex_id = 843 and passive_id = 360; -- [estimate] Bunnelby / Agility: 1 -> 6 (no per-species data; other species' earliest is 6, median 24)
update pokedex_passives set level_learned = 4 where pokedex_id = 1118 and passive_id = 345; -- [estimate] Clamperl / Iron defense: 1 -> 4 (no per-species data; other species' earliest is 4, median 21)
update pokedex_passives set level_learned = 5 where pokedex_id = 1067 and passive_id = 364; -- [estimate] Dialga / Scary face: 1 -> 5 (no per-species data; other species' earliest is 5, median 20)
update pokedex_passives set level_learned = 6 where pokedex_id = 931 and passive_id = 360; -- [estimate] Eternatus / Agility: 1 -> 6 (no per-species data; other species' earliest is 6, median 24)
update pokedex_passives set level_learned = 21 where pokedex_id = 1128 and passive_id = 352; -- [estimate] Manaphy / Tail glow: 1 -> 21 (no per-species data; other species' earliest is 21, median 11)
update pokedex_passives set level_learned = 5 where pokedex_id = 1310 and passive_id = 364; -- [estimate] Maschiff / Scary face: 1 -> 5 (no per-species data; other species' earliest is 5, median 20)
update pokedex_passives set level_learned = 13 where pokedex_id = 935 and passive_id = 368; -- [estimate] Okidogi / Bulk up: 1 -> 13 (no per-species data; other species' earliest is 13, median 25)
update pokedex_passives set level_learned = 5 where pokedex_id = 1126 and passive_id = 364; -- [estimate] Palkia / Scary face: 1 -> 5 (no per-species data; other species' earliest is 5, median 20)
update pokedex_passives set level_learned = 5 where pokedex_id = 1318 and passive_id = 364; -- [estimate] Snubbull / Scary face: 1 -> 5 (no per-species data; other species' earliest is 5, median 20)
update pokedex_passives set level_learned = 13 where pokedex_id = 754 and passive_id = 378; -- [estimate] Toxel / Tearful look: 1 -> 13 (no per-species data; other species' earliest is 13, median 19)
update pokedex_passives set level_learned = 9 where pokedex_id = 1225 and passive_id = 354; -- [estimate] Wynaut / Amnesia: 1 -> 9 (no per-species data; other species' earliest is 9, median 29)
update pokedex_passives set level_learned = 21 where pokedex_id = 750 and passive_id = 352; -- [estimate] Xurkitree / Tail glow: 1 -> 21 (no per-species data; other species' earliest is 21, median 11)
