-- Tag Moves with their Proficiencies (per Features/Tag Moves with their Proficiencies.md).
-- moves_proficiencies was completely empty (0 rows) -- this seeds it from a PDF extraction pass over
-- PTA3Pokedex-1.pdf pages 750-775 ("Proficiency Group Lists"), matched against the real move/
-- proficiency names already in this schema. Full extraction methodology, per-proficiency counts, and
-- the reasoning behind every derived proficiency below are logged in that FR note.

-- =========================================================================
-- Part 1: 19 moves that appear in the PDF's Proficiency Lists but were never added to `moves`.
-- All 19 are single-type-list moves (no ambiguity about which proficiency they belong to).
-- =========================================================================

insert into moves (name, range, type_id, damage_stat, frequency, damage_dice, description) values
  ('Struggling bug', 'Ranged (20ft)', (select id from types where lower(name) = lower('Bug')), 'special', 'At will', '2d6', 'No additional effect'),
  ('Brutal hit', 'Melee', (select id from types where lower(name) = lower('Dark')), 'physical', 'At will', '2d6', 'No additional effect'),
  ('Void fury', 'Melee', (select id from types where lower(name) = lower('Dark')), 'physical', '1/day', '5d12', 'On hit, your Defense and Special Defense are -2 for 10 mins'),
  ('Twisting gust', 'Ranged (20ft)', (select id from types where lower(name) = lower('Dragon')), 'special', 'At will', '1d12', 'No additional effect'),
  ('Thunder spark', 'Ranged (20ft)', (select id from types where lower(name) = lower('Electric')), 'special', 'At will', '1d12', 'No additional effect'),
  ('Moonwrecker', 'Ranged (20ft, 10ft blast)', (select id from types where lower(name) = lower('Fairy')), 'special', '1/day', '5d12', 'After use, your Special Attack is -4 for 10 mins'),
  ('Karate slap', 'Melee', (select id from types where lower(name) = lower('Fighting')), 'physical', 'At will', '2d6', 'No additional effect'),
  ('Emberish', 'Ranged (20ft)', (select id from types where lower(name) = lower('Fire')), 'special', 'At will', '1d12', 'No additional effect'),
  ('Air dart', 'Ranged (10ft)', (select id from types where lower(name) = lower('Flying')), 'physical', 'At will', '2d6', 'No additional effect'),
  ('Spook', 'Melee', (select id from types where lower(name) = lower('Ghost')), 'physical', 'At will', '2d6', 'No additional effect'),
  ('Terrify', 'Ranged (25ft)', (select id from types where lower(name) = lower('Ghost')), 'special', 'At will', '1d12', 'No additional effect'),
  ('Mud throw', 'Ranged (20ft)', (select id from types where lower(name) = lower('Ground')), 'special', 'At will', '2d6', 'No additional effect'),
  ('Icy breeze', 'Ranged (20ft)', (select id from types where lower(name) = lower('Ice')), 'special', 'At will', '2d6', 'No additional effect'),
  ('Clearing smog', 'Ranged (20ft)', (select id from types where lower(name) = lower('Poison')), 'special', 'At will', '1d12', 'No additional effect'),
  ('Sludge wave', 'Ranged (20ft, 10ft wave)', (select id from types where lower(name) = lower('Poison')), 'special', '1/day', '3d12', 'On hit, if you got 18 or higher on Accuracy Check, all targets are Poisoned'),
  ('Confusioning', 'Ranged (20ft)', (select id from types where lower(name) = lower('Psychic')), 'special', 'At will', '1d12', 'No additional effect'),
  ('Psionic fury', 'Ranged (20ft)', (select id from types where lower(name) = lower('Psychic')), 'special', '1/day', '5d12', 'On hit, your Defense and Special Defense are -2 for 10 mins'),
  ('Metal cut', 'Melee', (select id from types where lower(name) = lower('Steel')), 'physical', 'At will', '2d6', 'No additional effect'),
  ('Meteor rain', 'Ranged (20ft, 10ft blast)', (select id from types where lower(name) = lower('Steel')), 'special', '1/day', '5d12', 'After use, your Special Attack is -4 for 10 mins')
on conflict (name) do nothing;

-- =========================================================================
-- Part 2: the extracted (move, proficiency) pairs -- 633 from the PDF pull plus the 19 new moves'
-- own tags (652 total), inserted via a VALUES table joined against moves/proficiencies by name so a
-- typo in either resolves to no row rather than a bad foreign key.
-- =========================================================================

insert into moves_proficiencies (move_id, proficiency_id)
select m.id, p.id
from (values
  ('Brave bird', 'Avian'),
  ('Drill peck', 'Avian'),
  ('Mirror move', 'Avian'),
  ('Peck', 'Avian'),
  ('Belly drum', 'Bruiser'),
  ('Body slam', 'Bruiser'),
  ('Breaking swipe', 'Bruiser'),
  ('Brutal swing', 'Bruiser'),
  ('Counter', 'Bruiser'),
  ('Darkest lariat', 'Bruiser'),
  ('Double edge', 'Bruiser'),
  ('Earth power', 'Bruiser'),
  ('Earthquake', 'Bruiser'),
  ('Hammer arm', 'Bruiser'),
  ('Headbutt', 'Bruiser'),
  ('Iron head', 'Bruiser'),
  ('Lash out', 'Bruiser'),
  ('Play rough', 'Bruiser'),
  ('Revenge', 'Bruiser'),
  ('Slam', 'Bruiser'),
  ('Stomping tantrum', 'Bruiser'),
  ('Strength', 'Bruiser'),
  ('Submission', 'Bruiser'),
  ('Superpower', 'Bruiser'),
  ('Thrash', 'Bruiser'),
  ('Acid spray', 'Bug'),
  ('Bug bite', 'Bug'),
  ('Bug buzz', 'Bug'),
  ('Fell stinger', 'Bug'),
  ('Fury cutter', 'Bug'),
  ('Infestation', 'Bug'),
  ('Leech life', 'Bug'),
  ('Lunge', 'Bug'),
  ('Megahorn', 'Bug'),
  ('Pin missile', 'Bug'),
  ('Poison sting', 'Bug'),
  ('Pounce', 'Bug'),
  ('Signal beam', 'Bug'),
  ('Silver wind', 'Bug'),
  ('Skitter smack', 'Bug'),
  ('Struggle bug', 'Bug'),
  ('Struggling bug', 'Bug'),
  ('Venoshock', 'Bug'),
  ('Alluring voice', 'Cutesy'),
  ('Disarming voice', 'Cutesy'),
  ('Draining kiss', 'Cutesy'),
  ('Follow me', 'Cutesy'),
  ('Nuzzle', 'Cutesy'),
  ('Pounce', 'Cutesy'),
  ('Skitter smack', 'Cutesy'),
  ('Sweet kiss', 'Cutesy'),
  ('Yawn', 'Cutesy'),
  ('Assurance', 'Dark'),
  ('Bite', 'Dark'),
  ('Brutal hit', 'Dark'),
  ('Brutal swing', 'Dark'),
  ('Crunch', 'Dark'),
  ('Dark pulse', 'Dark'),
  ('Feint attack', 'Dark'),
  ('Knock off', 'Dark'),
  ('Lash out', 'Dark'),
  ('Night slash', 'Dark'),
  ('Payback', 'Dark'),
  ('Punishment', 'Dark'),
  ('Snarl', 'Dark'),
  ('Sucker punch', 'Dark'),
  ('Thief', 'Dark'),
  ('Throat chop', 'Dark'),
  ('Void fury', 'Dark'),
  ('Dragon breath', 'Draconian'),
  ('Dragon claw', 'Draconian'),
  ('Dragon rage', 'Draconian'),
  ('Dragon rush', 'Draconian'),
  ('Dragon tail', 'Draconian'),
  ('Draco meteor', 'Dragon'),
  ('Dragon breath', 'Dragon'),
  ('Dragon rage', 'Dragon'),
  ('Dragon rush', 'Dragon'),
  ('Dragon tail', 'Dragon'),
  ('Dual chop', 'Dragon'),
  ('Outrage', 'Dragon'),
  ('Scale shot', 'Dragon'),
  ('Twister', 'Dragon'),
  ('Twisting gust', 'Dragon'),
  ('Charge', 'Electric'),
  ('Charge beam', 'Electric'),
  ('Discharge', 'Electric'),
  ('Electric terrain', 'Electric'),
  ('Electro ball', 'Electric'),
  ('Flash', 'Electric'),
  ('Magnet rise', 'Electric'),
  ('Rising voltage', 'Electric'),
  ('Shock wave', 'Electric'),
  ('Spark', 'Electric'),
  ('Supercell slam', 'Electric'),
  ('Thunder', 'Electric'),
  ('Thunder fang', 'Electric'),
  ('Thunder punch', 'Electric'),
  ('Thunder shock', 'Electric'),
  ('Thunder spark', 'Electric'),
  ('Thunder wave', 'Electric'),
  ('Thunderbolt', 'Electric'),
  ('Wild charge', 'Electric'),
  ('Zap cannon', 'Electric'),
  ('Blizzard', 'Elemental Attack'),
  ('Charge beam', 'Elemental Attack'),
  ('Ember', 'Elemental Attack'),
  ('Fire blast', 'Elemental Attack'),
  ('Fire spin', 'Elemental Attack'),
  ('Flame burst', 'Elemental Attack'),
  ('Flamethrower', 'Elemental Attack'),
  ('Heat wave', 'Elemental Attack'),
  ('Ice beam', 'Elemental Attack'),
  ('Icy wind', 'Elemental Attack'),
  ('Shock wave', 'Elemental Attack'),
  ('Thunder', 'Elemental Attack'),
  ('Thunder shock', 'Elemental Attack'),
  ('Thunderbolt', 'Elemental Attack'),
  ('Charge beam', 'Elemental Attack E'),
  ('Shock wave', 'Elemental Attack E'),
  ('Thunder', 'Elemental Attack E'),
  ('Thunder shock', 'Elemental Attack E'),
  ('Thunderbolt', 'Elemental Attack E'),
  ('Blizzard', 'Elemental Attack I'),
  ('Ice beam', 'Elemental Attack I'),
  ('Icy wind', 'Elemental Attack I'),
  ('Dark pulse', 'Energy Blast'),
  ('Dazzling gleam', 'Energy Blast'),
  ('Dragon pulse', 'Energy Blast'),
  ('Flash cannon', 'Energy Blast'),
  ('Psybeam', 'Energy Blast'),
  ('Shadow ball', 'Energy Blast'),
  ('Signal beam', 'Energy Blast'),
  ('Dazzling gleam', 'Fairy'),
  ('Disarming voice', 'Fairy'),
  ('Draining kiss', 'Fairy'),
  ('Fairy wind', 'Fairy'),
  ('Misty terrain', 'Fairy'),
  ('Moonblast', 'Fairy'),
  ('Moonwrecker', 'Fairy'),
  ('Play rough', 'Fairy'),
  ('Sweet kiss', 'Fairy'),
  ('Sweet scent', 'Fairy'),
  ('Bite', 'Fangs'),
  ('Bug bite', 'Fangs'),
  ('Crunch', 'Fangs'),
  ('Fire fang', 'Fangs'),
  ('Hyper fang', 'Fangs'),
  ('Ice fang', 'Fangs'),
  ('Poison fang', 'Fangs'),
  ('Psychic fangs', 'Fangs'),
  ('Thunder fang', 'Fangs'),
  ('Aura sphere', 'Fighting'),
  ('Brick break', 'Fighting'),
  ('Close combat', 'Fighting'),
  ('Coaching', 'Fighting'),
  ('Counter', 'Fighting'),
  ('Cross chop', 'Fighting'),
  ('Detect', 'Fighting'),
  ('Double kick', 'Fighting'),
  ('Drain punch', 'Fighting'),
  ('Dynamic punch', 'Fighting'),
  ('Final gambit', 'Fighting'),
  ('Focus blast', 'Fighting'),
  ('Focus punch', 'Fighting'),
  ('Force palm', 'Fighting'),
  ('High jump kick', 'Fighting'),
  ('Jump kick', 'Fighting'),
  ('Karate chop', 'Fighting'),
  ('Karate slap', 'Fighting'),
  ('Low kick', 'Fighting'),
  ('Low sweep', 'Fighting'),
  ('Mach punch', 'Fighting'),
  ('Power-up punch', 'Fighting'),
  ('Revenge', 'Fighting'),
  ('Reversal', 'Fighting'),
  ('Rock smash', 'Fighting'),
  ('Rolling kick', 'Fighting'),
  ('Seismic toss', 'Fighting'),
  ('Submission', 'Fighting'),
  ('Superpower', 'Fighting'),
  ('Vacuum wave', 'Fighting'),
  ('Vital throw', 'Fighting'),
  ('Wake-up slap', 'Fighting'),
  ('Clear smog', 'Fire'),
  ('Ember', 'Fire'),
  ('Emberish', 'Fire'),
  ('Fire blast', 'Fire'),
  ('Fire punch', 'Fire'),
  ('Fire spin', 'Fire'),
  ('Flame burst', 'Fire'),
  ('Flame charge', 'Fire'),
  ('Flame wheel', 'Fire'),
  ('Flamethrower', 'Fire'),
  ('Flare blitz', 'Fire'),
  ('Flash', 'Fire'),
  ('Heat wave', 'Fire'),
  ('Incinerate', 'Fire'),
  ('Inferno', 'Fire'),
  ('Lava plume', 'Fire'),
  ('Overheat', 'Fire'),
  ('Scorching sands', 'Fire'),
  ('Smog', 'Fire'),
  ('Smoke screen', 'Fire'),
  ('Solar beam', 'Fire'),
  ('Sunny day', 'Fire'),
  ('Temper flare', 'Fire'),
  ('Will-o-wisp', 'Fire'),
  ('Aromatherapy', 'Floral'),
  ('Energy ball', 'Floral'),
  ('Grassy terrain', 'Floral'),
  ('Petal blizzard', 'Floral'),
  ('Petal dance', 'Floral'),
  ('Sleep powder', 'Floral'),
  ('Stun spore', 'Floral'),
  ('Sweet scent', 'Floral'),
  ('Aerial ace', 'Flying'),
  ('Air cutter', 'Flying'),
  ('Air dart', 'Flying'),
  ('Air slash', 'Flying'),
  ('Bounce', 'Flying'),
  ('Defog', 'Flying'),
  ('Fly', 'Flying'),
  ('Gust', 'Flying'),
  ('Hurricane', 'Flying'),
  ('Sky drop', 'Flying'),
  ('Whirlwind', 'Flying'),
  ('Wing attack', 'Flying'),
  ('Astonish', 'Ghost'),
  ('Confuse ray', 'Ghost'),
  ('Curse', 'Ghost'),
  ('Destiny bond', 'Ghost'),
  ('Hex', 'Ghost'),
  ('Lick', 'Ghost'),
  ('Night shade', 'Ghost'),
  ('Ominous wind', 'Ghost'),
  ('Phantom force', 'Ghost'),
  ('Poltergeist', 'Ghost'),
  ('Shadow ball', 'Ghost'),
  ('Shadow claw', 'Ghost'),
  ('Shadow sneak', 'Ghost'),
  ('Spook', 'Ghost'),
  ('Terrify', 'Ghost'),
  ('Belch', 'Glutton'),
  ('Gastro acid', 'Glutton'),
  ('Lick', 'Glutton'),
  ('Spit up', 'Glutton'),
  ('Stockpile', 'Glutton'),
  ('Swallow', 'Glutton'),
  ('Absorb', 'Grass'),
  ('Bullet seed', 'Grass'),
  ('Energy ball', 'Grass'),
  ('Giga drain', 'Grass'),
  ('Grass knot', 'Grass'),
  ('Grassy glide', 'Grass'),
  ('Grassy terrain', 'Grass'),
  ('Leaf blade', 'Grass'),
  ('Leaf storm', 'Grass'),
  ('Leafage', 'Grass'),
  ('Leech seed', 'Grass'),
  ('Magical leaf', 'Grass'),
  ('Mega drain', 'Grass'),
  ('Poison powder', 'Grass'),
  ('Razor leaf', 'Grass'),
  ('Seed bomb', 'Grass'),
  ('Sleep powder', 'Grass'),
  ('Solar beam', 'Grass'),
  ('Stun spore', 'Grass'),
  ('Sunny day', 'Grass'),
  ('Sweet scent', 'Grass'),
  ('Synthesis', 'Grass'),
  ('Bulldoze', 'Ground'),
  ('Dig', 'Ground'),
  ('Earth power', 'Ground'),
  ('Earthquake', 'Ground'),
  ('Mud bomb', 'Ground'),
  ('Mud shot', 'Ground'),
  ('Mud sport', 'Ground'),
  ('Mud throw', 'Ground'),
  ('Mud-slap', 'Ground'),
  ('Sand tomb', 'Ground'),
  ('Sandstorm', 'Ground'),
  ('Scorching sands', 'Ground'),
  ('Spikes', 'Ground'),
  ('Stomping tantrum', 'Ground'),
  ('Heal pulse', 'Healer'),
  ('Healing wish', 'Healer'),
  ('Life dew', 'Healer'),
  ('Refresh', 'Healer'),
  ('Safeguard', 'Healer'),
  ('Wish', 'Healer'),
  ('Confuse ray', 'Hexwork'),
  ('Destiny bond', 'Hexwork'),
  ('Disable', 'Hexwork'),
  ('Dream eater', 'Hexwork'),
  ('Heal block', 'Hexwork'),
  ('Hex', 'Hexwork'),
  ('Hypnosis', 'Hexwork'),
  ('Mean look', 'Hexwork'),
  ('Memento', 'Hexwork'),
  ('Pain split', 'Hexwork'),
  ('Trick', 'Hexwork'),
  ('Will-o-wisp', 'Hexwork'),
  ('Drill run', 'Horned'),
  ('Horn attack', 'Horned'),
  ('Ice spinner', 'Horned'),
  ('Megahorn', 'Horned'),
  ('Poison jab', 'Horned'),
  ('Poison sting', 'Horned'),
  ('Smart strike', 'Horned'),
  ('Aurora beam', 'Ice'),
  ('Aurora veil', 'Ice'),
  ('Avalanche', 'Ice'),
  ('Blizzard', 'Ice'),
  ('Chilling water', 'Ice'),
  ('Freeze-dry', 'Ice'),
  ('Frost breath', 'Ice'),
  ('Hail', 'Ice'),
  ('Haze', 'Ice'),
  ('Ice beam', 'Ice'),
  ('Ice shard', 'Ice'),
  ('Ice spinner', 'Ice'),
  ('Icicle crash', 'Ice'),
  ('Icicle spear', 'Ice'),
  ('Icy breeze', 'Ice'),
  ('Icy wind', 'Ice'),
  ('Mirror coat', 'Ice'),
  ('Mist', 'Ice'),
  ('Powder snow', 'Ice'),
  ('Snowscape', 'Ice'),
  ('Triple axel', 'Ice'),
  ('Axe kick', 'Kicks'),
  ('Blaze kick', 'Kicks'),
  ('Double kick', 'Kicks'),
  ('High jump kick', 'Kicks'),
  ('Jump kick', 'Kicks'),
  ('Low kick', 'Kicks'),
  ('Low sweep', 'Kicks'),
  ('Rolling kick', 'Kicks'),
  ('Triple axel', 'Kicks'),
  ('Poison powder', 'Lepidopteran'),
  ('Powder', 'Lepidopteran'),
  ('Rage powder', 'Lepidopteran'),
  ('Sleep powder', 'Lepidopteran'),
  ('Stun spore', 'Lepidopteran'),
  ('Electric terrain', 'Magnetism'),
  ('Lock-on', 'Magnetism'),
  ('Magnet pull', 'Magnetism'),
  ('Magnet rise', 'Magnetism'),
  ('Acrobatics', 'Martial'),
  ('Aura sphere', 'Martial'),
  ('Close combat', 'Martial'),
  ('Cross chop', 'Martial'),
  ('Dual chop', 'Martial'),
  ('Force palm', 'Martial'),
  ('Karate chop', 'Martial'),
  ('Rock climb', 'Martial'),
  ('Smack down', 'Martial'),
  ('Throat chop', 'Martial'),
  ('Vacuum wave', 'Martial'),
  ('Vital throw', 'Martial'),
  ('Wake-up slap', 'Martial'),
  ('Bullet seed', 'Munition'),
  ('Electro ball', 'Munition'),
  ('Gyro ball', 'Munition'),
  ('Mud bomb', 'Munition'),
  ('Rock blast', 'Munition'),
  ('Sludge bomb', 'Munition'),
  ('Astonish', 'Normal Block'),
  ('Avalanche', 'Normal Block'),
  ('Blizzard', 'Normal Block'),
  ('Brick break', 'Normal Block'),
  ('Charge beam', 'Normal Block'),
  ('Dynamic punch', 'Normal Block'),
  ('Ember', 'Normal Block'),
  ('Fire blast', 'Normal Block'),
  ('Fire spin', 'Normal Block'),
  ('Flame burst', 'Normal Block'),
  ('Flame wheel', 'Normal Block'),
  ('Flamethrower', 'Normal Block'),
  ('Focus blast', 'Normal Block'),
  ('Focus punch', 'Normal Block'),
  ('Grass knot', 'Normal Block'),
  ('Gunk shot', 'Normal Block'),
  ('Gyro ball', 'Normal Block'),
  ('Heat wave', 'Normal Block'),
  ('Ice beam', 'Normal Block'),
  ('Icy wind', 'Normal Block'),
  ('Incinerate', 'Normal Block'),
  ('Mud shot', 'Normal Block'),
  ('Mud sport', 'Normal Block'),
  ('Mud-slap', 'Normal Block'),
  ('Power-up punch', 'Normal Block'),
  ('Psychic', 'Normal Block'),
  ('Rain dance', 'Normal Block'),
  ('Rock smash', 'Normal Block'),
  ('Rock tomb', 'Normal Block'),
  ('Rollout', 'Normal Block'),
  ('Seismic toss', 'Normal Block'),
  ('Shadow ball', 'Normal Block'),
  ('Shock wave', 'Normal Block'),
  ('Submission', 'Normal Block'),
  ('Sunny day', 'Normal Block'),
  ('Thunder', 'Normal Block'),
  ('Thunder shock', 'Normal Block'),
  ('Thunder wave', 'Normal Block'),
  ('Thunderbolt', 'Normal Block'),
  ('Wild charge', 'Normal Block'),
  ('Zap cannon', 'Normal Block'),
  ('Zen headbutt', 'Normal Block'),
  ('Absorb', 'Parasitic'),
  ('Giga drain', 'Parasitic'),
  ('Leech life', 'Parasitic'),
  ('Mega drain', 'Parasitic'),
  ('Aqua tail', 'Piscian'),
  ('Body slam', 'Piscian'),
  ('Bounce', 'Piscian'),
  ('Dive', 'Piscian'),
  ('Flail', 'Piscian'),
  ('Signal beam', 'Piscian'),
  ('Slam', 'Piscian'),
  ('Water pulse', 'Piscian'),
  ('Whirlpool', 'Piscian'),
  ('Acid spray', 'Poison'),
  ('Clear smog', 'Poison'),
  ('Clearing smog', 'Poison'),
  ('Corrosive gas', 'Poison'),
  ('Cross poison', 'Poison'),
  ('Gunk shot', 'Poison'),
  ('Poison fang', 'Poison'),
  ('Poison gas', 'Poison'),
  ('Poison sting', 'Poison'),
  ('Sludge bomb', 'Poison'),
  ('Sludge wave', 'Poison'),
  ('Smog', 'Poison'),
  ('Smoke screen', 'Poison'),
  ('Sweet scent', 'Poison'),
  ('Toxic', 'Poison'),
  ('Toxic spikes', 'Poison'),
  ('Venom drench', 'Poison'),
  ('Venoshock', 'Poison'),
  ('Acupressure', 'Prickly'),
  ('Ice spinner', 'Prickly'),
  ('Pin missile', 'Prickly'),
  ('Poison jab', 'Prickly'),
  ('Poison sting', 'Prickly'),
  ('Spike cannon', 'Prickly'),
  ('Spikes', 'Prickly'),
  ('Twineedle', 'Prickly'),
  ('Ally switch', 'Psychic'),
  ('Confusion', 'Psychic'),
  ('Confusioning', 'Psychic'),
  ('Dream eater', 'Psychic'),
  ('Expanding force', 'Psychic'),
  ('Extrasensory', 'Psychic'),
  ('Future sight', 'Psychic'),
  ('Gravity', 'Psychic'),
  ('Light screen', 'Psychic'),
  ('Magic room', 'Psychic'),
  ('Mirror coat', 'Psychic'),
  ('Psionic fury', 'Psychic'),
  ('Psybeam', 'Psychic'),
  ('Psychic', 'Psychic'),
  ('Psychic terrain', 'Psychic'),
  ('Psycho cut', 'Psychic'),
  ('Psyshock', 'Psychic'),
  ('Reflect', 'Psychic'),
  ('Teleport', 'Psychic'),
  ('Trick', 'Psychic'),
  ('Trick room', 'Psychic'),
  ('Wonder room', 'Psychic'),
  ('Zen headbutt', 'Psychic'),
  ('Aura sphere', 'Pulse'),
  ('Dark pulse', 'Pulse'),
  ('Dragon pulse', 'Pulse'),
  ('Heal pulse', 'Pulse'),
  ('Terrain pulse', 'Pulse'),
  ('Water pulse', 'Pulse'),
  ('Bullet punch', 'Punches'),
  ('Comet punch', 'Punches'),
  ('Dizzy punch', 'Punches'),
  ('Drain punch', 'Punches'),
  ('Dynamic punch', 'Punches'),
  ('Fire punch', 'Punches'),
  ('Focus punch', 'Punches'),
  ('Ice punch', 'Punches'),
  ('Mach punch', 'Punches'),
  ('Poison jab', 'Punches'),
  ('Power-up punch', 'Punches'),
  ('Sky uppercut', 'Punches'),
  ('Sucker punch', 'Punches'),
  ('Thunder punch', 'Punches'),
  ('Ancient power', 'Rock'),
  ('Head smash', 'Rock'),
  ('Meteor beam', 'Rock'),
  ('Power gem', 'Rock'),
  ('Rock blast', 'Rock'),
  ('Rock slide', 'Rock'),
  ('Rock throw', 'Rock'),
  ('Rock tomb', 'Rock'),
  ('Rollout', 'Rock'),
  ('Sandstorm', 'Rock'),
  ('Smack down', 'Rock'),
  ('Stealth rock', 'Rock'),
  ('Stone edge', 'Rock'),
  ('Aerial ace', 'Slashing'),
  ('Air slash', 'Slashing'),
  ('Cross poison', 'Slashing'),
  ('Crush claw', 'Slashing'),
  ('Cut', 'Slashing'),
  ('Fury cutter', 'Slashing'),
  ('Fury swipes', 'Slashing'),
  ('Metal claw', 'Slashing'),
  ('Night slash', 'Slashing'),
  ('Psycho cut', 'Slashing'),
  ('Razor wind', 'Slashing'),
  ('Scratch', 'Slashing'),
  ('Shadow claw', 'Slashing'),
  ('Slash', 'Slashing'),
  ('Solar blade', 'Slashing'),
  ('X-scissor', 'Slashing'),
  ('Boomburst', 'Sound'),
  ('Echoed voice', 'Sound'),
  ('Hyper voice', 'Sound'),
  ('Round', 'Sound'),
  ('Sing', 'Sound'),
  ('Sonic boom', 'Sound'),
  ('Supersonic', 'Sound'),
  ('Synchronoise', 'Sound'),
  ('Uproar', 'Sound'),
  ('Ally switch', 'Spellcraft'),
  ('Destiny bond', 'Spellcraft'),
  ('Disable', 'Spellcraft'),
  ('Flash', 'Spellcraft'),
  ('Gravity', 'Spellcraft'),
  ('Heal block', 'Spellcraft'),
  ('Healing wish', 'Spellcraft'),
  ('Light screen', 'Spellcraft'),
  ('Lucky chant', 'Spellcraft'),
  ('Magic coat', 'Spellcraft'),
  ('Magic room', 'Spellcraft'),
  ('Magical leaf', 'Spellcraft'),
  ('Mean look', 'Spellcraft'),
  ('Misty terrain', 'Spellcraft'),
  ('Mystical fire', 'Spellcraft'),
  ('Pain split', 'Spellcraft'),
  ('Reflect', 'Spellcraft'),
  ('Safeguard', 'Spellcraft'),
  ('Sing', 'Spellcraft'),
  ('Teleport', 'Spellcraft'),
  ('Wish', 'Spellcraft'),
  ('Assurance', 'Stampeding'),
  ('Belly drum', 'Stampeding'),
  ('Block', 'Stampeding'),
  ('Body press', 'Stampeding'),
  ('Body slam', 'Stampeding'),
  ('Bulldoze', 'Stampeding'),
  ('Double edge', 'Stampeding'),
  ('Earthquake', 'Stampeding'),
  ('Head smash', 'Stampeding'),
  ('Headbutt', 'Stampeding'),
  ('Heavy slam', 'Stampeding'),
  ('Outrage', 'Stampeding'),
  ('Rock slide', 'Stampeding'),
  ('Sand tomb', 'Stampeding'),
  ('Slam', 'Stampeding'),
  ('Steamroller', 'Stampeding'),
  ('Steel roller', 'Stampeding'),
  ('Stomp', 'Stampeding'),
  ('Stomping tantrum', 'Stampeding'),
  ('Stone edge', 'Stampeding'),
  ('Strength', 'Stampeding'),
  ('Surf', 'Stampeding'),
  ('Thrash', 'Stampeding'),
  ('Bullet punch', 'Steel'),
  ('Flash cannon', 'Steel'),
  ('Gyro ball', 'Steel'),
  ('Heavy slam', 'Steel'),
  ('Iron head', 'Steel'),
  ('Iron tail', 'Steel'),
  ('Metal burst', 'Steel'),
  ('Metal cut', 'Steel'),
  ('Meteor rain', 'Steel'),
  ('Mirror coat', 'Steel'),
  ('Sandstorm', 'Steel'),
  ('Steel beam', 'Steel'),
  ('Steel roller', 'Steel'),
  ('Burning jealousy', 'Tricky'),
  ('Fake out', 'Tricky'),
  ('Feint attack', 'Tricky'),
  ('Flatter', 'Tricky'),
  ('Knock off', 'Tricky'),
  ('Payback', 'Tricky'),
  ('Punishment', 'Tricky'),
  ('Quash', 'Tricky'),
  ('Sucker punch', 'Tricky'),
  ('Swagger', 'Tricky'),
  ('Switcheroo', 'Tricky'),
  ('Thief', 'Tricky'),
  ('Throat chop', 'Tricky'),
  ('Aqua jet', 'Water'),
  ('Aqua ring', 'Water'),
  ('Aqua tail', 'Water'),
  ('Brine', 'Water'),
  ('Bubble', 'Water'),
  ('Bubble beam', 'Water'),
  ('Chilling water', 'Water'),
  ('Dive', 'Water'),
  ('Hydro pump', 'Water'),
  ('Liquidation', 'Water'),
  ('Muddy water', 'Water'),
  ('Rain dance', 'Water'),
  ('Scald', 'Water'),
  ('Soak', 'Water'),
  ('Surf', 'Water'),
  ('Water gun', 'Water'),
  ('Water pulse', 'Water'),
  ('Water sport', 'Water'),
  ('Waterfall', 'Water'),
  ('Whirlpool', 'Water'),
  ('Defog', 'Weather'),
  ('Hail', 'Weather'),
  ('Haze', 'Weather'),
  ('Mist', 'Weather'),
  ('Rain dance', 'Weather'),
  ('Snowscape', 'Weather'),
  ('Sunny day', 'Weather'),
  ('Confuse ray', 'Weird'),
  ('Gravity', 'Weird'),
  ('Lucky chant', 'Weird'),
  ('Magic room', 'Weird'),
  ('Mean look', 'Weird'),
  ('Misty terrain', 'Weird'),
  ('Switcheroo', 'Weird'),
  ('Trick room', 'Weird'),
  ('Wonder room', 'Weird'),
  ('Acrobatics', 'Winged'),
  ('Aerial ace', 'Winged'),
  ('Bounce', 'Winged'),
  ('Defog', 'Winged'),
  ('Dual wingbeat', 'Winged'),
  ('Fairy wind', 'Winged'),
  ('Heat wave', 'Winged'),
  ('Ominous wind', 'Winged'),
  ('Razor wind', 'Winged'),
  ('Roost', 'Winged'),
  ('Silver wind', 'Winged'),
  ('Sky attack', 'Winged'),
  ('Sky drop', 'Winged'),
  ('Steel wing', 'Winged'),
  ('Twister', 'Winged'),
  ('Wing attack', 'Winged')
) as pairs(move_name, proficiency_name)
join moves m on lower(m.name) = lower(pairs.move_name)
join proficiencies p on lower(p.name) = lower(pairs.proficiency_name)
on conflict (move_id, proficiency_id) do nothing;

-- =========================================================================
-- Part 3: derive the 8 qualifier proficiencies that have no separate move-list in the PDF (they're
-- per-species access limitations on a base list, not their own roster) from the base tags Part 2 just
-- inserted, using the move's own range/type_id/damage_stat columns.
-- =========================================================================

-- Grass (Melee) / Ice (Melee) / Poison (Melee): the melee-range subset of the base list.
insert into moves_proficiencies (move_id, proficiency_id)
select mp.move_id, target.id
from moves_proficiencies mp
join proficiencies base on base.id = mp.proficiency_id
join moves m on m.id = mp.move_id
join proficiencies target on target.name = base.name || ' (Melee)'
where base.name in ('Grass', 'Ice', 'Poison')
  and m.range = 'Melee'
on conflict (move_id, proficiency_id) do nothing;

-- Psychic (Effects): the non-damage-utility subset of the Psychic list.
insert into moves_proficiencies (move_id, proficiency_id)
select mp.move_id, (select id from proficiencies where name = 'Psychic (Effects)')
from moves_proficiencies mp
join proficiencies base on base.id = mp.proficiency_id
join moves m on m.id = mp.move_id
where base.name = 'Psychic'
  and m.damage_stat = 'effect'
on conflict (move_id, proficiency_id) do nothing;

-- Martial (No Punches or Kicks): identical to the base Martial tag set (the Martial List's own moves
-- only -- Punches/Kicks were kept as separate tags in Part 2, so this is a plain copy).
insert into moves_proficiencies (move_id, proficiency_id)
select mp.move_id, (select id from proficiencies where name = 'Martial (No Punches or Kicks)')
from moves_proficiencies mp
join proficiencies base on base.id = mp.proficiency_id
where base.name = 'Martial'
on conflict (move_id, proficiency_id) do nothing;

-- Martial (Kicks): union of the Martial and Kicks tag sets.
insert into moves_proficiencies (move_id, proficiency_id)
select distinct mp.move_id, (select id from proficiencies where name = 'Martial (Kicks)')
from moves_proficiencies mp
join proficiencies base on base.id = mp.proficiency_id
where base.name in ('Martial', 'Kicks')
on conflict (move_id, proficiency_id) do nothing;

-- Martial (No Ice) / Martial (No Electric or Ice): union of Martial + Punches + Kicks, excluding the
-- named type(s) -- Ice Punch and Thunder Punch are real members of the Punches list, so this exclusion
-- has real effect, not a hypothetical filter.
insert into moves_proficiencies (move_id, proficiency_id)
select distinct mp.move_id, (select id from proficiencies where name = 'Martial (No Ice)')
from moves_proficiencies mp
join proficiencies base on base.id = mp.proficiency_id
join moves m on m.id = mp.move_id
where base.name in ('Martial', 'Punches', 'Kicks')
  and m.type_id != (select id from types where lower(name) = lower('Ice'))
on conflict (move_id, proficiency_id) do nothing;

insert into moves_proficiencies (move_id, proficiency_id)
select distinct mp.move_id, (select id from proficiencies where name = 'Martial (No Electric or Ice)')
from moves_proficiencies mp
join proficiencies base on base.id = mp.proficiency_id
join moves m on m.id = mp.move_id
where base.name in ('Martial', 'Punches', 'Kicks')
  and m.type_id not in (
    select id from types where lower(name) in (lower('Ice'), lower('Electric'))
  )
on conflict (move_id, proficiency_id) do nothing;
