-- Fills Size/Weight/Diet/Habitat/Proficiencies for species PTA3Pokedex.pdf never covers (Legendaries/
-- Mythicals/Ultra Beasts/Paradox), sourced from PTA3GameMastersGuide.pdf pages 159-262 instead. See
-- [[Fill in Legendary and Mythical Pokedex data from a second source]]. Covers 52 of the 75 species
-- confirmed absent from the original sourcebook -- the rest need manual follow-up (parser couldn't
-- cleanly isolate their entry in this source's two-column layout, or had an ambiguous field).

-- Two new habitats this source needs that nothing existing covers (cosmic Legendaries / Ultra Beasts).
insert into habitats (name, description) values
  ('Space', 'The vacuum beyond the world -- cosmic, dimension-traveling, or otherwise not of this world.'),
  ('Foreign Dimension', 'A dimension outside this world entirely, as with Ultra Beasts passing through Ultra Wormholes.')
on conflict (name) do nothing;

-- Size + Weight (direct columns on pokedex)
update pokedex set size_id = (select id from sizes where name = 'Gigantic'), weight_id = (select id from weights where name = 'Superweight') where name = 'Groudon';
update pokedex set size_id = (select id from sizes where name = 'Large'), weight_id = (select id from weights where name = 'Medium') where name = 'Zapdos';
update pokedex set size_id = (select id from sizes where name = 'Large'), weight_id = (select id from weights where name = 'Heavy') where name = 'Raikou';
update pokedex set size_id = (select id from sizes where name = 'Large'), weight_id = (select id from weights where name = 'Superweight') where name = 'Xurkitree';
update pokedex set size_id = (select id from sizes where name = 'Huge'), weight_id = (select id from weights where name = 'Heavy') where name = 'Regieleki';
update pokedex set size_id = (select id from sizes where name = 'Gigantic'), weight_id = (select id from weights where name = 'Superweight') where name = 'Regigigas';
update pokedex set size_id = (select id from sizes where name = 'Gigantic'), weight_id = (select id from weights where name = 'Superweight') where name = 'Arceus';
update pokedex set size_id = (select id from sizes where name = 'Large'), weight_id = (select id from weights where name = 'Heavy') where name = 'Silvally';
update pokedex set size_id = (select id from sizes where name = 'Small'), weight_id = (select id from weights where name = 'Medium') where name = 'Marshadow';
update pokedex set size_id = (select id from sizes where name = 'Small'), weight_id = (select id from weights where name = 'Light') where name = 'Poipole';
update pokedex set size_id = (select id from sizes where name = 'Huge'), weight_id = (select id from weights where name = 'Heavy') where name = 'Naganadel';
update pokedex set size_id = (select id from sizes where name = 'Large'), weight_id = (select id from weights where name = 'Heavy') where name = 'Okidogi';
update pokedex set size_id = (select id from sizes where name = 'Medium'), weight_id = (select id from weights where name = 'Medium') where name = 'Munkidori';
update pokedex set size_id = (select id from sizes where name = 'Large'), weight_id = (select id from weights where name = 'Medium') where name = 'Fezandipiti';
update pokedex set size_id = (select id from sizes where name = 'Small'), weight_id = (select id from weights where name = 'Featherweight') where name = 'Pecharunt';
update pokedex set size_id = (select id from sizes where name = 'Huge'), weight_id = (select id from weights where name = 'Superweight') where name = 'Regirock';
update pokedex set size_id = (select id from sizes where name = 'Large'), weight_id = (select id from weights where name = 'Superweight') where name = 'Terrakion';
update pokedex set size_id = (select id from sizes where name = 'Medium'), weight_id = (select id from weights where name = 'Medium') where name = 'Diancie';
update pokedex set size_id = (select id from sizes where name = 'Huge'), weight_id = (select id from weights where name = 'Superweight') where name = 'Stakataka';
update pokedex set size_id = (select id from sizes where name = 'Medium'), weight_id = (select id from weights where name = 'Heavy') where name = 'Genesect';
update pokedex set size_id = (select id from sizes where name = 'Large'), weight_id = (select id from weights where name = 'Superweight') where name = 'Buzzwole';
update pokedex set size_id = (select id from sizes where name = 'Large'), weight_id = (select id from weights where name = 'Medium') where name = 'Pheromosa';
update pokedex set size_id = (select id from sizes where name = 'Huge'), weight_id = (select id from weights where name = 'Medium') where name = 'Spectrier';
update pokedex set size_id = (select id from sizes where name = 'Huge'), weight_id = (select id from weights where name = 'Superweight') where name = 'Registeel';
update pokedex set size_id = (select id from sizes where name = 'Small'), weight_id = (select id from weights where name = 'Light') where name = 'Jirachi';
update pokedex set size_id = (select id from sizes where name = 'Large'), weight_id = (select id from weights where name = 'Superweight') where name = 'Cobalion';
update pokedex set size_id = (select id from sizes where name = 'Gigantic'), weight_id = (select id from weights where name = 'Superweight') where name = 'Celesteela';
update pokedex set size_id = (select id from sizes where name = 'Large'), weight_id = (select id from weights where name = 'Superweight') where name = 'Suicune';
update pokedex set size_id = (select id from sizes where name = 'Gigantic'), weight_id = (select id from weights where name = 'Superweight') where name = 'Kyogre';
update pokedex set size_id = (select id from sizes where name = 'Small'), weight_id = (select id from weights where name = 'Light') where name = 'Phione';
update pokedex set size_id = (select id from sizes where name = 'Small'), weight_id = (select id from weights where name = 'Light') where name = 'Manaphy';
update pokedex set size_id = (select id from sizes where name = 'Large'), weight_id = (select id from weights where name = 'Superweight') where name = 'Virizion';
update pokedex set size_id = (select id from sizes where name = 'Tiny'), weight_id = (select id from weights where name = 'Featherweight') where name = 'Kartana';
update pokedex set size_id = (select id from sizes where name = 'Small'), weight_id = (select id from weights where name = 'Light') where name = 'Celebi';
update pokedex set size_id = (select id from sizes where name = 'Large'), weight_id = (select id from weights where name = 'Heavy') where name = 'Cresselia';
update pokedex set size_id = (select id from sizes where name = 'Small'), weight_id = (select id from weights where name = 'Light') where name = 'Victini';
update pokedex set size_id = (select id from sizes where name = 'Small'), weight_id = (select id from weights where name = 'Featherweight') where name = 'Cosmog';
update pokedex set size_id = (select id from sizes where name = 'Tiny'), weight_id = (select id from weights where name = 'Superweight') where name = 'Cosmoem';
update pokedex set size_id = (select id from sizes where name = 'Huge'), weight_id = (select id from weights where name = 'Superweight') where name = 'Lunala';
update pokedex set size_id = (select id from sizes where name = 'Huge'), weight_id = (select id from weights where name = 'Superweight') where name = 'Necrozma';
update pokedex set size_id = (select id from sizes where name = 'Medium'), weight_id = (select id from weights where name = 'Light') where name = 'Calyrex';
update pokedex set size_id = (select id from sizes where name = 'Large'), weight_id = (select id from weights where name = 'Medium') where name = 'Latias';
update pokedex set size_id = (select id from sizes where name = 'Large'), weight_id = (select id from weights where name = 'Medium') where name = 'Latios';
update pokedex set size_id = (select id from sizes where name = 'Gigantic'), weight_id = (select id from weights where name = 'Superweight') where name = 'Rayquaza';
update pokedex set size_id = (select id from sizes where name = 'Gigantic'), weight_id = (select id from weights where name = 'Superweight') where name = 'Reshiram';
update pokedex set size_id = (select id from sizes where name = 'Gigantic'), weight_id = (select id from weights where name = 'Superweight') where name = 'Zekrom';
update pokedex set size_id = (select id from sizes where name = 'Huge'), weight_id = (select id from weights where name = 'Superweight') where name = 'Regidrago';
update pokedex set size_id = (select id from sizes where name = 'Large'), weight_id = (select id from weights where name = 'Medium') where name = 'Darkrai';
update pokedex set size_id = (select id from sizes where name = 'Gigantic'), weight_id = (select id from weights where name = 'Superweight') where name = 'Yveltal';
update pokedex set size_id = (select id from sizes where name = 'Gigantic'), weight_id = (select id from weights where name = 'Superweight') where name = 'Guzzlord';
update pokedex set size_id = (select id from sizes where name = 'Huge'), weight_id = (select id from weights where name = 'Heavy') where name = 'Zarude';
update pokedex set size_id = (select id from sizes where name = 'Gigantic'), weight_id = (select id from weights where name = 'Superweight') where name = 'Xerneas';

-- Diet
insert into pokedex_diets (pokedex_id, diet_id) values
  ((select id from pokedex where name = 'Groudon'), (select id from diets where name = 'Glacievore')),
  ((select id from pokedex where name = 'Groudon'), (select id from diets where name = 'Terravore')),
  ((select id from pokedex where name = 'Zapdos'), (select id from diets where name = 'Omnivore')),
  ((select id from pokedex where name = 'Raikou'), (select id from diets where name = 'Omnivore')),
  ((select id from pokedex where name = 'Xurkitree'), (select id from diets where name = 'Ergovore')),
  ((select id from pokedex where name = 'Regieleki'), (select id from diets where name = 'Ergovore')),
  ((select id from pokedex where name = 'Regigigas'), (select id from diets where name = 'Ergovore')),
  ((select id from pokedex where name = 'Arceus'), (select id from diets where name = 'Nullivore')),
  ((select id from pokedex where name = 'Silvally'), (select id from diets where name = 'Ergovore')),
  ((select id from pokedex where name = 'Marshadow'), (select id from diets where name = 'Psiotroph')),
  ((select id from pokedex where name = 'Poipole'), (select id from diets where name = 'Omnivore')),
  ((select id from pokedex where name = 'Naganadel'), (select id from diets where name = 'Omnivore')),
  ((select id from pokedex where name = 'Okidogi'), (select id from diets where name = 'Omnivore')),
  ((select id from pokedex where name = 'Munkidori'), (select id from diets where name = 'Omnivore')),
  ((select id from pokedex where name = 'Fezandipiti'), (select id from diets where name = 'Omnivore')),
  ((select id from pokedex where name = 'Pecharunt'), (select id from diets where name = 'Nullivore')),
  ((select id from pokedex where name = 'Regirock'), (select id from diets where name = 'Ergovore')),
  ((select id from pokedex where name = 'Terrakion'), (select id from diets where name = 'Omnivore')),
  ((select id from pokedex where name = 'Diancie'), (select id from diets where name = 'Terravore')),
  ((select id from pokedex where name = 'Stakataka'), (select id from diets where name = 'Terravore')),
  ((select id from pokedex where name = 'Genesect'), (select id from diets where name = 'Ergovore')),
  ((select id from pokedex where name = 'Buzzwole'), (select id from diets where name = 'Omnivore')),
  ((select id from pokedex where name = 'Pheromosa'), (select id from diets where name = 'Omnivore')),
  ((select id from pokedex where name = 'Spectrier'), (select id from diets where name = 'Herbivore')),
  ((select id from pokedex where name = 'Registeel'), (select id from diets where name = 'Ergovore')),
  ((select id from pokedex where name = 'Jirachi'), (select id from diets where name = 'Psiotroph')),
  ((select id from pokedex where name = 'Cobalion'), (select id from diets where name = 'Omnivore')),
  ((select id from pokedex where name = 'Celesteela'), (select id from diets where name = 'Terravore')),
  ((select id from pokedex where name = 'Suicune'), (select id from diets where name = 'Omnivore')),
  ((select id from pokedex where name = 'Kyogre'), (select id from diets where name = 'Omnivore')),
  ((select id from pokedex where name = 'Phione'), (select id from diets where name = 'Herbivore')),
  ((select id from pokedex where name = 'Manaphy'), (select id from diets where name = 'Herbivore')),
  ((select id from pokedex where name = 'Virizion'), (select id from diets where name = 'Omnivore')),
  ((select id from pokedex where name = 'Kartana'), (select id from diets where name = 'Herbivore')),
  ((select id from pokedex where name = 'Celebi'), (select id from diets where name = 'Phototroph')),
  ((select id from pokedex where name = 'Cresselia'), (select id from diets where name = 'Herbivore')),
  ((select id from pokedex where name = 'Victini'), (select id from diets where name = 'Ergovore')),
  ((select id from pokedex where name = 'Victini'), (select id from diets where name = 'Herbivore')),
  ((select id from pokedex where name = 'Cosmog'), (select id from diets where name = 'Phototroph')),
  ((select id from pokedex where name = 'Cosmoem'), (select id from diets where name = 'Phototroph')),
  ((select id from pokedex where name = 'Lunala'), (select id from diets where name = 'Phototroph')),
  ((select id from pokedex where name = 'Necrozma'), (select id from diets where name = 'Omnivore')),
  ((select id from pokedex where name = 'Calyrex'), (select id from diets where name = 'Herbivore')),
  ((select id from pokedex where name = 'Latias'), (select id from diets where name = 'Omnivore')),
  ((select id from pokedex where name = 'Latios'), (select id from diets where name = 'Omnivore')),
  ((select id from pokedex where name = 'Rayquaza'), (select id from diets where name = 'Glacievore')),
  ((select id from pokedex where name = 'Rayquaza'), (select id from diets where name = 'Terravore')),
  ((select id from pokedex where name = 'Reshiram'), (select id from diets where name = 'Omnivore')),
  ((select id from pokedex where name = 'Zekrom'), (select id from diets where name = 'Omnivore')),
  ((select id from pokedex where name = 'Regidrago'), (select id from diets where name = 'Ergovore')),
  ((select id from pokedex where name = 'Darkrai'), (select id from diets where name = 'Psiotroph')),
  ((select id from pokedex where name = 'Yveltal'), (select id from diets where name = 'Carnivore')),
  ((select id from pokedex where name = 'Guzzlord'), (select id from diets where name = 'Omnivore')),
  ((select id from pokedex where name = 'Zarude'), (select id from diets where name = 'Omnivore')),
  ((select id from pokedex where name = 'Xerneas'), (select id from diets where name = 'Herbivore'))
on conflict (pokedex_id, diet_id) do nothing;

-- Habitat
insert into pokedex_habitats (pokedex_id, habitat_id) values
  ((select id from pokedex where name = 'Groudon'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Zapdos'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Zapdos'), (select id from habitats where name = 'Urban Plants')),
  ((select id from pokedex where name = 'Raikou'), (select id from habitats where name = 'Grasslands')),
  ((select id from pokedex where name = 'Raikou'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Xurkitree'), (select id from habitats where name = 'Foreign Dimension')),
  ((select id from pokedex where name = 'Regieleki'), (select id from habitats where name = 'Caves')),
  ((select id from pokedex where name = 'Regieleki'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Regigigas'), (select id from habitats where name = 'Caves')),
  ((select id from pokedex where name = 'Regigigas'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Regigigas'), (select id from habitats where name = 'Tundra')),
  ((select id from pokedex where name = 'Arceus'), (select id from habitats where name = 'Space')),
  ((select id from pokedex where name = 'Silvally'), (select id from habitats where name = 'Caves')),
  ((select id from pokedex where name = 'Silvally'), (select id from habitats where name = 'Urban')),
  ((select id from pokedex where name = 'Marshadow'), (select id from habitats where name = 'Forests')),
  ((select id from pokedex where name = 'Poipole'), (select id from habitats where name = 'Foreign Dimension')),
  ((select id from pokedex where name = 'Naganadel'), (select id from habitats where name = 'Foreign Dimension')),
  ((select id from pokedex where name = 'Okidogi'), (select id from habitats where name = 'Fields')),
  ((select id from pokedex where name = 'Okidogi'), (select id from habitats where name = 'Forests')),
  ((select id from pokedex where name = 'Okidogi'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Munkidori'), (select id from habitats where name = 'Forests')),
  ((select id from pokedex where name = 'Munkidori'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Fezandipiti'), (select id from habitats where name = 'Forests')),
  ((select id from pokedex where name = 'Fezandipiti'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Pecharunt'), (select id from habitats where name = 'Caves')),
  ((select id from pokedex where name = 'Pecharunt'), (select id from habitats where name = 'Forests')),
  ((select id from pokedex where name = 'Pecharunt'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Regirock'), (select id from habitats where name = 'Caves')),
  ((select id from pokedex where name = 'Regirock'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Terrakion'), (select id from habitats where name = 'Caves')),
  ((select id from pokedex where name = 'Terrakion'), (select id from habitats where name = 'Forests')),
  ((select id from pokedex where name = 'Terrakion'), (select id from habitats where name = 'Grasslands')),
  ((select id from pokedex where name = 'Terrakion'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Diancie'), (select id from habitats where name = 'Caves')),
  ((select id from pokedex where name = 'Diancie'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Stakataka'), (select id from habitats where name = 'Foreign Dimension')),
  ((select id from pokedex where name = 'Genesect'), (select id from habitats where name = 'Caves')),
  ((select id from pokedex where name = 'Genesect'), (select id from habitats where name = 'Urban')),
  ((select id from pokedex where name = 'Buzzwole'), (select id from habitats where name = 'Foreign Dimension')),
  ((select id from pokedex where name = 'Pheromosa'), (select id from habitats where name = 'Foreign Dimension')),
  ((select id from pokedex where name = 'Spectrier'), (select id from habitats where name = 'Polar')),
  ((select id from pokedex where name = 'Spectrier'), (select id from habitats where name = 'Tundra')),
  ((select id from pokedex where name = 'Registeel'), (select id from habitats where name = 'Caves')),
  ((select id from pokedex where name = 'Registeel'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Jirachi'), (select id from habitats where name = 'Caves')),
  ((select id from pokedex where name = 'Jirachi'), (select id from habitats where name = 'Forests')),
  ((select id from pokedex where name = 'Jirachi'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Jirachi'), (select id from habitats where name = 'Space')),
  ((select id from pokedex where name = 'Cobalion'), (select id from habitats where name = 'Caves')),
  ((select id from pokedex where name = 'Cobalion'), (select id from habitats where name = 'Forests')),
  ((select id from pokedex where name = 'Cobalion'), (select id from habitats where name = 'Grasslands')),
  ((select id from pokedex where name = 'Cobalion'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Celesteela'), (select id from habitats where name = 'Foreign Dimension')),
  ((select id from pokedex where name = 'Suicune'), (select id from habitats where name = 'Forests')),
  ((select id from pokedex where name = 'Suicune'), (select id from habitats where name = 'Grasslands')),
  ((select id from pokedex where name = 'Kyogre'), (select id from habitats where name = 'Polar')),
  ((select id from pokedex where name = 'Kyogre'), (select id from habitats where name = 'Oceans')),
  ((select id from pokedex where name = 'Phione'), (select id from habitats where name = 'Oceans')),
  ((select id from pokedex where name = 'Manaphy'), (select id from habitats where name = 'Oceans')),
  ((select id from pokedex where name = 'Virizion'), (select id from habitats where name = 'Caves')),
  ((select id from pokedex where name = 'Virizion'), (select id from habitats where name = 'Forests')),
  ((select id from pokedex where name = 'Virizion'), (select id from habitats where name = 'Grasslands')),
  ((select id from pokedex where name = 'Virizion'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Kartana'), (select id from habitats where name = 'Foreign Dimension')),
  ((select id from pokedex where name = 'Celebi'), (select id from habitats where name = 'Forests')),
  ((select id from pokedex where name = 'Celebi'), (select id from habitats where name = 'Jungles')),
  ((select id from pokedex where name = 'Cresselia'), (select id from habitats where name = 'Forests')),
  ((select id from pokedex where name = 'Cresselia'), (select id from habitats where name = 'Jungles')),
  ((select id from pokedex where name = 'Cresselia'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Victini'), (select id from habitats where name = 'Forests')),
  ((select id from pokedex where name = 'Victini'), (select id from habitats where name = 'Urban Plants')),
  ((select id from pokedex where name = 'Cosmog'), (select id from habitats where name = 'Forests')),
  ((select id from pokedex where name = 'Cosmog'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Cosmog'), (select id from habitats where name = 'Space')),
  ((select id from pokedex where name = 'Cosmoem'), (select id from habitats where name = 'Forests')),
  ((select id from pokedex where name = 'Cosmoem'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Cosmoem'), (select id from habitats where name = 'Space')),
  ((select id from pokedex where name = 'Lunala'), (select id from habitats where name = 'Forests')),
  ((select id from pokedex where name = 'Lunala'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Lunala'), (select id from habitats where name = 'Space')),
  ((select id from pokedex where name = 'Necrozma'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Necrozma'), (select id from habitats where name = 'Space')),
  ((select id from pokedex where name = 'Calyrex'), (select id from habitats where name = 'Polar')),
  ((select id from pokedex where name = 'Calyrex'), (select id from habitats where name = 'Tundra')),
  ((select id from pokedex where name = 'Latias'), (select id from habitats where name = 'Beaches')),
  ((select id from pokedex where name = 'Latias'), (select id from habitats where name = 'Forests')),
  ((select id from pokedex where name = 'Latias'), (select id from habitats where name = 'Grasslands')),
  ((select id from pokedex where name = 'Latias'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Latios'), (select id from habitats where name = 'Beaches')),
  ((select id from pokedex where name = 'Latios'), (select id from habitats where name = 'Forests')),
  ((select id from pokedex where name = 'Latios'), (select id from habitats where name = 'Grasslands')),
  ((select id from pokedex where name = 'Latios'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Rayquaza'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Reshiram'), (select id from habitats where name = 'Space')),
  ((select id from pokedex where name = 'Zekrom'), (select id from habitats where name = 'Space')),
  ((select id from pokedex where name = 'Regidrago'), (select id from habitats where name = 'Caves')),
  ((select id from pokedex where name = 'Regidrago'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Darkrai'), (select id from habitats where name = 'Caves')),
  ((select id from pokedex where name = 'Darkrai'), (select id from habitats where name = 'Forests')),
  ((select id from pokedex where name = 'Darkrai'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Yveltal'), (select id from habitats where name = 'Mountains')),
  ((select id from pokedex where name = 'Guzzlord'), (select id from habitats where name = 'Foreign Dimension')),
  ((select id from pokedex where name = 'Zarude'), (select id from habitats where name = 'Forests')),
  ((select id from pokedex where name = 'Zarude'), (select id from habitats where name = 'Jungles')),
  ((select id from pokedex where name = 'Xerneas'), (select id from habitats where name = 'Forests'))
on conflict (pokedex_id, habitat_id) do nothing;

-- Proficiencies (Arceus/Cosmog/Cosmoem/Lunala deliberately excluded -- their source text is prose
-- ("can know any move") not a real proficiency list, left with none rather than force-fit)
insert into pokedex_proficiencies (pokedex_id, proficiency_id) values
  ((select id from pokedex where name = 'Groudon'), (select id from proficiencies where name = 'Dragon')),
  ((select id from pokedex where name = 'Groudon'), (select id from proficiencies where name = 'Flying')),
  ((select id from pokedex where name = 'Groudon'), (select id from proficiencies where name = 'Slashing')),
  ((select id from pokedex where name = 'Groudon'), (select id from proficiencies where name = 'Draconian')),
  ((select id from pokedex where name = 'Groudon'), (select id from proficiencies where name = 'Stampeding')),
  ((select id from pokedex where name = 'Zapdos'), (select id from proficiencies where name = 'Electric')),
  ((select id from pokedex where name = 'Raikou'), (select id from proficiencies where name = 'Electric')),
  ((select id from pokedex where name = 'Raikou'), (select id from proficiencies where name = 'Slashing')),
  ((select id from pokedex where name = 'Raikou'), (select id from proficiencies where name = 'Fangs')),
  ((select id from pokedex where name = 'Raikou'), (select id from proficiencies where name = 'Weather')),
  ((select id from pokedex where name = 'Xurkitree'), (select id from proficiencies where name = 'Electric')),
  ((select id from pokedex where name = 'Xurkitree'), (select id from proficiencies where name = 'Energy Blast')),
  ((select id from pokedex where name = 'Xurkitree'), (select id from proficiencies where name = 'Parasitic')),
  ((select id from pokedex where name = 'Regieleki'), (select id from proficiencies where name = 'Electric')),
  ((select id from pokedex where name = 'Regieleki'), (select id from proficiencies where name = 'Magnetism')),
  ((select id from pokedex where name = 'Regieleki'), (select id from proficiencies where name = 'Stampeding')),
  ((select id from pokedex where name = 'Regigigas'), (select id from proficiencies where name = 'Dragon')),
  ((select id from pokedex where name = 'Regigigas'), (select id from proficiencies where name = 'Electric')),
  ((select id from pokedex where name = 'Regigigas'), (select id from proficiencies where name = 'Ice')),
  ((select id from pokedex where name = 'Regigigas'), (select id from proficiencies where name = 'Rock')),
  ((select id from pokedex where name = 'Regigigas'), (select id from proficiencies where name = 'Steel')),
  ((select id from pokedex where name = 'Regigigas'), (select id from proficiencies where name = 'Bruiser')),
  ((select id from pokedex where name = 'Regigigas'), (select id from proficiencies where name = 'Energy Blast')),
  ((select id from pokedex where name = 'Regigigas'), (select id from proficiencies where name = 'Stampeding')),
  ((select id from pokedex where name = 'Silvally'), (select id from proficiencies where name = 'Bug')),
  ((select id from pokedex where name = 'Silvally'), (select id from proficiencies where name = 'Electric')),
  ((select id from pokedex where name = 'Silvally'), (select id from proficiencies where name = 'Steel')),
  ((select id from pokedex where name = 'Silvally'), (select id from proficiencies where name = 'Magnetism')),
  ((select id from pokedex where name = 'Marshadow'), (select id from proficiencies where name = 'Fighting')),
  ((select id from pokedex where name = 'Marshadow'), (select id from proficiencies where name = 'Ghost')),
  ((select id from pokedex where name = 'Marshadow'), (select id from proficiencies where name = 'Bruiser')),
  ((select id from pokedex where name = 'Marshadow'), (select id from proficiencies where name = 'Martial')),
  ((select id from pokedex where name = 'Poipole'), (select id from proficiencies where name = 'Dragon')),
  ((select id from pokedex where name = 'Poipole'), (select id from proficiencies where name = 'Poison')),
  ((select id from pokedex where name = 'Poipole'), (select id from proficiencies where name = 'Draconian')),
  ((select id from pokedex where name = 'Poipole'), (select id from proficiencies where name = 'Prickly')),
  ((select id from pokedex where name = 'Poipole'), (select id from proficiencies where name = 'Winged')),
  ((select id from pokedex where name = 'Naganadel'), (select id from proficiencies where name = 'Dragon')),
  ((select id from pokedex where name = 'Naganadel'), (select id from proficiencies where name = 'Poison')),
  ((select id from pokedex where name = 'Naganadel'), (select id from proficiencies where name = 'Draconian')),
  ((select id from pokedex where name = 'Naganadel'), (select id from proficiencies where name = 'Prickly')),
  ((select id from pokedex where name = 'Naganadel'), (select id from proficiencies where name = 'Winged')),
  ((select id from pokedex where name = 'Okidogi'), (select id from proficiencies where name = 'Dark')),
  ((select id from pokedex where name = 'Okidogi'), (select id from proficiencies where name = 'Fighting')),
  ((select id from pokedex where name = 'Okidogi'), (select id from proficiencies where name = 'Poison')),
  ((select id from pokedex where name = 'Okidogi'), (select id from proficiencies where name = 'Fangs')),
  ((select id from pokedex where name = 'Okidogi'), (select id from proficiencies where name = 'Martial')),
  ((select id from pokedex where name = 'Munkidori'), (select id from proficiencies where name = 'Dark')),
  ((select id from pokedex where name = 'Munkidori'), (select id from proficiencies where name = 'Poison')),
  ((select id from pokedex where name = 'Munkidori'), (select id from proficiencies where name = 'Psychic')),
  ((select id from pokedex where name = 'Munkidori'), (select id from proficiencies where name = 'Energy Blast')),
  ((select id from pokedex where name = 'Fezandipiti'), (select id from proficiencies where name = 'Dark')),
  ((select id from pokedex where name = 'Fezandipiti'), (select id from proficiencies where name = 'Flying')),
  ((select id from pokedex where name = 'Fezandipiti'), (select id from proficiencies where name = 'Poison')),
  ((select id from pokedex where name = 'Fezandipiti'), (select id from proficiencies where name = 'Avian')),
  ((select id from pokedex where name = 'Fezandipiti'), (select id from proficiencies where name = 'Winged')),
  ((select id from pokedex where name = 'Pecharunt'), (select id from proficiencies where name = 'Dark')),
  ((select id from pokedex where name = 'Pecharunt'), (select id from proficiencies where name = 'Ghost')),
  ((select id from pokedex where name = 'Pecharunt'), (select id from proficiencies where name = 'Poison')),
  ((select id from pokedex where name = 'Pecharunt'), (select id from proficiencies where name = 'Hexwork')),
  ((select id from pokedex where name = 'Pecharunt'), (select id from proficiencies where name = 'Spellcraft')),
  ((select id from pokedex where name = 'Pecharunt'), (select id from proficiencies where name = 'Tricky')),
  ((select id from pokedex where name = 'Pecharunt'), (select id from proficiencies where name = 'Weird')),
  ((select id from pokedex where name = 'Regirock'), (select id from proficiencies where name = 'Electric')),
  ((select id from pokedex where name = 'Regirock'), (select id from proficiencies where name = 'Rock')),
  ((select id from pokedex where name = 'Regirock'), (select id from proficiencies where name = 'Magnetism')),
  ((select id from pokedex where name = 'Regirock'), (select id from proficiencies where name = 'Stampeding')),
  ((select id from pokedex where name = 'Terrakion'), (select id from proficiencies where name = 'Fighting')),
  ((select id from pokedex where name = 'Terrakion'), (select id from proficiencies where name = 'Rock')),
  ((select id from pokedex where name = 'Terrakion'), (select id from proficiencies where name = 'Slashing')),
  ((select id from pokedex where name = 'Terrakion'), (select id from proficiencies where name = 'Stampeding')),
  ((select id from pokedex where name = 'Diancie'), (select id from proficiencies where name = 'Fairy')),
  ((select id from pokedex where name = 'Diancie'), (select id from proficiencies where name = 'Psychic')),
  ((select id from pokedex where name = 'Diancie'), (select id from proficiencies where name = 'Rock')),
  ((select id from pokedex where name = 'Diancie'), (select id from proficiencies where name = 'Cutesy')),
  ((select id from pokedex where name = 'Diancie'), (select id from proficiencies where name = 'Magnetism')),
  ((select id from pokedex where name = 'Stakataka'), (select id from proficiencies where name = 'Steel')),
  ((select id from pokedex where name = 'Stakataka'), (select id from proficiencies where name = 'Rock')),
  ((select id from pokedex where name = 'Stakataka'), (select id from proficiencies where name = 'Magnetism')),
  ((select id from pokedex where name = 'Stakataka'), (select id from proficiencies where name = 'Stampeding')),
  ((select id from pokedex where name = 'Genesect'), (select id from proficiencies where name = 'Bug')),
  ((select id from pokedex where name = 'Genesect'), (select id from proficiencies where name = 'Electric')),
  ((select id from pokedex where name = 'Genesect'), (select id from proficiencies where name = 'Steel')),
  ((select id from pokedex where name = 'Genesect'), (select id from proficiencies where name = 'Magnetism')),
  ((select id from pokedex where name = 'Buzzwole'), (select id from proficiencies where name = 'Bug')),
  ((select id from pokedex where name = 'Buzzwole'), (select id from proficiencies where name = 'Fighting')),
  ((select id from pokedex where name = 'Buzzwole'), (select id from proficiencies where name = 'Martial')),
  ((select id from pokedex where name = 'Pheromosa'), (select id from proficiencies where name = 'Bug')),
  ((select id from pokedex where name = 'Pheromosa'), (select id from proficiencies where name = 'Fighting')),
  ((select id from pokedex where name = 'Pheromosa'), (select id from proficiencies where name = 'Lepidopteran')),
  ((select id from pokedex where name = 'Spectrier'), (select id from proficiencies where name = 'Fighting')),
  ((select id from pokedex where name = 'Spectrier'), (select id from proficiencies where name = 'Ghost')),
  ((select id from pokedex where name = 'Spectrier'), (select id from proficiencies where name = 'Stampeding')),
  ((select id from pokedex where name = 'Spectrier'), (select id from proficiencies where name = 'Weird')),
  ((select id from pokedex where name = 'Registeel'), (select id from proficiencies where name = 'Electric')),
  ((select id from pokedex where name = 'Registeel'), (select id from proficiencies where name = 'Steel')),
  ((select id from pokedex where name = 'Registeel'), (select id from proficiencies where name = 'Magnetism')),
  ((select id from pokedex where name = 'Registeel'), (select id from proficiencies where name = 'Stampeding')),
  ((select id from pokedex where name = 'Jirachi'), (select id from proficiencies where name = 'Psychic')),
  ((select id from pokedex where name = 'Jirachi'), (select id from proficiencies where name = 'Steel')),
  ((select id from pokedex where name = 'Jirachi'), (select id from proficiencies where name = 'Cutesy')),
  ((select id from pokedex where name = 'Jirachi'), (select id from proficiencies where name = 'Healer')),
  ((select id from pokedex where name = 'Cobalion'), (select id from proficiencies where name = 'Fighting')),
  ((select id from pokedex where name = 'Cobalion'), (select id from proficiencies where name = 'Steel')),
  ((select id from pokedex where name = 'Cobalion'), (select id from proficiencies where name = 'Slashing')),
  ((select id from pokedex where name = 'Cobalion'), (select id from proficiencies where name = 'Stampeding')),
  ((select id from pokedex where name = 'Celesteela'), (select id from proficiencies where name = 'Flying')),
  ((select id from pokedex where name = 'Celesteela'), (select id from proficiencies where name = 'Grass')),
  ((select id from pokedex where name = 'Celesteela'), (select id from proficiencies where name = 'Steel')),
  ((select id from pokedex where name = 'Celesteela'), (select id from proficiencies where name = 'Stampeding')),
  ((select id from pokedex where name = 'Suicune'), (select id from proficiencies where name = 'Ice')),
  ((select id from pokedex where name = 'Suicune'), (select id from proficiencies where name = 'Water')),
  ((select id from pokedex where name = 'Suicune'), (select id from proficiencies where name = 'Slashing')),
  ((select id from pokedex where name = 'Suicune'), (select id from proficiencies where name = 'Fangs')),
  ((select id from pokedex where name = 'Suicune'), (select id from proficiencies where name = 'Weather')),
  ((select id from pokedex where name = 'Kyogre'), (select id from proficiencies where name = 'Ice')),
  ((select id from pokedex where name = 'Kyogre'), (select id from proficiencies where name = 'Water')),
  ((select id from pokedex where name = 'Kyogre'), (select id from proficiencies where name = 'Piscian')),
  ((select id from pokedex where name = 'Kyogre'), (select id from proficiencies where name = 'Stampeding')),
  ((select id from pokedex where name = 'Phione'), (select id from proficiencies where name = 'Water')),
  ((select id from pokedex where name = 'Phione'), (select id from proficiencies where name = 'Cutesy')),
  ((select id from pokedex where name = 'Phione'), (select id from proficiencies where name = 'Piscian')),
  ((select id from pokedex where name = 'Manaphy'), (select id from proficiencies where name = 'Water')),
  ((select id from pokedex where name = 'Manaphy'), (select id from proficiencies where name = 'Cutesy')),
  ((select id from pokedex where name = 'Manaphy'), (select id from proficiencies where name = 'Healer')),
  ((select id from pokedex where name = 'Manaphy'), (select id from proficiencies where name = 'Piscian')),
  ((select id from pokedex where name = 'Virizion'), (select id from proficiencies where name = 'Fighting')),
  ((select id from pokedex where name = 'Virizion'), (select id from proficiencies where name = 'Grass')),
  ((select id from pokedex where name = 'Virizion'), (select id from proficiencies where name = 'Slashing')),
  ((select id from pokedex where name = 'Virizion'), (select id from proficiencies where name = 'Stampeding')),
  ((select id from pokedex where name = 'Kartana'), (select id from proficiencies where name = 'Slashing')),
  ((select id from pokedex where name = 'Celebi'), (select id from proficiencies where name = 'Grass')),
  ((select id from pokedex where name = 'Celebi'), (select id from proficiencies where name = 'Psychic')),
  ((select id from pokedex where name = 'Celebi'), (select id from proficiencies where name = 'Cutesy')),
  ((select id from pokedex where name = 'Celebi'), (select id from proficiencies where name = 'Healer')),
  ((select id from pokedex where name = 'Celebi'), (select id from proficiencies where name = 'Winged')),
  ((select id from pokedex where name = 'Cresselia'), (select id from proficiencies where name = 'Fairy')),
  ((select id from pokedex where name = 'Cresselia'), (select id from proficiencies where name = 'Psychic')),
  ((select id from pokedex where name = 'Cresselia'), (select id from proficiencies where name = 'Energy Blast')),
  ((select id from pokedex where name = 'Cresselia'), (select id from proficiencies where name = 'Healer')),
  ((select id from pokedex where name = 'Cresselia'), (select id from proficiencies where name = 'Spellcraft')),
  ((select id from pokedex where name = 'Victini'), (select id from proficiencies where name = 'Fire')),
  ((select id from pokedex where name = 'Victini'), (select id from proficiencies where name = 'Fighting')),
  ((select id from pokedex where name = 'Victini'), (select id from proficiencies where name = 'Psychic')),
  ((select id from pokedex where name = 'Victini'), (select id from proficiencies where name = 'Cutesy')),
  ((select id from pokedex where name = 'Victini'), (select id from proficiencies where name = 'Energy Blast')),
  ((select id from pokedex where name = 'Necrozma'), (select id from proficiencies where name = 'Ghost')),
  ((select id from pokedex where name = 'Necrozma'), (select id from proficiencies where name = 'Psychic')),
  ((select id from pokedex where name = 'Necrozma'), (select id from proficiencies where name = 'Rock')),
  ((select id from pokedex where name = 'Necrozma'), (select id from proficiencies where name = 'Steel')),
  ((select id from pokedex where name = 'Necrozma'), (select id from proficiencies where name = 'Slashing')),
  ((select id from pokedex where name = 'Calyrex'), (select id from proficiencies where name = 'Grass')),
  ((select id from pokedex where name = 'Calyrex'), (select id from proficiencies where name = 'Psychic')),
  ((select id from pokedex where name = 'Calyrex'), (select id from proficiencies where name = 'Energy Blast')),
  ((select id from pokedex where name = 'Calyrex'), (select id from proficiencies where name = 'Healer')),
  ((select id from pokedex where name = 'Calyrex'), (select id from proficiencies where name = 'Pulse')),
  ((select id from pokedex where name = 'Latias'), (select id from proficiencies where name = 'Psychic')),
  ((select id from pokedex where name = 'Latias'), (select id from proficiencies where name = 'Dragon')),
  ((select id from pokedex where name = 'Latias'), (select id from proficiencies where name = 'Draconian')),
  ((select id from pokedex where name = 'Latias'), (select id from proficiencies where name = 'Energy Blast')),
  ((select id from pokedex where name = 'Latios'), (select id from proficiencies where name = 'Psychic')),
  ((select id from pokedex where name = 'Latios'), (select id from proficiencies where name = 'Dragon')),
  ((select id from pokedex where name = 'Latios'), (select id from proficiencies where name = 'Draconian')),
  ((select id from pokedex where name = 'Latios'), (select id from proficiencies where name = 'Energy Blast')),
  ((select id from pokedex where name = 'Rayquaza'), (select id from proficiencies where name = 'Dragon')),
  ((select id from pokedex where name = 'Rayquaza'), (select id from proficiencies where name = 'Flying')),
  ((select id from pokedex where name = 'Rayquaza'), (select id from proficiencies where name = 'Slashing')),
  ((select id from pokedex where name = 'Rayquaza'), (select id from proficiencies where name = 'Draconian')),
  ((select id from pokedex where name = 'Rayquaza'), (select id from proficiencies where name = 'Stampeding')),
  ((select id from pokedex where name = 'Reshiram'), (select id from proficiencies where name = 'Dragon')),
  ((select id from pokedex where name = 'Reshiram'), (select id from proficiencies where name = 'Fire')),
  ((select id from pokedex where name = 'Reshiram'), (select id from proficiencies where name = 'Psychic')),
  ((select id from pokedex where name = 'Reshiram'), (select id from proficiencies where name = 'Slashing')),
  ((select id from pokedex where name = 'Reshiram'), (select id from proficiencies where name = 'Draconian')),
  ((select id from pokedex where name = 'Zekrom'), (select id from proficiencies where name = 'Dragon')),
  ((select id from pokedex where name = 'Zekrom'), (select id from proficiencies where name = 'Electric')),
  ((select id from pokedex where name = 'Zekrom'), (select id from proficiencies where name = 'Psychic')),
  ((select id from pokedex where name = 'Zekrom'), (select id from proficiencies where name = 'Slashing')),
  ((select id from pokedex where name = 'Zekrom'), (select id from proficiencies where name = 'Draconian')),
  ((select id from pokedex where name = 'Zekrom'), (select id from proficiencies where name = 'Winged')),
  ((select id from pokedex where name = 'Regidrago'), (select id from proficiencies where name = 'Dragon')),
  ((select id from pokedex where name = 'Regidrago'), (select id from proficiencies where name = 'Draconian')),
  ((select id from pokedex where name = 'Regidrago'), (select id from proficiencies where name = 'Fangs')),
  ((select id from pokedex where name = 'Regidrago'), (select id from proficiencies where name = 'Magnetism')),
  ((select id from pokedex where name = 'Darkrai'), (select id from proficiencies where name = 'Dark')),
  ((select id from pokedex where name = 'Darkrai'), (select id from proficiencies where name = 'Psychic')),
  ((select id from pokedex where name = 'Darkrai'), (select id from proficiencies where name = 'Slashing')),
  ((select id from pokedex where name = 'Darkrai'), (select id from proficiencies where name = 'Hexwork')),
  ((select id from pokedex where name = 'Darkrai'), (select id from proficiencies where name = 'Tricky')),
  ((select id from pokedex where name = 'Yveltal'), (select id from proficiencies where name = 'Dark')),
  ((select id from pokedex where name = 'Yveltal'), (select id from proficiencies where name = 'Ghost')),
  ((select id from pokedex where name = 'Yveltal'), (select id from proficiencies where name = 'Flying')),
  ((select id from pokedex where name = 'Yveltal'), (select id from proficiencies where name = 'Slashing')),
  ((select id from pokedex where name = 'Yveltal'), (select id from proficiencies where name = 'Energy Blast')),
  ((select id from pokedex where name = 'Yveltal'), (select id from proficiencies where name = 'Winged')),
  ((select id from pokedex where name = 'Guzzlord'), (select id from proficiencies where name = 'Dark')),
  ((select id from pokedex where name = 'Guzzlord'), (select id from proficiencies where name = 'Dragon')),
  ((select id from pokedex where name = 'Guzzlord'), (select id from proficiencies where name = 'Poison')),
  ((select id from pokedex where name = 'Guzzlord'), (select id from proficiencies where name = 'Draconian')),
  ((select id from pokedex where name = 'Guzzlord'), (select id from proficiencies where name = 'Glutton')),
  ((select id from pokedex where name = 'Guzzlord'), (select id from proficiencies where name = 'Stampeding')),
  ((select id from pokedex where name = 'Zarude'), (select id from proficiencies where name = 'Dark')),
  ((select id from pokedex where name = 'Zarude'), (select id from proficiencies where name = 'Grass')),
  ((select id from pokedex where name = 'Zarude'), (select id from proficiencies where name = 'Bruiser')),
  ((select id from pokedex where name = 'Zarude'), (select id from proficiencies where name = 'Slashing')),
  ((select id from pokedex where name = 'Zarude'), (select id from proficiencies where name = 'Fangs')),
  ((select id from pokedex where name = 'Xerneas'), (select id from proficiencies where name = 'Fairy')),
  ((select id from pokedex where name = 'Xerneas'), (select id from proficiencies where name = 'Grass')),
  ((select id from pokedex where name = 'Xerneas'), (select id from proficiencies where name = 'Psychic')),
  ((select id from pokedex where name = 'Xerneas'), (select id from proficiencies where name = 'Healer')),
  ((select id from pokedex where name = 'Xerneas'), (select id from proficiencies where name = 'Horned'))
on conflict (pokedex_id, proficiency_id) do nothing;
