-- Fill out the Items table, batch 8: Trainer Pack Bundles. Source: PTA3PlayersHandbook.pdf pages
-- 198-200. Flat category, no detail table -- weight/dimensions/contents are all flavor text with
-- nothing else in this app that would consume them structurally (matches Trainer Pack Bundles' own
-- framing: "there's no reason you can't pick one up on your own regardless of your origin," i.e.
-- flavor/starting-loadout items, not mechanically distinct from each other the way Poké Balls or
-- Berries are).
--
-- Kept the PDF's packing-list descriptions in full rather than trimming them -- some minor formatting
-- artifacts survived from the source's own comma-less parenthetical counts (e.g. "primers (2 3 oz.)"
-- almost certainly means "2, 3 oz. containers" with a dropped comma) -- preserved as extracted rather
-- than guessed at, since silently "fixing" ambiguous formatting risks introducing a wrong reading.
--
-- Miscreant's Pack is the one exception to "all buyable": its own description says "there's no real
-- reason to have this, let alone sell it... may not be easily found and available in stores" -- treated
-- as not normally purchasable, same tier as Master Ball/HM's "hard to find" precedent.
insert into item_categories (name) values ('Trainer Pack Bundles');

insert into items (name, item_category_id, buyable, price, description)
select v.name, c.id, v.buyable, v.price, v.description
from item_categories c,
(values
  ('Basic Tool Kit', true, 150, 'Basic tools for basic repairs or maintenance. Includes hammer, screwdriver (adaptable head), wrench, handsaw, steel ruler, level, nails (40 assorted), screws (40 assorted), nuts and bolts (40 assorted), and a tackle box they fit snuggly in with little room for anything else. 8 lbs. 14x6x6 in.'),
  ('Camera Bag', true, 150, 'Everything you need as a travelling photographer, minus the camera. Includes lenses (3), extra bulbs (2), gaffer tape, microfiber cloth, micro screw driver, micro flash light, extra battery (1), extra memory card (20 GB), ear plugs, and the bag which has room for your camera (camera not included). 18x10x8 in. 3 lbs.'),
  ('Cooking Kit', true, 850, 'For the chef on the go, in the wilds. Includes portable electric stove (2 burners), cast iron pan, cast iron pot with lid, water purifier, cutting board, cutting knife, measuring cups and spoons, spatula, cooking spoon, and a sturdy bag it all fits into. The electric stove can be charged to use for two weeks after a 4-hour charge. 35 lbs. 2x2x1 ft. 4 ft strap.'),
  ('Dig Kit', true, 150, 'Whatever you''re looking for, this should help. Includes extendable shovel, extendable pickaxe, hammer, trowel, compass, measuring tape (25ft), 6 in. stakes (10), string (600 ft), and a tool roll bag with some room for more equipment. 15 lbs. 16x6x4 in. 4ft strap.'),
  ('Drawing Kit', true, 20, 'For an artist, or maybe just a doodler. Includes drawing pad (200pp), journal (200pp), blue pencils (10), mechanical pencils (2), kneaded eraser, white vinyl eraser, blender, pen and ink, assorted brush pens (10), and a bag with extra room to carry it all. 4 lbs. 20x18x3 in. 3ft strap.'),
  ('Engineer''s Tool Kit', true, 1050, 'If you''re building something on the go, or taking something else apart, maybe you''ll need this? Electric unfolding soldering table (2x2 ft), soldering iron, desoldering pump, assorted soldering iron tips (8), soldering assist tools (2), tin wire tube, tweezers, wire stripper cutter, electric wire (80 ft), long nose pliers (2), precision screwdriver, magnetic/gripping retrieving tool, telescoping mirror, various spare screws (100). The table folds into itself while storing all of the supplies, revealing a handle. 15 lbs. 24x12x4 in.'),
  ('Fishing Kit', true, 750, 'For trainers who are looking to lure underwater Pokémon to the surface. Includes telescoping fishing rod, spare reel lines (2), assorted hooks (100), assorted bobbers (10), sinkers (10), assorted lures (10), needle nose pliers, small knife, and a tackle box with room to store a bit more. 8 lbs. 14x6x6 in.'),
  ('Grooming Kit', true, 150, 'Your Pokémon will always look their best when you''re using this kit. Includes electronic trimmer, trimmer length attachments (8), assorted combs (5), assorted brushes (5), assorted scissors/shears (3), clippers, nail file, soap (8 oz.), shampoo (8 oz.), and bag with room for more. The trimmer can be charged to use for one week after a 1-hour charge. 4 lbs. 12x8x8 in. 2ft strap.'),
  ('Make Up Kit', true, 150, 'You will always look your best when you''re with this kit. Includes moisturizer (8 oz.), primers (2, 3 oz.), concealers (2, 3 oz.), foundation (3 oz.), assorted blush (4, 2 oz.), assorted bronzer/highlighter (4, 2 oz.), powders (4, 3 oz.), setting spray (3 oz.), eyeliner pencil, liquid eyeliner (2 oz.), assorted mascara (4, 1 oz.), lash curler, assorted lip balm (4, 1 oz.), assorted lipstick (4), assorted lip gloss (4, 1oz.), and a collapsing case with room to expand your options. 4 lbs. 16x12x4 in.'),
  ('Medical Field Kit', true, 2150, 'Includes pain relievers (20 pills), antihistamine (20 pills), cold/flu relievers (20 pills), electrolyte tablets (20 pills), antiseptic solution (8 oz.), antiseptic gel (8 oz.), medical adhesive tape (30ft), slings (2), crepe bandages (2, 3ft. rolls), cloth bandages (4, 3ft. rolls), gauze swabs (30), stitch strips (20), ear plugs (10), safety pins (20), thermometer, small scissors, small scalpel, tweezers, and assorted adhesive bandages (40), and a folding carrying case it all fits snuggly into. Less useful with Pokémon unless you are proficient in its use. As an action, attempt a Medicine skill check of 15 to stabilize an unconscious trainer to 1 hit point (or spend 5 minutes to do so automatically when out of combat). Out of combat, you may attempt a Medicine skill check of 15 once per hour to cure a target of any affliction.'),
  ('Mess Kit', true, 10, 'Everything you need to enjoy a meal on the go. Includes a plate, a bowl, a fork, a spoon, a knife, a cup, and a slip it all fits into neatly. 1.5 lbs. 10x10x3 in.'),
  ('Miscreant''s Pack', false, 250, 'There''s no real reason to have this, let alone sell it -- may not be easily found and available in stores. Includes solar charger, universal power adapter, universal adapter dongle, memory sticks (4, 80 GB), micro file (2), lock picks (8), multi-head screwdriver, hammer, crowbar, small narrow saw, small narrow scissors, telescoping mirror, thin wire (20 ft), water bottle, and a backpack or side pack to fit everything with some extra room. 10 lbs. 30x16x16 in.'),
  ('Poké Ball Smith Kit', true, 1250, 'If you''re planning to make your own Poké Balls, this will be necessary. Includes electric unfolding soldering table (2x2 ft), soldering iron, desoldering pump, assorted soldering iron tips (8), tin wire tube, tweezers, wire stripper cutter, electric wire (80 ft), micro screwdriver, micro screws (400), micro glass and mirror spares (200), micro rods (200), micro steel sheets (200). The table folds into itself while storing all of the supplies, revealing a handle. 15 lbs. 24x12x4 in.'),
  ('Portable Chemistry Set', true, 850, 'Science on the go! Includes portable Bunsen burner, beakers (1x 250 ml, 1x 50 ml), conical flask (100 ml), measuring cylinder (25ml), test tubes (6x 10 ml), reusable spray bottles (6), test tube rack, heat clamps, thermometer, glass dropper, stirring rod, cleaning brush, corks (12), mortar and pestle, Nuffield spatula, and a padded case to hold everything securely. The reusable bottles can store concoctions to be reused once cleaned. 12 lbs. 2x1x1 ft. 4ft strap.'),
  ('Sewing Kit', true, 200, 'This is useful for the designer on the go. Includes electronic folding sewing machine, measuring tape (6ft), assorted buttons and fasteners (50), assorted spools of thread (20), hand-sewing needles (10), fabric pens (10), bleach pen, stain removing pen, pins (50), needle threader, pincushion, fabric shears, seam ripper, thimbles. The sewing machine folds into itself while storing all of the supplies, revealing a handle, and can be charged to use for two weeks after a 4-hour charge. 20 lbs. 2x1x1 ft.'),
  ('Spiritualist''s Pack', true, 60, 'For those who travel and spread the word of various greater beings. Includes solar charger, universal power adapter, religious texts (2), religious symbol, candles (10), incense sticks (20), waterproof matches (25), water bottle, and a backpack or side pack to fit everything with a great deal of extra room. 5 lbs. 30x16x16 in.'),
  ('Studious Pack', true, 80, 'Useful things for a trainer with a knack for academics. Includes solar charger, universal power adapter, universal adapter dongle, memory stick (40 GB), binder, folders (6), notebooks (3), journal, notepad, pencils (5), pens (3), highlighter, vinyl eraser, pencil sharpener, ruler, headphones, water bottle, and a backpack or side pack to fit everything with extra room for your laptop among other things (laptop not included). 10 lbs. 30x16x16 in.'),
  ('Traveler''s Pack', true, 150, 'Really useful gear for extended travel through the wilds. Includes collapsible pop-up tent (two-person 7x4 ft), tarp (8x10 ft), sleeping bag, pocket knife, solar flashlight, compass, waterproof matches (20), water bottle, and a compression sack with straps to snuggly fit everything. 15 lbs. 40x16x16 in.'),
  ('Trainer''s Pack', true, 80, 'Basic goods for a trainer who''s starting their journey. Includes solar charger, universal power adapter, compression bands (4), crepe bandages (4), micro screwdriver, water bottle, and a backpack or side pack to fit everything with a great deal of extra room. 5 lbs. 30x16x16 in.')
) as v(name, buyable, price, description)
where c.name = 'Trainer Pack Bundles';
